### ISSUE TITLE
UnicodeDecodeError when running python setup.py egg_info

### ISSUE THREAD

**Issue by david-caro** [pypa/setuptools#1392] opened 2018-06-20 13:31 UTC
Hi!

I'm getting the above error when trying to install a package though tox. So, with tox, I'm trying to install a package that has `dulwich` as `setup_requires` in the `setup.py` file. That ends up with the following stack trace:
```python
 Downloading https://files.pythonhosted.org/packages/f4/43/efec01f4eb07d51a7967688a7c52bc7a90619110f836d466e28718676a6c/dulwich-0.19.3.tar.gz (345kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_oyvn4sp/dulwich/setup.py", line 96, in <module>
        **setup_kwargs
      File "/code/.tox/py36/lib/python3.6/site-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/code/.tox/py36/lib/python3.6/site-packages/setuptools/__init__.py", line 121, in _install_setup_requires
        dist.parse_config_files(ignore_option_errors=True)
      File "/code/.tox/py36/lib/python3.6/site-packages/setuptools/dist.py", line 492, in parse_config_files
        _Distribution.parse_config_files(self, filenames=filenames)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 395, in parse_config_files
        parser.read(filename)
      File "/usr/local/lib/python3.6/configparser.py", line 697, in read
        self._read(fp, filename)
      File "/usr/local/lib/python3.6/configparser.py", line 1015, in _read
        for lineno, line in enumerate(fp, start=1):
      File "/code/.tox/py36/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 48: ordinal not in range(128)
```

If I manually add the package or try to install it through tox using a requires.txt file before that, it works well. It seems to be failing because the package has some non-ascii chars in the setup.cfg file.

Thanks

**Comment by david-caro** [comment] 2018-06-20 13:33
btw. I'm using the python:3.6 docker image:
```
root@918551a46cfa:/code# python --version
Python 3.6.5
root@918551a46cfa:/code# tox --version
3.0.0 imported from /usr/local/lib/python3.6/site-packages/tox/__init__.py
```

**Comment by carlajiji** [comment] 2018-07-10 19:10
I'm using the python:3.6 too.

**Comment by pganssle** [comment] 2018-10-23 14:16
Apparently this is a duplicate of #1062.

**Closed by pganssle** 2018-10-23 14:16 UTC
Labels: Needs Triage
