### ISSUE TITLE
Add prominent link to python-packaging RTD?

### ISSUE THREAD

**Issue by warsaw** [pypa/setuptools#1856] opened 2019-10-04 17:37 UTC
I was trying to find the definition of the `scripts` keyword in `setup.py` and `setup.cfg` as a reference for other documentation I was writing.  I was frustrated to find that it's not defined in the setuptools documentation, but instead on [python-packaging RTD](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-scripts-keyword-argument).

I wonder if the API documentation for setuptools, shouldn't prominently link to python-packaging for detailed keyword/option documentation?

**Comment by pganssle** [comment] 2019-10-04 17:41
@warsaw That is not actually any sort of official thing, it's not associated with the PyPA and  I am pretty sure it's unmaintained and horribly out-of-date.

What we really need to do is:

1. Merge #1765 / Close #1700 
2. Move the rest of the `distutils` documentation into setuptools' documentation.

Right now the setuptools documentation only documents the differences between distutils and setuptools, and the distutils documentation says, "Use setuptools". This is part of one of the [fundable packaging improvements](https://wiki.python.org/psf/Fundable%20Packaging%20Improvements#Make_setuptools_the_reference_implementation_of_the_distutils_API) that is high on the "long list"...

**Comment by pganssle** [comment] 2019-10-04 17:43
I'm going to close this as essentially a duplicate of #1700.

**Closed by pganssle** 2019-10-04 17:43 UTC

**Comment by warsaw** [comment] 2019-10-04 17:45
Thanks @pganssle - that sounds like exactly the right solution.
