### ISSUE TITLE
[BUG] msvc.EnvironmentInfo.return_env fails because VCRuntimeRedist is None in GitHub action

### ISSUE THREAD

**Issue by jfolz** [pypa/setuptools#4627] opened 2024-09-03 09:48 UTC
### setuptools version

setuptools==74.1.0

### Python version

3.9

### OS

windows-latest

### Additional environment information

Environment is GitHub action using the [windows-latest](https://github.com/actions/runner-images) image.

### Description

One of my packages that needs to compile external dependencies is "outdated" (#4620), so I'm trying to port it to current setuptools. Of course on Windows, this mean I need to set up the env correctly to make MSVC happy. I'm currently stuck on `EnvironmentInfo.return_env` which fails with this trace:
```
Traceback (most recent call last):
  File "D:\a\setuptools-msvc-test\setuptools-msvc-test\test.py", line 6, in <module>
    env = EnvironmentInfo(ARCH).return_env()
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\setuptools\msvc.py", line 1472, in return_env
    if self.vs_ver >= 14 and isfile(self.VCRuntimeRedist):
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

Note that this might have been first reported in #1902.

If this is not the intended use case for `EnvironmentInfo`, I would ask that setuptools kindly provide guidance for how to migrate "outdated" packages.

### Expected behavior

`EnvironmentInfo.return_env` can be used to set up the env for MSVC.

### How to Reproduce

Test code:
```Python
import platform
from setuptools.msvc import EnvironmentInfo

ARCH = platform.machine()
print(f'Setting up environment for MSVC on {ARCH}')
env = EnvironmentInfo(ARCH).return_env()
for key, value in env.items():
    print(f'{key}="{value}"')
```

I created a [minimal repo](https://github.com/jfolz/setuptools-msvc-test) to reproduce the error.

### Output

```console
Run python test.py
Setting up environment for MSVC on AMD64
Traceback (most recent call last):
  File "D:\a\setuptools-msvc-test\setuptools-msvc-test\test.py", line 6, in <module>
    env = EnvironmentInfo(ARCH).return_env()
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\setuptools\msvc.py", line 1472, in return_env
    if self.vs_ver >= 14 and isfile(self.VCRuntimeRedist):
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Error: Process completed with exit code 1.
```

**Comment by jaraco** [comment] 2024-09-03 11:49
After reviewing, I agree it's probably a duplicate of #1902. I'll follow up there.

**Closed** 2024-09-03 11:49 UTC
Labels: bug, Needs Triage
