### ISSUE TITLE
[BUG] Cannot import torch when installation torch extension packages

### ISSUE THREAD

**Issue by ghostplant** [pypa/setuptools#4222] opened 2024-02-16 14:44 UTC
### setuptools version

setuptools==69.1.0

### Python version

Python 3.12.2

### OS

Windows

### Additional environment information

This is only happening in "Python 3.12.2 + Windows + setuptools==69.1.0"

### Description

```sh
python3 -m pip install --verbose --upgrade git+https://github.com/microsoft/tutel@main
```

My testing in different environment:

  Python 3.12.0 + Windows + setuptools==69.1.0:  Installation Passed ✓

  Python 3.12.2 + Windows + setuptools==69.1.0:  Installation Failed: × **ModuleNotFoundError: No module named 'torch'** (I ensure I have installed torch package for Python3.12.2)

  Python 3.12.0 + Ubuntu + setuptools==69.1.0:  Installation Passed ✓

  Python 3.8.6 + Ubuntu + setuptools==69.1.0:  Installation Passed ✓

Under Linux, I don't find any issues using any versions of Pytorch.

### Expected behavior

Python 3.12.2 + Windows + setuptools==69.1.0 should work normally like other platforms and python versions.

### How to Reproduce

Under Windows + Python3.12.2 + Torch:<any>:
```
python3 -m pip install --verbose --upgrade git+https://github.com/microsoft/tutel@main
```
Above command should detect and import package correctly.

### Output

This is the error output using Python3.12.2:
```console
  Running command Getting requirements to build wheel
  Traceback (most recent call last):
    File "C:\Users\develop\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\develop\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\develop\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\develop\AppData\Local\Temp\pip-build-env-ijd5_0va\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\develop\AppData\Local\Temp\pip-build-env-ijd5_0va\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "C:\Users\develop\AppData\Local\Temp\pip-build-env-ijd5_0va\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
      super().run_setup(setup_script=setup_script)
    File "C:\Users\develop\AppData\Local\Temp\pip-build-env-ijd5_0va\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 19, in <module>
  ModuleNotFoundError: No module named 'torch'
  error: subprocess-exited-with-error
```

**Comment by abravalheri** [comment] 2024-02-16 18:59
Hi @ghostplant, by the looks of the logs it seems that the `setup.py` script is trying to import the `torch` package during the build, but it is not installed in the virtual environment[^1] where the build process is running.

There might be a plethora of reasons for the fact it works in some environment combinations and not in others.

The most likely is that `https://github.com/microsoft/tutel` does not have a `pyproject.toml` and does not list `torch` as part of the `requires` field in the `[build-system]` table.

Also note that because the absence of `pyproject.toml`, `pip` will use its internal heuristics to choose whether or not to rely on [build isolation](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#build-isolation). In turn, these heuristics depend on the state of the virtual environment[^1], and therefore might seem inconsistent between different attempts.

Other combinations of OSs/Python versions might be working because `torch` is installed there, and/or because of transitive conditional dependencies on that package, and/or a different choice made by `pip` whether or not the build isolation feature is used.

See [docs on Basic Usage](https://setuptools.pypa.io/en/latest/userguide/quickstart.html#basic-use) for an example of `pyproject.toml` and where to list build-time dependencies.
Alternatively, if you want to disable "build isolaiton" you can run `pip install` with the `--no-build-isolation` and/or `--no-pep517` flags (if you do that you need to ensure all the build dependencies are installed).

I do recommend having a `pyproject.toml` though, as it improves reproducibility and make things more deterministic.

[^1]: Or "global Python environment" related to the installation that is being used.

**Comment by ghostplant** [comment] 2024-02-17 08:43
Thanks, I add that configuration in this branch: https://github.com/ghostplant/tutel/blob/main/pyproject.toml

However, I didn't get any luck by installing with: `python3 -m pip install --verbose --upgrade git+https://github.com/ghostplant/tutel@main`

A worse thing is that, that file makes all other platforms failed to import torch package as well.

**Comment by ghostplant** [comment] 2024-02-17 09:38
Other options also don't work:
```sh
$ pip install --verbose --upgrade --no-build-isolation git+https://github.com/microsoft/tutel@main

  ...
  Resolved https://github.com/microsoft/tutel to commit b440e018c347205d3292a7c1e7947981e8fe46ad
  Running command git rev-parse HEAD
  b440e018c347205d3292a7c1e7947981e8fe46ad
  Running command Preparing metadata (pyproject.toml)
  running dist_info
  creating C:\Users\devel\AppData\Local\Temp\pip-modern-metadata-fb2ve584\tutel.egg-info
  writing C:\Users\devel\AppData\Local\Temp\pip-modern-metadata-fb2ve584\tutel.egg-info\PKG-INFO
  writing dependency_links to C:\Users\devel\AppData\Local\Temp\pip-modern-metadata-fb2ve584\tutel.egg-info\dependency_links.txt
  writing requirements to C:\Users\devel\AppData\Local\Temp\pip-modern-metadata-fb2ve584\tutel.egg-info\requires.txt
  writing top-level names to C:\Users\devel\AppData\Local\Temp\pip-modern-metadata-fb2ve584\tutel.egg-info\top_level.txt
  writing manifest file 'C:\Users\devel\AppData\Local\Temp\pip-modern-metadata-fb2ve584\tutel.egg-info\SOURCES.txt'
  C:\Users\devel\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\cpp_extension.py:500: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
    warnings.warn(msg.format('we could not find ninja.'))
  reading manifest file 'C:\Users\devel\AppData\Local\Temp\pip-modern-metadata-fb2ve584\tutel.egg-info\SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file 'C:\Users\devel\AppData\Local\Temp\pip-modern-metadata-fb2ve584\tutel.egg-info\SOURCES.txt'
  creating 'C:\Users\devel\AppData\Local\Temp\pip-modern-metadata-fb2ve584\tutel-0.3.dist-info'
  Try installing without NCCL extension..
  running dist_info
  writing C:\Users\devel\AppData\Local\Temp\pip-modern-metadata-fb2ve584\tutel.egg-info\PKG-INFO
  writing dependency_links to C:\Users\devel\AppData\Local\Temp\pip-modern-metadata-fb2ve584\tutel.egg-info\dependency_links.txt
  writing requirements to C:\Users\devel\AppData\Local\Temp\pip-modern-metadata-fb2ve584\tutel.egg-info\requires.txt
  writing top-level names to C:\Users\devel\AppData\Local\Temp\pip-modern-metadata-fb2ve584\tutel.egg-info\top_level.txt
  reading manifest file 'C:\Users\devel\AppData\Local\Temp\pip-modern-metadata-fb2ve584\tutel.egg-info\SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file 'C:\Users\devel\AppData\Local\Temp\pip-modern-metadata-fb2ve584\tutel.egg-info\SOURCES.txt'
  creating 'C:\Users\devel\AppData\Local\Temp\pip-modern-metadata-fb2ve584\tutel-0.3.dist-info'
  Try installing without CUDA extension..
  running dist_info
  writing C:\Users\devel\AppData\Local\Temp\pip-modern-metadata-fb2ve584\tutel.egg-info\PKG-INFO
  writing dependency_links to C:\Users\devel\AppData\Local\Temp\pip-modern-metadata-fb2ve584\tutel.egg-info\dependency_links.txt
  writing requirements to C:\Users\devel\AppData\Local\Temp\pip-modern-metadata-fb2ve584\tutel.egg-info\requires.txt
  writing top-level names to C:\Users\devel\AppData\Local\Temp\pip-modern-metadata-fb2ve584\tutel.egg-info\top_level.txt
  reading manifest file 'C:\Users\devel\AppData\Local\Temp\pip-modern-metadata-fb2ve584\tutel.egg-info\SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file 'C:\Users\devel\AppData\Local\Temp\pip-modern-metadata-fb2ve584\tutel.egg-info\SOURCES.txt'
  creating 'C:\Users\devel\AppData\Local\Temp\pip-modern-metadata-fb2ve584\tutel-0.3.dist-info'
  error: invalid command 'bdist_wheel'
  error: subprocess-exited-with-error
```

```sh
$ pip install --verbose --upgrade --no-use-pep517 git+https://github.com/microsoft/tutel@main

  ...

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

--no-use-pep517 error: It is not possible to use --no-use-pep517
without setuptools and wheel installed.
```

I have to unzip the online files to local, and manually run `setup.py`:
```sh
$ git clone https://github.com/microsoft/tutel
$ cd tutel && ./setup.py
  ...
  creating c:\Users\devel\appdata\local\programs\python\python312\lib\site-packages\tutel-0.3-py3.12-win-amd64.egg
  Extracting tutel-0.3-py3.12-win-amd64.egg to c:\Users\devel\appdata\local\programs\python\python312\lib\site-packages
  Adding tutel 0.3 to easy-install.pth file
  detected new path './tutel-0.3-py3.12-win-amd64.egg'

  Installed c:\Users\devel\appdata\local\programs\python\python312\lib\site-packages\tutel-0.3-py3.12-win-amd64.egg
  Processing dependencies for tutel==0.3
  Searching for numpy==1.26.4
  Best match: numpy 1.26.4
  Adding numpy 1.26.4 to easy-install.pth file
  Installing f2py-script.py script to C:\Users\devel\AppData\Local\Programs\Python\Python312\Scripts
  Installing f2py.exe script to C:\Users\devel\AppData\Local\Programs\Python\Python312\Scripts

  Using c:\Users\devel\appdata\local\programs\python\python312\lib\site-packages
  Finished processing dependencies for tutel==0.3
```

Looks like online/zipped-file installation is problematic in `Win11 + Py3.12.2`, since running setup.py is always working, even without `pyproject.toml` configured.

In other platforms like Linux, I don't see any differences between online/zipped-file installation and running `./setup.py` manually.

**Comment by ghostplant** [comment] 2024-02-17 09:57
Is it possible to fix `--no-build-isolation` error above and keep it as the same behavior as running local `./setup.py`?

I think configure "torch" dependencies in `pyproject.toml` isn't a good choice in my case, since torch is a huge package with diverse dependencies from special extra index URL. It is not only expensive to download and install in a fresh isolated sandbox, on the other hand, it is also not likely possible for Tutel (or any other Torch applications) to detect which version, backend-type and index-URL that local torch was ever installed with, so it may result in a wrong torch installed and thus introducing other CXX_ABI errors or backend-mismatch errors.

**Comment by abravalheri** [comment] 2024-02-19 02:07
> Thanks, I tried adding that configuration in this branch: https://github.com/ghostplant/tutel/blob/main/pyproject.toml
> 
> However, I didn't get any luck by installing with:
> ```py
> python3 -m pip install --verbose --upgrade git+https://github.com/ghostplant/tutel@main
> ```
> 
> A worse thing is that, that file makes all other platforms failed to import torch package as well.

I think you ended up adding the `[project]` table (which is not necessary) instead of the `[build-system]` which allows you to list all the build dependencies. Please have  a look on https://setuptools.pypa.io/en/latest/userguide/quickstart.html#basic-use and don't forget to add all the build-time dependencies to the `requires` field. I actually recommend completely removing the `[project]` table for now, because that is a completely different topic.

**Comment by abravalheri** [comment] 2024-02-19 02:09
> Other options also don't work:
> $ pip install --verbose --upgrade --no-build-isolation git+https://github.com/microsoft/tutel@main

Please note that if you do that you need to install **all** build dependencies. I have prévios mentioned that

> Alternatively, if you want to disable "build isolation" you can run pip install with the --no-build-isolation and/or --no-use-pep517 flags (if you do that you need to ensure all the build dependencies are installed, including `setuptools` and `wheel`).

By the looks of the logs, it seems like `wheel` was not installed.

**Comment by abravalheri** [comment] 2024-02-19 02:14
> Is it possible to fix `--no-build-isolation` error above and keep it as the same behavior as running local `./setup.py`? Supporting `isolation_safe=False` instead of an explicit `--no-build-isolation` option would be even greater.
> 
> I think configure "torch" dependencies in `pyproject.toml` isn't a good choice in my case, since torch is a huge package with diverse dependencies (e.g. nvidia-ptx/..) from special extra index URL. It is not only expensive to download and install a new torch package in a fresh isolated sandbox, it is also not likely possible for Tutel (or any other Torch applications) to **smartly detect which index-URL that local torch was ever installed with**, so it may result in installing a wrong torch target in the sandbox and further introducing other CXX_ABI errors or backend-mismatch errors.

I am afraid that is not up to `setuptools`. The installation process is handled by `pip` and they have their own way of deciding when "buil isolation" will be triggered.As far as I know, the way to achieve consistency is by installing all the build dependencies manually and then explicitly passing the flag.

**Comment by ghostplant** [comment] 2024-02-19 06:07
> > Other options also don't work:
> > $ pip install --verbose --upgrade --no-build-isolation git+https://github.com/microsoft/tutel@main
> 
> Please note that if you do that you need to install **all** build dependencies. I have previuosly mentioned:
> 
> > Alternatively, if you want to disable "build isolation" you can run pip install with the --no-build-isolation and/or --no-use-pep517 flags (if you do that you need to ensure all the build dependencies are installed, including `setuptools` and `wheel`).
> 
> By the looks of the logs, it seems like `wheel` was not installed.

That works! It indeed solves the online installation problem after `pip install wheel`. However, I think the error message `error: invalid command 'bdist_wheel'` is very confusing. If reporting `Exception ModuleNotFound: wheel` instead, it would be much clearer for user ensure wheel package before reinstalling user package again.

**Comment by ghostplant** [comment] 2024-02-19 06:22
BTW, after installing wheel package in advance, I don't even need to set `--no-build-isolation` to install user packages, which is great. One more question: in order to avoid other environment/users to get into the same trouble, if it possible to set pre-dependency keys in `setup.py` to ensure pip to install wheel package first and then continuing user package installation. `pyproject.toml` is a great thing to set pre-dependency in an isolated environment, but how about pre-dependency for non-isolated environment?

**Comment by abravalheri** [comment] 2024-02-19 14:09
> If reporting `Exception ModuleNotFound: wheel` instead, it would be much clearer for user ensure wheel package before reinstalling user package again.

Setuptools does not know exactly which package is providing the `bdist_wheel` command either to be honest. It uses [`entry-points` and discovery](https://setuptools.pypa.io/en/latest/userguide/entry_point.html) to decouple the implementation of the commands. `wheel` provides a reference implementation for `bdist_wheel`, but many projects do customise that.


> BTW, after installing wheel package in advance, I don't even need to set `--no-build-isolation` to install user packages, which is great.

Please be mindful however that this behaviour depends on the internal heuristics used by `pip` to decide whether to trigger build isolation[^1]. I am not sure how stable are these heuristics and how often they are planned to change. I don't think `pip` make any promises on that front either. To be fully in control of what is happening and improve reproducibility, I would recommend being explicit with the flags.

[^1]: We can see that one of the parameters used by `pip` is the presence of `wheel` installed in the (virtual) environment.


> in order to avoid other environment/users to get into the same trouble, if it possible to set pre-dependency keys in `setup.py` to ensure pip to install wheel package first and then continuing user package installation.

As far as I know there is no API implemented in `pip` that allows `setuptools` to tell which packages to pre-install in the case of "no-isolation"[^2]. By the time that `setup.py` runs it is too late: the imports are already parsed and trigger import errors. If "no-isolation" is needed, the only means I know to minimise errors is to document all the steps in the "Installation" section of your package description.

[^2]: The `pyproject.toml` and related APIs are only defined for the "isolation" use case. When using "isolation", `setuptools` uses the [build APIs](https://peps.python.org/pep-0517/) to tell `pip` to pre-install `wheel`, but nothing similar exist for "no-isolation"

**Comment by ghostplant** [comment] 2024-02-19 17:06
OK, the online setup has now been changed to multiple stages like this, which runs much more stable on all platforms I have tested:
```sh
Line-1:      $ python3 -m pip install setuptools wheel
Line-2:      $ python3 -m pip install -v -U --no-build-isolation git+https://github.com/microsoft/tutel@main
```

Since it is late for setuptools to analyze build-time dependencies, while most users may still easily forget running `Line-1` above, I plan to add some check in `setupy.py` to check whether it is already in an isolated environment, if so, I need to stop further installation and print useful errors that is not ambiguous like `torch is not found`.

```py
import setuptools
..

if <I-am-in-an-isolated-environment>:
  raise Exception('Please install wheel and setuptools..')

# Run original scripts
setup(
 ..
)
```

Is it convient to do `<I-am-in-an-isolated-environment>` decently?

**Comment by abravalheri** [comment] 2024-02-19 18:15
Hi @ghostplant, it might be useful to also suggest pre-installing `torch` in `Line-1`, because it is also a build dependency, isn't it? (It is imported in `setup.py`, so if the user does not have it installed, `Line-2` will fail with an exception).

Regarding the check you mentioned:
1. I don't know a way to check specifically for `<I-am-in-an-isolated-environment>`...
   You might try to check for the presence of `torch` or `wheel`. That might be easy to achieve.
2. If the (virtual) environment does not contain `setuptools` installed, the exception will happen when `import setuptools` run.

It might be worth to keep `torch` in `[build-system] requires` anyway, because I guess some users will still oversee the installation instructions and simply attempt to run the install command without the `--no-build-isolation`. While that is sub-optimal and will take longer, at least they get something...

   ```diff
    [build-system]
   +requires = ["setuptools", "wheel", "torch"]
   -requires = ["setuptools", "wheel"]
    build-backend = "setuptools.build_meta"
   ```

**Comment by ghostplant** [comment] 2024-02-20 01:59
> , because I guess some users will still oversee the installation instructions and simply attempt to run the install command without

Thanks for the suggestion. I have tried adding `pyproject.toml` that but seems like it damages most platform's default installation, because that file makes pip always thinking of creating an isolated environment, and thus triggers to download a new torch from PyPi repo instead of Torch's official repo, which eventually produces pyDLL with an improper ABI and backend setting which is not able to be imported successfully by the Pytorch installed at host site.

**Comment by abravalheri** [comment] 2024-02-21 10:26
Ah, I see: there is also a `pip` x `conda` background to this issue.

Yeah that makes sense. I suppose that in this use case it is better to focus on the way `conda` distributes packages and/or custom detailed installation instructions instead of trying to follow the recommendations we would normally give for a `pip`-centric process.


I will go ahead and close this issue for now: it seems to me that all the details we have discussed so far are related to how the build environment is set, which happens before `setuptools` itself is even imported in the first place.

The setting up of the build environment in a modern `pip`-centric installation process is the responsibility of what we call `build-frontend` (e.g. `pip` or [`build`](https://github.com/pypa/build)), but `setuptools` is a `build-backend`. In the last half-decade PyPA's tools have improved a lot for isolated builds, and in general it is a good idea to use isolation. I understand that there are use cases (e.g. very large dependencies and/or integration with `conda`) that are probably better if treated differently and the tool chain has not matured enough for that. But this is probably something that has to be discussed in a broader context via https://discuss.python.org/c/packaging/14, since this is not part of the scope of `setuptools` itself.

**Closed by abravalheri** 2024-02-21 10:26 UTC
Labels: bug, Needs Triage

**Comment by ghostplant** [comment] 2024-02-21 14:24
Thanks. Windows is more common to see this issue since a fresh Python installation usually excludes `setuptools` and `wheel` which make pip force to decide isolation.
