### ISSUE TITLE
No module named 'six'

### ISSUE THREAD

**Issue by davidism** [pypa/setuptools#1042] opened 2017-06-01 01:18 UTC
Flask's Tox/Travis builds all started failing. Looks like a new version of setuptools was just released that has a problem with six.

~~~pytb
Obtaining file:///home/david/Projects/flask
Installing collected packages: Flask
  Running setup.py develop for Flask
    Complete output from command /home/david/Projects/flask/.tox/py/bin/python3 -c "import setuptools, tokenize;__file__='/home/david/Projects/flask/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    /home/david/Projects/flask/.tox/py/lib/python3.6/site-packages/setuptools/dist.py:336: UserWarning: Normalizing '0.13-dev' to '0.13.dev0'
      normalized_version,
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/david/Projects/flask/setup.py", line 109, in <module>
        '''
      File "/usr/lib64/python3.6/distutils/core.py", line 134, in setup
        ok = dist.parse_command_line()
      File "/home/david/Projects/flask/.tox/py/lib/python3.6/site-packages/setuptools/dist.py", line 363, in parse_command_line
        result = _Distribution.parse_command_line(self)
      File "/usr/lib64/python3.6/distutils/dist.py", line 472, in parse_command_line
        args = self._parse_command_opts(parser, args)
      File "/home/david/Projects/flask/.tox/py/lib/python3.6/site-packages/setuptools/dist.py", line 674, in _parse_command_opts
        nargs = _Distribution._parse_command_opts(self, parser, args)
      File "/usr/lib64/python3.6/distutils/dist.py", line 528, in _parse_command_opts
        cmd_class = self.get_command_class(command)
      File "/home/david/Projects/flask/.tox/py/lib/python3.6/site-packages/setuptools/dist.py", line 495, in get_command_class
        self.cmdclass[command] = cmdclass = ep.load()
      File "/home/david/Projects/flask/.tox/py/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2303, in load
        return self.resolve()
      File "/home/david/Projects/flask/.tox/py/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2309, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/home/david/Projects/flask/.tox/py/lib/python3.6/site-packages/setuptools/command/develop.py", line 11, in <module>
        from setuptools.command.easy_install import easy_install
      File "/home/david/Projects/flask/.tox/py/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 49, in <module>
        from setuptools.py27compat import rmtree_safe
      File "/home/david/Projects/flask/.tox/py/lib/python3.6/site-packages/setuptools/py27compat.py", line 7, in <module>
        import six
    ModuleNotFoundError: No module named 'six'
~~~

Example failed build log: https://travis-ci.org/pallets/flask/jobs/238166427#L242

**Comment by thanatos** [comment] 2017-06-01 01:22
I am seeing [a very similar traceback](https://gist.github.com/thanatos/7daa078f02a84de106d0183fbe6ea54e)

**Comment by davidism** [comment] 2017-06-01 01:23
This doesn't happen if I manually create a virtualenv. In that case, setuptools=36.0.0 is installed and installing packages works fine.

**Comment by dstufft** [comment] 2017-06-01 01:24
It looks like an import got missed for being rewritten to import from the vendored packages.

**Comment by dmsimard** [comment] 2017-06-01 02:39
Thanks for identifying the issue quickly.

This is currently plaguing most of our python-based jobs, would appreciate a release ASAP once the pull request https://github.com/pypa/setuptools/pull/1043 lands.

**Comment by elliterate** [comment] 2017-06-01 03:19
I was able to temporarily work around this, first, by upgrading my CI environment to just short of v36 with the following pre-install command:

    pip install --upgrade "setuptools < 36"

Then, by ensuring that my soon-to-be-created virtualenv inherited that version with the following environment variable:

    VIRTUALENV_NO_DOWNLOAD=1

**Comment by cumber** [comment] 2017-06-01 03:26
I was able to work around this by manually running `pip install six` in my new virtualenv, before installing anything else. It was able to reuse a cached wheel for `six` though; not certain that it would have worked otherwise.

**Comment by badone** [comment] 2017-06-01 03:34
A quick fix would be nice. This is affecting our builds as well.

**Comment by silvana-i** [comment] 2017-06-01 05:07
Adding one more report for this issue. We are using virtualenv, which installs the faulty setuptools version. Afterwards when installing our project dependencies with `pip install -r requirements.txt` it is choking on the download of a custom package from a locally hosted pypi server. It fails during package collection, so the only thing that we found to fix it is to call `pip install six` before installing the requirements.txt.

**Comment by asottile** [comment] 2017-06-01 05:23
For what it's worth, I made a `tox` plugin to avoid `virtualenv`'s download behaviour [for exactly this reason](https://github.com/asottile/tox-virtualenv-no-download#wait-why)

Simply `pip install tox-virtualenv-no-download` alongside `tox`

**Comment by escapewindow** [comment] 2017-06-01 05:26
`virtualenv --no-download PATH` will probably work for `virtualenv>=14.0.0`; that'll prevent hitting pypi for the new setuptools when creating the virtualenv.
https://virtualenv.pypa.io/en/stable/changes/

**Comment by fengxx** [comment] 2017-06-01 06:02
can we have a emergency release for the bugfix?

**Comment by fake-name** [comment] 2017-06-01 06:31
It appears you can work around the issue by manually installing six before the dependencies that require it.

**Comment by fengxx** [comment] 2017-06-01 06:35
there is a workaround like VIRTUALENV_NO_DOWNLOAD=1  but the issue will cause trouble for virtualenv user who doesn't know the workaround.

**Comment by dstufft** [comment] 2017-06-01 11:03
It was pointed out to me that at some point I had been added as a maintainer to setuptools on PyPI, I wasn't aware of that (or had forgotten if I was aware). I've gone ahead and deleted 36.0 from PyPI.

@jaraco I downloaded the files to my computer, if you want to restore 36.0 let me know and I can do it.

**Comment by hrw** [comment] 2017-06-01 11:07
@dstufft can you merge pull request with fix and release 36.0.1?

**Comment by dstufft** [comment] 2017-06-01 11:12
Jason is the only member of the @pypa/setuptools-developers team, so while I have the *technical* capability of merging a PR due to being an admin of the PyPA org on Github, I was not explicitly made a committer of the repository and I don't feel comfortable merging that change. Additionally I don't really know the normal release process of setuptools, so I wouldn't feel comfortable cutting a release (and possibly screwing it up again).

Ultimately, the bleeding is stopped and this can wait for @jaraco now.

**Comment by kulapard** [comment] 2017-06-01 11:20
Fixed without importing six #1046

**Comment by graingert** [comment] 2017-06-01 11:22
Smallest passing build #1047

**Comment by ilovezfs** [comment] 2017-06-01 11:38
Fix confirmed here as well: https://github.com/Homebrew/homebrew-core/pull/14130.

**Comment by pabelanger** [comment] 2017-06-01 12:01
@dstufft If possible, please do not delete packages that have already been tagged and released to pypi. This puts local mirrors in an awkward position of now having an unreleased packaging mirrored.
I know you are not the maintainer but it would have been better to tag 37.0.0 reverting 36.0.0 to 35.x.x

**Comment by graingert** [comment] 2017-06-01 12:04
>  I know you are not the maintainer but it would have been better to tag 37.0.0 reverting 36.0.0 to 35.x.x

that will probably happen soon. Deleting 36 was the fastest way to get travis working again.

**Comment by pabelanger** [comment] 2017-06-01 12:08
While it was the fastest way to get TravisCI working again, it breaks other CI systems in the process. It is never possible to delete something from the internet, there will always be a cache somewhere.

**Comment by Natim** [comment] 2017-06-01 12:28
It won't be possible to upload them again actually...

**Comment by andreibacos** [comment] 2017-06-01 12:33
As someone in the process of removing 36 from our internal devpi caches, @pabelanger made a good point.

**Comment by Natim** [comment] 2017-06-01 12:35
> I don't really know the normal release process of setuptools, so I wouldn't feel comfortable cutting a release

The release process is [documented here](https://setuptools.readthedocs.io/en/latest/releases.html)

I don't think relying on a single person to fix a so central Python package is a good thing. It puts a lot of pressure on their shoulder while we could handle it on our side.

I wouldn't consider it to be a bleeding, its part of the life of a project to ship broken releases once in a while.

The release process of a python project is to release a new version to fix a release.

I would be glad to cut a release myself if you give me necessary permissions.

**Comment by matthew-brett** [comment] 2017-06-01 12:43
@Natim - see #1045 for a request to add release candidate builds to the release process.

**Comment by Natim** [comment] 2017-06-01 12:46
Yes that's probably a good idea too. Thanks @matthew-brett

**Closed** 2017-06-01 12:52 UTC

**Comment by jaraco** [comment] 2017-06-01 13:15
Please see [this comment](https://github.com/pypa/setuptools/pull/1043#issuecomment-305485240) regarding my apology and intention for the project maintenance.

**Comment by meloChap** [comment] 2024-04-24 03:45
> pip install six

If the display shows that Six already exists, it should be that the location of this file has been moved
