### ISSUE TITLE
[BUG] ensure_local_distutils is failing when pip is imported before setuptools

### ISSUE THREAD

**Issue by mgorny** [pypa/setuptools#3044] opened 2022-01-22 21:24 UTC
### setuptools version

af875d6573c90c5df4a32f948dc65598c58dbf2b

### Python version

CPython 3.10.2

### OS

Gentoo Linux

### Description

When `pip` is imported before `setuptools`, the `ensure_local_distutils` assertion fails.

### Expected behavior

No failing assertions ;-).

### How to Reproduce

```
pip install pip setuptools
python -c 'import pip; import setuptools'
```

### Output

```pytb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/setuptools/setuptools/__init__.py", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
  File "/tmp/setuptools/.venv/lib/python3.10/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "/tmp/setuptools/.venv/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 71, in do_override
    ensure_local_distutils()
  File "/tmp/setuptools/.venv/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 59, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: /usr/lib/python3.10/distutils/core.py
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jaraco** [comment] 2022-01-29 19:28
Thanks for the report.

This behavior is by design, albeit a somewhat cobbled, reactive design.

The `_distutils_hack` aims to make the local copy of distutils the default, causing `import distutils` to bring in the local copy. However, doing so when running pip breaks pip's assumptions about how distutils works (pypa/pip#8761). Until pip can drop its reliance on distutils or add support for using distutils as found in Setuptools, this issue is likely to persist.

One option available is the escape hatch. Set `SETUPTOOLS_USE_DISTUTILS=stdlib` will allow Setuptools to fall back to the old behavior.

Another workaround could be not to `import pip`, which explicitly declares that the recommended way to use pip is through it's command interface.

I'm open to other ideas, but I'm unaware of a path to achieve the reporter's preferred expectation.

For that reason, I'm closing this issue as wontfix, but I welcome further discussion and can re-open if appropriate.

Thanks for your understanding.

**Closed by jaraco** 2022-01-29 19:28 UTC
Labels: wontfix
