### ISSUE TITLE
Python bytecode compiled with optimization (--optimize=1) but console_scripts entry points are run non-optimized

### ISSUE THREAD

**Issue by igo95862** [pypa/setuptools#2008] opened 2020-02-27 10:22 UTC
python setup.py install --optimize=1

allows you to compile python optimized files. 

However, the console scripts installed will use non-optimized byte code. 

One easy fix is to modify [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) when optimize flag is passed to setup.py

Before:
#!/usr/bin/python
After:
#!/usr/bin/python -O

**Comment by ebarg666** [comment] 2020-02-29 13:35
#@`
Duplicate of #`

**Comment by juhannc** [comment] 2022-10-20 14:17
Is there any progress on this issue? I think a feature to run console scripts in optimized mode (aka with at least `__debug__ = False`) would be very interesting

**Comment by abravalheri** [comment] 2022-10-20 15:25
When you install a package with `pip install`, `pip` is the tool creating the CLI wrappers (using `distlib`). Setuptools is no longer involved in this process (`python setup.py install`) is considered deprecated.

**Comment by abravalheri** [comment] 2022-10-20 15:28
Given that `python setup.py install` is considered deprecated and that the recommended replacement is `pip install`, I believe that the best action is to close this issue.

I can see in [`pip` docs]() that `pip` offers a `--compile` flag. Maybe it is worth exploring that option.

**Closed by abravalheri** 2022-10-20 15:28 UTC
