### ISSUE TITLE
v45 is still set to build a universal wheel, but doesn't support Python 2

### ISSUE THREAD

**Issue by bennuttall** [pypa/setuptools#1976] opened 2020-01-19 12:03 UTC
If you run

```
pip3 wheel setuptools --no-binary :all:
```

this yields the file `setuptools-45.0.0-py2.py3-none-any.whl`

but if you try to use it with Python 2, it fails with the error

```
setuptools requires Python '>=3.5' but the running Python is 2.7.17
```

This arose in my [piwheels](https://www.piwheels.org/) project. We build wheels of everything on PyPI on Raspberry Pi hardware. Some users have reported their Python 2 projects suffering for this. See https://github.com/piwheels/packages/issues/74. We don't build for Python 2 (we never have) and generally, pure Python wheels get built with a `py3` Python version tag. Only when a project specifies "universal" in their setup do we end up with a `py2.py3` tag.

Example: if I have `/etc/pip.conf` configured to use piwheels.org as an additional index, then trying to create a Python 2 virtualenv fails:

```bash
ben@gunter:~ $ cat /etc/pip.conf 
[global]
extra-index-url=https://www.piwheels.org/simple
ben@gunter:~ $ mkvirtualenv py2
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/ben/.virtualenvs/py2/bin/python2
Also creating executable in /home/ben/.virtualenvs/py2/bin/python
Installing setuptools, pkg_resources, pip, wheel...
  Complete output from command /home/ben/.virtualenvs/py2/bin/python2 - setuptools pkg_resources pip wheel:
  Collecting setuptools
  Downloading https://www.piwheels.org/simple/setuptools/setuptools-45.0.0-py2.py3-none-any.whl (583kB)
setuptools requires Python '>=3.5' but the running Python is 2.7.17
----------------------------------------
...Installing setuptools, pkg_resources, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2375, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 724, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 992, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 922, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 817, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/ben/.virtualenvs/py2/bin/python2 - setuptools pkg_resources pip wheel failed with error code 1
```

setuptools still has `universal = 1` in [`setup.cfg`](https://github.com/pypa/setuptools/blob/master/setup.cfg)

I guess this should either be set to `0` or that section removed. I'll open a PR.

**Comment by jaraco** [comment] 2020-01-19 15:33
I believe this is a dupe of #1974.

**Closed by jaraco** 2020-01-19 15:33 UTC

**Comment by pganssle** [comment] 2020-01-19 19:17
@bennuttall Thanks for your PRs, but you should probably be aware that this is only a temporary workaround for your problem. The bigger issue is that piwheels.org does not expose the `data-requires-python` attribute as specified in [PEP 503](https://www.python.org/dev/peps/pep-0503/). Even if you only ever support Python 2, it will cause problems as packages drop support for Python 3.4, 3.5, 3.6, etc at different times.

Shipping a `.py3` wheel instead of a `py2.py3` wheel is an expedient workaround today, but it only papers over the deeper problem.

**Comment by bennuttall** [comment] 2020-01-19 19:39
Thanks @pganssle I'll open an issue on piwheels
