### ISSUE TITLE
python setup.py bdist_rpm problem!

### ISSUE THREAD

**Issue by denefer** [pypa/setuptools#1846] opened 2019-09-11 08:44 UTC
hi:
  when i use command 'python setup.py bdist_rpm' to build rpm package from setuptools-41.2.0 
the error as below:
```
removing /tmp/tmp_U6BNz.py
running install_egg_info
running egg_info
writing requirements to setuptools.egg-info/requires.txt
writing setuptools.egg-info/PKG-INFO
writing top-level names to setuptools.egg-info/top_level.txt
writing dependency_links to setuptools.egg-info/dependency_links.txt
writing entry points to setuptools.egg-info/entry_points.txt
reading manifest file 'setuptools.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching 'pyproject.toml'
writing manifest file 'setuptools.egg-info/SOURCES.txt'
Copying setuptools.egg-info to /home/zhou/rpmbuild/SOURCES/supervisor/setuptools-41.2.0/build/bdist.linux-x86_64/rpm/BUILDROOT/setuptools-41.2.0.post20190911-1.x86_64/usr/lib/python2.7/site-packages/setuptools-41.2.0.post20190911-py2.7.egg-info
running install_scripts
Installing easy_install script to /home/zhou/rpmbuild/SOURCES/supervisor/setuptools-41.2.0/build/bdist.linux-x86_64/rpm/BUILDROOT/setuptools-41.2.0.post20190911-1.x86_64/usr/bin
Installing easy_install-2.7 script to /home/zhou/rpmbuild/SOURCES/supervisor/setuptools-41.2.0/build/bdist.linux-x86_64/rpm/BUILDROOT/setuptools-41.2.0.post20190911-1.x86_64/usr/bin
writing list of installed files to 'INSTALLED_FILES'
+ /usr/lib/rpm/find-debuginfo.sh --strict-build-id -m --run-dwz --dwz-low-mem-die-limit 10000000 --dwz-max-die-limit 110000000 /home/zhou/rpmbuild/SOURCES/supervisor/setuptools-41.2.0/build/bdist.linux-x86_64/rpm/BUILD/setuptools-41.2.0.post20190911
/usr/lib/rpm/sepdebugcrcfix: Updated 0 CRC32s, 0 CRC32s did match.
find: 'debug': No such file or directory
+ '[' noarch = noarch ']'
+ case "${QA_CHECK_RPATHS:-}" in
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-compress
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
Bytecompiling .py files below /home/zhou/rpmbuild/SOURCES/supervisor/setuptools-41.2.0/build/bdist.linux-x86_64/rpm/BUILDROOT/setuptools-41.2.0.post20190911-1.x86_64/usr/lib/python2.7 using /usr/bin/python2.7
+ /usr/lib/rpm/redhat/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-java-repack-jars
Processing files: setuptools-41.2.0.post20190911-1.noarch
error: File must begin with "/": (dev).tmpl
error: File must begin with "/": manifest.xml


RPM build errors:
    File must begin with "/": (dev).tmpl
    File must begin with "/": manifest.xml
error: command 'rpmbuild' failed with exit status 1
```

can anyone tell me how to fix that. thx!

**Comment by jaraco** [comment] 2019-10-27 13:15
It looks like the issue is that (apparently) `bdist_rpm` doesn't support filenames with spaces in them. I recommend digging into how rpms are built and determine where the shortcoming is that leads to this failure.

This is a duplicate of #767.

**Closed by jaraco** 2019-10-27 13:15 UTC
