### ISSUE TITLE
[BUG] PyQt5.sip module not found, when installing a module that made use of PyQt5 through setup.py script

### ISSUE THREAD

**Issue by Fcsalvagnini** [pypa/setuptools#2639] opened 2021-04-13 13:29 UTC
### setuptools version

52.0.0.post20210125

### Python version

Python 3.6.9

### OS

Ubuntu 20.04.2 LTS

### Additional environment information

I'm using a conda environment to try the instalation of my package in a fresh python.

I have created the conda environment using the following command:

```
conda create -n git_issu python=3.6.9
```

And then, I activate the environment and execute the setup.py script:

```
python setup.py install
```

### Description

I have created a python package and implemented a Graphical Interface for it, using PyQt5.

However, when I release it internally, some problems appeared.

When someone installs my package, either using the release `.whl` file or using the `setup.py` script, the `PyQt5` module is not correctly installed, and the following error is returned, when someone tries to start the graphical interface:

```
Traceback (most recent call last):
  File "/home/foo.bar/anaconda3/envs/git_issu/bin/pceb", line 33, in <module>
    sys.exit(load_entry_point('pceb==3.1.1', 'console_scripts', 'pceb')())
  File "/home/foo.bar/anaconda3/envs/git_issu/bin/pceb", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/foo.bar/anaconda3/envs/git_issu/lib/python3.6/site-packages/importlib_metadata-3.10.0-py3.6.egg/importlib_metadata/__init__.py", line 167, in load
    module = import_module(match.group('module'))
  File "/home/foo.bar/anaconda3/envs/git_issu/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/foo.bar/anaconda3/envs/git_issu/lib/python3.6/site-packages/pceb-3.1.1-py3.6.egg/pceb/main.py", line 13, in <module>
  File "/home/foo.bar/anaconda3/envs/git_issu/lib/python3.6/site-packages/pceb-3.1.1-py3.6.egg/pceb/interface/main_gui.py", line 2, in <module>
ModuleNotFoundError: No module named 'PyQt5.sip
```

After that, if you uninstall pyqt5 and pyqt5-sip and reinstall it using pip, all works just fine.

The following is the content of my `setup.py` script:

```
from setuptools import setup

setup()
```

And this is the content of my `setup.cfg` file:

```
[metadata]
name = pceb
version = attr: pceb.__version__
description = Image Degradation Module
long_description = file: README.md
long_description_content_type = text/markdown
author = foo bar
author_email = foo.bar@outlook.com.br
classifiers =
    Operating System :: OS Independent
    Programming Language :: Python :: 3.6

[options]
include_package_data = True
packages = find:
install_requires =
    setuptools == 51.0.0
    matplotlib == 3.1.3
    opencv-python == 4.2.0.32
    PyYAML == 5.3.1
    rawpy == 0.15.0
    tqdm == 4.43.0
    numpy == 1.18.5
    pillow == 8.1.2
    PyQt5-sip == 12.8.1
    PyQt5 == 5.14.2
    PyOpenGL == 3.1.5
    qdarkstyle == 2.8.1

[options.entry_points]
console_scripts =
    pceb = pceb.main:main
```

### Expected behavior

The expected behavior was: Releasing the package and made it available through pip, where it installs all the dependencies altogether with the package itself. However, this is not happening, as one first needs to uninstall PyQt5 and PyQt5-sip and reinstall it using pip.

### How to Reproduce

1. Create a simple python package that made use of `PyQt5`
2. Use the `install_requires` field in a `setup.cfg` file to specify the PyQt5 as a dependency (v5.14.2)
3. Install the simple package in a fresh python installation: `python setup.py install`
4. Start your package Graphical Interface 

### Output

You should get and error like:

```console
Traceback (most recent call last):
  File "/home/foo.bar/anaconda3/envs/git_issu/bin/pceb", line 33, in <module>
    sys.exit(load_entry_point('pceb==3.1.1', 'console_scripts', 'pceb')())
  File "/home/foo.bar/anaconda3/envs/git_issu/bin/pceb", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/foo.bar/anaconda3/envs/git_issu/lib/python3.6/site-packages/importlib_metadata-3.10.0-py3.6.egg/importlib_metadata/__init__.py", line 167, in load
    module = import_module(match.group('module'))
  File "/home/foo.bar/anaconda3/envs/git_issu/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/foo.bar/anaconda3/envs/git_issu/lib/python3.6/site-packages/pceb-3.1.1-py3.6.egg/pceb/main.py", line 13, in <module>
  File "/home/foo.bar/anaconda3/envs/git_issu/lib/python3.6/site-packages/pceb-3.1.1-py3.6.egg/pceb/interface/main_gui.py", line 2, in <module>
ModuleNotFoundError: No module named 'PyQt5.sip
```

### Code of Conduct

I agree to follow the PSF Code of Conduct

**Comment by webknjaz** [comment] 2021-04-16 22:42
@Fcsalvagnini it's not entirely clear what your problem is but I can tell you right away that it's highly discouraged to use `setup.py install` because it does not produce the same amount of metadata `pip` does making it impossible to `pip uninstall` such a thing.

Also, we need a minimum verifiable reproducer not relying on anaconda — what if your issue is with them? Plus the posted STR is too vague — can we do this without Qt? I wouldn't expect the maintainers will want to learn how to use it just to try understanding what you meant by "make use of Qt".

Could you add a reproducer that has exact source and exact commands including how you set up the environment and stuff, what the versions are. And also let's try using venv or virtualenv as a commonly known env creation method. I, for one, have never installed conda and have no idea if there's many installation methods and whether they produce different outcomes.

**Comment by webknjaz** [comment] 2021-04-16 22:45
Seeing posts like https://stackoverflow.com/a/51811884/595220 I'd assume that this is a problem with Qt packaging, probably unrelated to setuptools.

**Comment by abravalheri** [comment] 2023-02-21 12:10
I believe this was fixed in the last version of PyQt5:

```bash
mkdir -p /tmp/git_issue
cd /tmp/git_issue
cat <<EOF > setup.py
from setuptools import setup

setup()
EOF
cat <<EOF > setup.cfg
[metadata]
name = pceb

[options]
install_requires =
    PyQt5 == 5.15.9
EOF
pip install .
python -c 'from PyQt5 import QtCore'
# => <module 'PyQt5.QtCore' from '/usr/local/lib/python3.7/site-packages/PyQt5/QtCore.abi3.so'>
```
(Here I am using `pip install .` because `setup.py install` is deprecated).

Thank you very much `@webknjaz`.

**Closed by abravalheri** 2023-02-21 12:10 UTC
Labels: bug, Needs Repro
