### ISSUE TITLE
[BUG] Package data not installing nested dirs

### ISSUE THREAD

**Issue by roysc** [pypa/setuptools#4402] opened 2024-05-28 09:22 UTC
### setuptools version

setuptools==70.0.0

### Python version

Python 3.10

### OS

macOS Sonoma 14.4.1 (aarch64)

### Additional environment information

Happens when run in an Ubuntu-based Docker container.

### Description

When installing a package containing package data with a nested subdirectory which is matched by a glob in `package_data`, the nested subdirectory is not installed.

### Expected behavior

The nested data subdirectory should be installed along with other data files.
This works properly when run in a non-containerized local venv and with multiple other Docker images (e.g. `python:3.10-bookworm`, `python:3.10-alpine3.20`).

### How to Reproduce

1. Clone https://github.com/roysc/setuptools-data-subdir-reprex
2. Build docker image: `docker build . -t debug-datadirs`
3. Run container, install package and check installed files:
```docker run -v .:/app debug-datadirs -c 'pip3 -v install /app && ls -l /usr/local/lib/python3.10/dist-packages/some_package/data'```

### Output

```console
% docker run -v .:/app debug-datadirs -c 'pip3 -v install /app && ls -l /usr/local/lib/python3.10/dist-packages/some_package/data'
Using pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
Processing /app
  Installing build dependencies: started
  Running command pip subprocess to install build dependencies
  Collecting setuptools==70.0.0
    Downloading setuptools-70.0.0-py3-none-any.whl (863 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 863.4/863.4 KB 4.6 MB/s eta 0:00:00
  Installing collected packages: setuptools
  Successfully installed setuptools-70.0.0
  WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Running command Getting requirements to build wheel
  running egg_info
  writing manifest file 'debug_datadirs.egg-info/SOURCES.txt'
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Running command pip subprocess to install backend dependencies
  Collecting wheel
    Downloading wheel-0.43.0-py3-none-any.whl (65 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.8/65.8 KB 1.2 MB/s eta 0:00:00
  Installing collected packages: wheel
  Successfully installed wheel-0.43.0
  WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Running command Preparing metadata (pyproject.toml)
  running dist_info
  creating /tmp/pip-modern-metadata-6gmn1dg3/debug_datadirs.egg-info
  writing manifest file '/tmp/pip-modern-metadata-6gmn1dg3/debug_datadirs.egg-info/SOURCES.txt'
  writing manifest file '/tmp/pip-modern-metadata-6gmn1dg3/debug_datadirs.egg-info/SOURCES.txt'
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: debug-datadirs
  Building wheel for debug-datadirs (pyproject.toml): started
  Running command Building wheel for debug-datadirs (pyproject.toml)
  running bdist_wheel
  running build
  running build_py
  running install
  running install_lib
  creating build/bdist.linux-aarch64/wheel
  creating build/bdist.linux-aarch64/wheel/some_package
  copying build/lib/some_package/__init__.py -> build/bdist.linux-aarch64/wheel/some_package
  creating build/bdist.linux-aarch64/wheel/some_package/data
  copying build/lib/some_package/data/file1.txt -> build/bdist.linux-aarch64/wheel/some_package/data
  copying build/lib/some_package/data/__init__.py -> build/bdist.linux-aarch64/wheel/some_package/data
  running install_egg_info
  running egg_info
  writing manifest file 'debug_datadirs.egg-info/SOURCES.txt'
  Copying debug_datadirs.egg-info to build/bdist.linux-aarch64/wheel/debug_datadirs-0.1.0.egg-info
  running install_scripts
  Building wheel for debug-datadirs (pyproject.toml): finished with status 'done'
  Created wheel for debug-datadirs: filename=debug_datadirs-0.1.0-py3-none-any.whl size=1565 sha256=90226831e93bca0973f072af33da640132c42dc6af72ba947f6c884d79799ae9
  Stored in directory: /tmp/pip-ephem-wheel-cache-yce2ps5t/wheels/9b/2c/d1/15e20a2b97f37ccf65a87ba1049c73a9076d0bf0fbaf814e83
Successfully built debug-datadirs
Installing collected packages: debug-datadirs
Successfully installed debug-datadirs-0.1.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
total 8
-rw-r--r-- 1 root root    0 May 28 09:16 __init__.py
drwxr-xr-x 2 root root 4096 May 28 09:16 __pycache__
-rw-r--r-- 1 root root   10 May 28 09:16 file1.txt
```
Note that `some_package/data/subdir` is missing.

**Comment by abravalheri** [comment] 2024-05-28 09:29
Hi @roysc, please note that in Python any directory is considered a package (it does not need to contain `__init__.py` - the difference is that packages that don't have `__init__.py` are called namespace packages).

Your configuration is intentionally excluding namespace packages from the wheel... That is why such directories are not included.

You have 2 options: either add `__init__.py` to the directories that don't have one, or replace `find_packages` with `find_namespace_packages` in you `setup.py`.

See https://setuptools.pypa.io/en/latest/userguide/datafiles.html.

**Comment by roysc** [comment] 2024-05-28 10:32
Unfortunately that doesn't change the result. If I'm interpreting this output right, `subdir` is picked up by `find_namespace_packages` but it's still expected to contain `__init__.py`:

Note:`  package init file 'some_package/data/subdir/__init__.py' not found (or not a regular file)`, below.

Also note that this is using pip 22.2. I've found the behavior changes as of `23.0.0`, and I was about to file a bug with pip. 

```
Using pip 22.2 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)
Processing /app
  Installing build dependencies: started
  Running command pip subprocess to install build dependencies
  Collecting setuptools==70.0.0
    Downloading setuptools-70.0.0-py3-none-any.whl (863 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 863.4/863.4 kB 4.3 MB/s eta 0:00:00
  Installing collected packages: setuptools
  Successfully installed setuptools-70.0.0
  WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

  [notice] A new release of pip available: 22.2 -> 24.0
  [notice] To update, run: python3 -m pip install --upgrade pip
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Running command Getting requirements to build wheel
  running egg_info
  creating debug_datadirs.egg-info
  writing manifest file 'debug_datadirs.egg-info/SOURCES.txt'
  package init file 'some_package/data/subdir/__init__.py' not found (or not a regular file)
  writing manifest file 'debug_datadirs.egg-info/SOURCES.txt'
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Running command pip subprocess to install backend dependencies
  Collecting wheel
    Downloading wheel-0.43.0-py3-none-any.whl (65 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.8/65.8 kB 1.6 MB/s eta 0:00:00
  Installing collected packages: wheel
  Successfully installed wheel-0.43.0
  WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

  [notice] A new release of pip available: 22.2 -> 24.0
  [notice] To update, run: python3 -m pip install --upgrade pip
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Running command Preparing metadata (pyproject.toml)
  running dist_info
  creating /tmp/pip-modern-metadata-qwc7sihr/debug_datadirs.egg-info
  writing manifest file '/tmp/pip-modern-metadata-qwc7sihr/debug_datadirs.egg-info/SOURCES.txt'
  package init file 'some_package/data/subdir/__init__.py' not found (or not a regular file)
  writing manifest file '/tmp/pip-modern-metadata-qwc7sihr/debug_datadirs.egg-info/SOURCES.txt'
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: debug-datadirs
  Building wheel for debug-datadirs (pyproject.toml): started
  Running command Building wheel for debug-datadirs (pyproject.toml)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/some_package
  copying some_package/__init__.py -> build/lib/some_package
  creating build/lib/some_package/data
  copying some_package/data/__init__.py -> build/lib/some_package/data
  package init file 'some_package/data/subdir/__init__.py' not found (or not a regular file)
  copying some_package/data/file1.txt -> build/lib/some_package/data
  running install
  running install_lib
  creating build/bdist.linux-aarch64
  creating build/bdist.linux-aarch64/wheel
  creating build/bdist.linux-aarch64/wheel/some_package
  copying build/lib/some_package/__init__.py -> build/bdist.linux-aarch64/wheel/some_package
  creating build/bdist.linux-aarch64/wheel/some_package/data
  copying build/lib/some_package/data/file1.txt -> build/bdist.linux-aarch64/wheel/some_package/data
  copying build/lib/some_package/data/__init__.py -> build/bdist.linux-aarch64/wheel/some_package/data
  running install_egg_info
  running egg_info
  writing manifest file 'debug_datadirs.egg-info/SOURCES.txt'
  Copying debug_datadirs.egg-info to build/bdist.linux-aarch64/wheel/debug_datadirs-0.1.0.egg-info
  running install_scripts
  Building wheel for debug-datadirs (pyproject.toml): finished with status 'done'
  Created wheel for debug-datadirs: filename=debug_datadirs-0.1.0-py3-none-any.whl size=1565 sha256=8549bf89be806e2d5ae39e9ce7e289f25a62dd876fe5663453d6a41b68dcb06e
  Stored in directory: /tmp/pip-ephem-wheel-cache-48234ivw/wheels/9b/2c/d1/15e20a2b97f37ccf65a87ba1049c73a9076d0bf0fbaf814e83
Successfully built debug-datadirs
Installing collected packages: debug-datadirs
Successfully installed debug-datadirs-0.1.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip available: 22.2 -> 24.0
[notice] To update, run: python3 -m pip install --upgrade pip
total 8
-rw-r--r-- 1 root root    0 May 28 10:16 __init__.py
drwxr-xr-x 2 root root 4096 May 28 10:16 __pycache__
-rw-r--r-- 1 root root   10 May 28 10:16 file1.txt
```

**Comment by roysc** [comment] 2024-05-28 10:45
It's also not clear to me why `data` needs to be identified as a namespace package at all. 
The docs seem to indicate that files only need to match a glob pattern to be included by `package_data`. However, it doesn't specify how this interacts with recognized package names, or exactly what kind of patterns should work: 

> setuptools do not support glob patterns on package names for this configuration (patterns are only supported on the file paths)

To me this doesn't imply that `data/**` would be a problem, as the glob portion only applies to file paths - but again, it's not clear.

**Comment by abravalheri** [comment] 2024-05-28 11:01
> Note:` package init file 'some_package/data/subdir/__init__.py' not found (or not a regular file)`, below.

I believe this is informational, right? I does not mean that it is not installed... Could you please check if the installation directory is populated?

> Also note that this is using pip 22.2. I've found the behavior changes as of 23.0.0, and I was about to file a bug with pip.

Please use the latest version of `pip` so we have a better idea. Maybe even try to build a wheel with `python -m build` and see the file listing with `unzip -l`?

> It's also not clear to me why data needs to be identified as a namespace package at all.

That is how Python works, directories are packages. You can import them using an `import` statement or `importlib.import_module`.

> The docs seem to indicate that files only need to match a glob pattern to be included by package_data. However, it doesn't specify how this interacts with recognized package names, or exactly what kind of patterns should work:

The problem here is that the existence of the `package` needs to be guaranteed before the `package_data` can be placed inside that.

It is complicated, my personal opinion is that allowing nested glob patterns was a decision that just made this process more confuse. But I guess it would be problematic to remove it now.

If you would like to suggest any change it the docs, please feel free to submit a PR.

I believe that this part of the docs are highly relevant here:

![image](https://github.com/pypa/setuptools/assets/320755/f5714a3c-df3d-4b21-a1dc-9fc57036d592)

**Comment by roysc** [comment] 2024-05-28 11:28
> I believe this is informational, right? I does not mean that it is not installed... Could you please check if the installation directory is populated?

It's not installed. The output I pasted at the bottom is from running with the `find_namespace_packages` change (updated in https://github.com/roysc/setuptools-data-subdir-reprex) - note the final listing still doesn't include `subdir`:
```
total 8
-rw-r--r-- 1 root root    0 May 28 10:16 __init__.py
drwxr-xr-x 2 root root 4096 May 28 10:16 __pycache__
-rw-r--r-- 1 root root   10 May 28 10:16 file1.txt
```

> Please use the latest version of `pip` so we have a better idea.

This doesn't happen with any pip version I've tested beyond `23.0.0`, which is what I meant by a change in behavior. It may be something fixed (directly or indirectly) in later versions, but I would still expect `22.2` to get a patch.

> Maybe even try to build a wheel with `python -m build` and see the file listing with `unzip -l`?

A wheel built with `build` _does_ include the subdirectory, and it's also included by `pip install`.

To clarify, I understand this is not the recommended pattern for including data files. My main concern here is about the inconsistent behavior.

**Comment by roysc** [comment] 2024-05-28 12:15
Okay, at this point I'm prepared to give up on finding an explanation.

The thing that's still not clear to me from the docs: what, if any, is the correct way to include arbitrarily-nested data directories if not glob patterns?

**Comment by roysc** [comment] 2024-05-30 10:28
> Please let me know if you find inconsistency (i.e. using the same configuration and achieving different results) when you remove `pip` "out of the equation".

So far I haven't seen this when installing from a wheel or sdist rather than `pip` directly.

> There is a special value for "all packages", maybe you can try `package_data={"": ["*"]}`. Let me know how it goes.

This works. I believe I tried it before, but probably not with the correct namespace packages set. And indeed no MANIFEST.in was needed. (With `pyproject.toml` I had to use `package-data = {"*" = ["*"]}`.)

Thank you for your time on this. There's been a lot of developments here in the past several years that I haven't kept up with, but now I should know enough to work past the occasional incongruence between tools.

**Comment by abravalheri** [comment] 2024-05-30 11:42
Thank you very much @roysc. I think I will close this issue now as a noop.

Although it is difficult to understand - much likely due to the feature of nested glob patterns - the output in the wheel seems to be working as intended and documented.

**Closed by abravalheri** 2024-05-30 11:42 UTC
Labels: Waiting User Feedback

**Comment by ichard26** [comment] 2024-07-08 13:36
If you want to, you are welcome to file a new bug report against pip if you believe pip is partly responsible for buggy behaviour described here. It doesn't sound trivial, but it should be tracked if real.  

(Commenting here as the pip issue is locked now.)

**Comment by roysc** [comment] 2024-07-19 16:36
@ichard26 I would, but it seems like it will take a bit too much time to break this down any further. I'm fairly certain it's real, but the impact is limited.
