### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by tdene** [pypa/setuptools#3312] opened 2022-05-09 18:36 UTC
### setuptools version

45.2.0

### Python version

Python 3.8.10

### OS

Ubuntu

### Description

setuptools chooses to not install `__init__.py` files other than the main package's.

This is a documented choice, which I could find as far back as #1097

This leads to problematic and inconsistent behavior when combined with `importlib.resources`, as can be seen in [this small test repository](https://github.com/tdene/setuptools_issue).

Specifically, `importlib.resources.path` refuses to recognize submodules such as `issue_test.test_data` when they are automatically installed, because there is no `__init__.py` file present.

However, manually installing packages (whether by `pip -e` or by manual file copying) does not show this issue, instead working as expected.

### Expected behavior

setuptools's choice to not install `__init__.py` files other than the main package's should play nice with `importlib.resources.path`?

Or maybe I am just trying something that is unorthodox and should not be allowed. It is unclear which of these is the case.

### How to Reproduce

1. Observe the minimal setup required to reproduce this issue that can be found [here](https://github.com/tdene/setuptools_issue)
2. Clone the Python package in question
3. Install it with `pip install -e .`
4. Run `python3 -c "from issue_test import test; test.pkg_test();"` and note the lack of an issue.
5. Uninstall it with `pip uninstall issue_test`
6. Re-install it with `pip install .`
7. Run `python3 -c "from issue_test import test; test.pkg_test();"` and note the presence of an issue.

### Output

```
tdene@tdene-home:~/data/setuptools_issue$ pip install -e .
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/tdene/data/setuptools_issue
  Preparing metadata (setup.py) ... done
Installing collected packages: issue-test
  Running setup.py develop for issue-test
Successfully installed issue-test-0.0.0
tdene@tdene-home:~/data/setuptools_issue$ python3 -c "from issue_test import test; test.pkg_test();"
Successful
tdene@tdene-home:~/data/setuptools_issue$ pip uninstall issue_test
Found existing installation: issue-test 0.0.0
Uninstalling issue-test-0.0.0:
  Would remove:
    /home/tdene/.local/lib/python3.8/site-packages/issue-test.egg-link
Proceed (Y/n)? y
  Successfully uninstalled issue-test-0.0.0
tdene@tdene-home:~/data/setuptools_issue$ pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/tdene/data/setuptools_issue
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: issue-test
  Building wheel for issue-test (setup.py) ... done
  Created wheel for issue-test: filename=issue_test-0.0.0-py3-none-any.whl size=1522 sha256=e854f6fd87c3c8f706691680c0e96c9c139da65c9539bf5a29e5d037c2cb4a2d
  Stored in directory: /tmp/pip-ephem-wheel-cache-91we3hy5/wheels/c7/e6/aa/a632c5a16c3bc5f24c9bc49ab085af5e5dd822029feb2ee3ad
Successfully built issue-test
Installing collected packages: issue-test
Successfully installed issue-test-0.0.0
tdene@tdene-home:~/data/setuptools_issue$ python3 -c "from issue_test import test; test.pkg_test();"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tdene/.local/lib/python3.8/site-packages/issue_test/test.py", line 4, in pkg_test
    with importlib.resources.path("issue_test.test_data","data.txt") as pkg_file:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.8/importlib/resources.py", line 184, in path
    package = _get_package(package)
  File "/usr/lib/python3.8/importlib/resources.py", line 47, in _get_package
    module = import_module(package)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'issue_test.test_data'
```

**Comment by tdene** [comment] 2022-05-09 20:55
Follow-up comment.

A solution to my issue that exists within the current framework consists of using `find_namespace_packages` as seen in [this branch of the test repository](https://github.com/tdene/setuptools_issue/tree/solution).

`master` is non-functional unless installed with `-e`. `solution` is functional in all cases.

I believe the issue may be closed, but I do want to leave this here for posterity.

Keywords for future search engine queries, in hope of helping someone else:

"importlib.resources" "importlib.resources.path" "python package data folder"

**Comment by nullableVoidPtr** [comment] 2022-05-11 09:13
Hi,

I'm not too certain if this is considered unintended behaviour, as the test package you have demonstrated (thanks for that!) could be the result of packager error on the specified packages (not including `issue_test.test_data`, or not using `find_packages`), although the inconsistency between wheel installs and editable installs may be a cause for concern. Personally, I think it's within expectations.

Further, yes, having a non-package subdirectory containing data is a little unorthodox, but besides  `importlib.resources.path` (which does not allow subdirectories in the resource name), there is [`importlib.resources.files`](https://docs.python.org/3/library/importlib.html#importlib.resources.files) (only in 3.9, but backported in [`importlib-resources`](https://pypi.org/project/importlib-resources/)), which returns a `Traversable` and hence can "dive into" non-package subdirectories.

**Comment by abravalheri** [comment] 2022-05-11 12:36
Hi @tdene thank you very much for reporting this.

I agree with @nullableVoidPtr. In fact from Python's perspective the folder `issue_test/test_data` corresponds to the `issue_test.test_data` package. (That is just how Python works, if you set `PYTHONPATH` to the root of your project, you will be able to run `import issue_test.test_data` in a REPL).

There seems to be a misalignment of expectations: the `setup.py` script does not list `issue_test.test_data` as a package (instead only `issue_test` is listed), normally this would indicate to setuptools that `issue_test.test_data` should be left out of the wheel. (There are packages out there that rely on this behaviour).

When you use `find_namespace_packages`, setuptools will return `["issue_test", "issue_test.test_data"]`, that is why it solves the problem.

In the latest versions of setuptools you don't even need to specify `packages`, the [automatic discovery](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html) can take care of that (unless the package structure is very customised).

**Comment by abravalheri** [comment] 2022-05-11 12:37
For the time being I will close this issue, but please let me know if you think otherwise.

**Closed by abravalheri** 2022-05-11 12:37 UTC
Labels: bug, Needs Triage
