### ISSUE TITLE
pip 19.2.3: dependency installation not houring private package server

### ISSUE THREAD

**Issue by shvkumara** [pypa/setuptools#2391] opened 2020-09-16 13:11 UTC
My Case: I have a isolated server`(without internet and python 3.8.2)` which as python virtual env at` /apps/interface/usr/`, All my wheels are stored in `https://my.private.org/` I am using pip 19.2.3 to install the packages.

Now, I have pacakge named py, which has condition like "`setup_requires=["setuptools-scm"]`," (dependency).

    py package is downloaded from `https://my.private.org/ `
    now, while trying to download setuptools-scm, its referring to https://files.pythonhosted.org/packages/... instead of https://my.private.org/ I have tried the below methods to redirect the pip to install wheels from https://my.private.org/ .

Point: The main package is getting installed from my personal repo, But the dependency packages is trying to download from public web which we don't have access to.

Method 1:

`pip3.8 install py==1.8.1 --index-url https://user:psw@my.private.org/ --extra-index-url https://user:psw@my.private.org/ -v`

Method 2: updated /apps/interface/usr/lib/python3.8/distutils/distutils.cfg

```
[easy_install]
find_links = https://user:psw@my.private.org/
index-url = https://user:psw@my.private.org/
```

but no use.

Method 3: updated below files (tried with each file)

```
/etc/xdg/pip/pip.conf
/etc/pip.conf
/root/.pip/pip.conf
/root/.config/pip/pip.conf
/apps/interface/usr/pip.conf
```

Below is the error I am getting
```
raise DistutilsError("Download error for %s: %s"
    distutils.errors.DistutilsError: Download error for https://files.pythonhosted.org/packages/ad/d3/e54f8b4cde0f6fb4f231629f570c1a33ded18515411dee6df6fe363d976f/setuptools_scm-4.1.2-py2.py3-none-any.whl#sha256=69258e2eeba5f7ce1ed7a5f109519580fa3578250f8e4d6684859f86d1b15826: [Errno 101] Network is unreachable
```

Hope to find a way to fix this the issue.

Note: Below is Error details
```
Downloading from URL https://my.private.org/py/py-1.8.1.tar.gz (from https://my.private.org/py/)
     |████████████████████████████████| 215kB 74kB/s 
  Added py==1.8.1 from https://my.private.org/py/py-1.8.1.tar.gz to build tracker '/tmp/pip-req-tracker-gohcv4uc'
    Running setup.py (path:/tmp/pip-install-xp37jgnc/py/setup.py) egg_info for package py
    Running command python setup.py egg_info
 Traceback (most recent call last):
      File "/usr/local/lib/python3.8/urllib/request.py", line 1319, in do_open
        h.request(req.get_method(), req.selector, req.data, headers,
      File "/usr/local/lib/python3.8/http/client.py", line 1230, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/usr/local/lib/python3.8/http/client.py", line 1276, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/usr/local/lib/python3.8/http/client.py", line 1225, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/usr/local/lib/python3.8/http/client.py", line 1004, in _send_output
        self.send(msg)
      File "/usr/local/lib/python3.8/http/client.py", line 944, in send
        self.connect()
      File "/apps/interface/usr/lib/python3.8/site-packages/setuptools/ssl_support.py", line 173, in connect
        sock = socket.create_connection(
      File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
        raise err
      File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
        sock.connect(sa)
    OSError: [Errno 101] Network is unreachable

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/apps/interface/usr/lib/python3.8/site-packages/setuptools/package_index.py", line 766, in open_url
        return open_with_auth(url, self.opener)
      File "/apps/interface/usr/lib/python3.8/site-packages/setuptools/package_index.py", line 961, in _socket_timeout
        return func(*args, **kwargs)
      File "/apps/interface/usr/lib/python3.8/site-packages/setuptools/package_index.py", line 1080, in open_with_auth
        fp = opener(request)
      File "/usr/local/lib/python3.8/urllib/request.py", line 525, in open
        response = self._open(req, data)
      File "/usr/local/lib/python3.8/urllib/request.py", line 542, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +
      File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
        result = func(*args)
      File "/apps/interface/usr/lib/python3.8/site-packages/setuptools/ssl_support.py", line 160, in https_open
        return self.do_open(
      File "/usr/local/lib/python3.8/urllib/request.py", line 1322, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xp37jgnc/py/setup.py", line 42, in <module>
        main()
      File "/tmp/pip-install-xp37jgnc/py/setup.py", line 5, in main
        setup(
      File "/apps/interface/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/apps/interface/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/apps/interface/usr/lib/python3.8/site-packages/setuptools/dist.py", line 716, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/apps/interface/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "/apps/interface/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/apps/interface/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/apps/interface/usr/lib/python3.8/site-packages/setuptools/dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "/apps/interface/usr/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
        dist = self.package_index.fetch_distribution(
      File "/apps/interface/usr/lib/python3.8/site-packages/setuptools/package_index.py", line 655, in fetch_distribution
        dist = find(requirement)
      File "/apps/interface/usr/lib/python3.8/site-packages/setuptools/package_index.py", line 635, in find
        loc = self.download(dist.location, tmpdir)
      File "/apps/interface/usr/lib/python3.8/site-packages/setuptools/package_index.py", line 579, in download
        found = self._download_url(scheme.group(1), spec, tmpdir)
      File "/apps/interface/usr/lib/python3.8/site-packages/setuptools/package_index.py", line 824, in _download_url
        return self._attempt_download(url, filename)
      File "/apps/interface/usr/lib/python3.8/site-packages/setuptools/package_index.py", line 830, in _attempt_download
        headers = self._download_to(url, filename)
      File "/apps/interface/usr/lib/python3.8/site-packages/setuptools/package_index.py", line 729, in _download_to
        fp = self.open_url(url)
      File "/apps/interface/usr/lib/python3.8/site-packages/setuptools/package_index.py", line 779, in open_url
        raise DistutilsError("Download error for %s: %s"
    distutils.errors.DistutilsError: Download error for https://files.pythonhosted.org/packages/ad/d3/e54f8b4cde0f6fb4f231629f570c1a33ded18515411dee6df6fe363d976f/setuptools_scm-4.1.2-py2.py3-none-any.whl#sha256=69258e2eeba5f7ce1ed7a5f109519580fa3578250f8e4d6684859f86d1b15826: [Errno 101] Network is unreachable
Cleaning up...
  Removing source in /tmp/pip-install-xp37jgnc/py
Removed py==1.8.1 from https://packages.zeomega.org/py/py-1.8.1.tar.gz from build tracker '/tmp/pip-req-tracker-gohcv4uc'
Removed build tracker '/tmp/pip-req-tracker-gohcv4uc'
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by usmcamp0811** [comment] 2020-09-17 12:44
I think this is the exact same problem I am facing! I think I have a solution identified in my issue (#2385 ) I posted last week. It's a problem with `easy_install.py` having a hard coded url and somewhere along the kill chain the system default pypi url isn't being conveyed.

**Comment by shvkumara** [comment] 2020-09-18 06:51
@usmcamp0811   Thanks for the suggestion.. I just tried with the fix you have pointed. and It worked..

**Comment by jaraco** [comment] 2020-09-21 13:47
Dupe of #2385.

**Closed by jaraco** 2020-09-21 13:47 UTC
Labels: duplicate
