### ISSUE TITLE
Unable to install setuptools in debian 8.4 via ez_setup.py

### ISSUE THREAD

**Issue by liminspace** [pypa/setuptools#585] opened 2016-05-14 13:36 UTC
Console output:

``` bash
root@debian:/# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.4 (jessie)
Release:    8.4
Codename:   jessie

root@debian:/# wget -q https://bootstrap.pypa.io/ez_setup.py -O - | python
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-21.0.0.zip
Traceback (most recent call last):
  File "<stdin>", line 425, in <module>
  File "<stdin>", line 421, in main
  File "<stdin>", line 345, in download_setuptools
  File "<stdin>", line 264, in download_file_curl
  File "<stdin>", line 219, in _clean_check
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['curl', 'https://pypi.io/packages/source/s/setuptools/setuptools-21.0.0.zip', '--location', '--silent', '--output', '/setuptools-21.0.0.zip']' returned non-zero exit status 60
```

**Comment by jaraco** [comment] 2016-05-14 14:36
I suspect this is caused by #559. And older versions of curl don't support following redirects.

What happens if you run that command in the error message, except omit --silent? Wh. Does curl reveal the underlying error?

**Comment by ssaid** [comment] 2016-08-05 15:51
Hi, I'm facing a similar problem:
> curl https://pypi.io/packages/source/s/setuptools/setuptools-25.1.4.zip  

Returns me
> <html><head><title>301 Moved Permanently</title></head><body><center><h1>301 Moved Permanently</h1></center></body></html>

CURL Version:
> curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP

**Comment by abravalheri** [comment] 2022-01-05 00:10
Hello, since `ez_setup` has been deprecated for a while, I assume it should be OK to close this issue for now.

If anyone would like to reopen it, please feel free to write a new comment with more information or other use cases that we might be missing 😄.

**Closed by abravalheri** 2022-01-05 00:10 UTC
Labels: Needs Triage
