### ISSUE TITLE
find_packages() not compatible with PEP420 namespaces

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#431] opened 2015-09-07 20:10 UTC
Originally reported by: **wichert (Bitbucket: [wichert](http://bitbucket.org/wichert), GitHub: [wichert](http://github.com/wichert))**

----------------------------------------

I ran into a problem with a package always generating empty wheels. This turned out to be caused by setuptools.find_packages not finding any packages when using PEP 420 namespaces. This is easy to test:

```
$ mkdir -p src/foo/bar
$ : > src/foo/bar/__init__.py
$ python  -c 'from setuptools import find_packages ; print(find_packages("src"))'
[]
```

Adding an empty __init__.py to quickly simulate old-style namespace packages makes find_packages do the right thing:

```
$ : > src/foo/__init__.py
$ ../bin/python  -c 'from setuptools import find_packages ; print(find_packages("src"))'
['foo', 'foo.bar']
```

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/431

**Comment by kawing-chiu** [comment] 2016-10-10 03:06
+1 for namespace package support

**Comment by jaraco** [comment] 2016-10-19 15:43
Duplicate of #97.

**Closed by jaraco** 2016-10-19 15:43 UTC
Labels: bug, major
