### ISSUE TITLE
enable rolling builds support on AppVeyor

### ISSUE THREAD

**Issue by benoit-pierre** [pypa/setuptools#1518] opened 2018-10-23 15:31 UTC
Can someone with the necessary rights enable [rolling builds](https://www.appveyor.com/docs/build-configuration/#rolling-builds) on AppVeyor for the setuptools project?

**Comment by pganssle** [comment] 2018-10-23 15:32
@benoit-pierre Do you not have the relevant rights? I think if you sign in as PyPA you should have admin rights on `setuptools`, as a member of pypa/setuptools-developers.

**Comment by benoit-pierre** [comment] 2018-10-23 15:37
No, I can cancel/trigger builds, but not manage projects settings.

**Comment by pganssle** [comment] 2018-10-23 15:40
Hm, I'm seeing the same thing. I thought they used to ask you to log in as a specific team. I can't even find the project-specific settings for projects where I am the sole administrator...

@ewdurbin @di Maybe knows what to do?

**Comment by benoit-pierre** [comment] 2018-10-23 15:43
You can switch teams with the button on the top-left.

**Comment by pganssle** [comment] 2018-10-23 15:45
@benoit-pierre Yeah, but that doesn't give me access to project-specific settings on any of my repos, as far as I can tell. Looks like I am just able to manage org-specific settings.

**Comment by benoit-pierre** [comment] 2018-10-23 15:47
I can manage project settings for my repos (using the rightmost button on the toolbar that appears when hovering on the project name, in the projects page).

**Comment by pganssle** [comment] 2018-10-23 15:50
@benoit-pierre I'm going to collapse our previous conversation because it was me not understanding the UI and I don't want that to distract from the conversation. I see now how it works.

I think probably it's @ewdurbin who controls the repo rights for Appveyor. Would be nice if we could get @pypa/setuptools-developers admin rights on the `setuptools` settings.

**Comment by ewdurbin** [comment] 2018-10-23 15:51
I'm not familiar with the AppVeyor configuration for any of the projects in the Python space using it. My user doesn't seem to have any access to the teams/projects therein.

Do we know who initially set this all up?

**Comment by pganssle** [comment] 2018-10-23 16:00
Seems like @pfmoore has admin rights at least for `pip`, if I'm reading [this comment correctly](https://github.com/pypa/pip/pull/5190#issuecomment-379551844).

**Comment by di** [comment] 2018-10-23 16:06
Sorry, I can't help here either.

**Comment by pganssle** [comment] 2018-10-23 16:18
Hm, actually, [this issue where we got appveyor permissions](https://github.com/pypa/packaging-problems/issues/148) looks like maybe @pfmoore and @jaraco might have the right permissions now?

We should probably try and sort this out properly this weekend.

**Comment by benoit-pierre** [comment] 2018-10-23 17:34
@pfmoore: Yes, thanks!

> Let me know if you need something else doing.

There's something wrong with pip's AppVeyor going on: each merge triggers 3 builds! See https://github.com/pypa/pip/pull/5910#issuecomment-432297985, https://github.com/pypa/pip/pull/5910#issuecomment-432298772 and https://github.com/pypa/pip/pull/5909#issuecomment-432327813. I'd be interested to know what the events log on AppVeyor for the project has to say.

**Comment by pfmoore** [comment] 2018-10-23 17:34
Permissions on the PyPA account on Appveyor look like the following:

![image](https://user-images.githubusercontent.com/1110419/47379121-ec04cc80-d6f1-11e8-9e7b-eb9adaba783c.png)

![image](https://user-images.githubusercontent.com/1110419/47379146-fd4dd900-d6f1-11e8-9c8a-9531b1364ca6.png)

It's easy enough to change things here, but it's worth noting that the Appveyor permissions are on the "PyPA" account, so permissions will apply across all the PyPA projects (currently pip, setuptools and pipenv - although pipenv's last build was titled "death to appveyor!" so I guess they moved off appveyor :wink:).

**Comment by pfmoore** [comment] 2018-10-23 17:37
>  I'd be interested to know what the events log on AppVeyor for the project has to say.

Nothing much, sadly...

![image](https://user-images.githubusercontent.com/1110419/47379357-9846b300-d6f2-11e8-8188-ef6dcac05e7e.png)

**Comment by benoit-pierre** [comment] 2018-10-23 17:42
Apart for the cancellations, can you find the specific events that created the 1.0.3659, 1.0.3660 and 1.0.3661 builds?

**Comment by pfmoore** [comment] 2018-10-23 17:47
Nope, there was absolutely nothing for any of them. Everything below what I posted was for older builds...

I have no idea how there could be no "Created" event at all :-(

**Comment by pganssle** [comment] 2018-10-23 17:52
@pfmoore While we're doing Appveyor stuff, I imagine @dstufft @ewdurbin and @di should all be in @pypa/appveyor-admins, since they all have pan-PyPA roles.

**Comment by benoit-pierre** [comment] 2018-10-23 17:53
@pfmoore: I'll create a discussion on AppVeyor support forum.

**Comment by benoit-pierre** [comment] 2018-10-23 18:03
@pfmoore: Should be fixed now, see https://help.appveyor.com/discussions/problems/17650-multiple-builds-triggered-on-merge. We'll see for sure with the next merge.

**Comment by pganssle** [comment] 2018-10-23 18:11
@benoit-pierre #1517 is ready to be merged when CI passes, you can use that to test it out.

**Comment by benoit-pierre** [comment] 2018-10-23 18:16
OK, thanks.

**Comment by pfmoore** [comment] 2018-10-23 18:30
Also, it would probably be useful if the setuptools and pip projects could have their own admins, but I don't see any means of doing that in Appveyor. So we may have to live with just pypa-level admins.

I don't actually have any great problem personally with extending pypa appveyor rights to the pip and setuptools devs (I can't think of any particular harm it could do), But I'd prefer to get confirmation from @jaraco and/or @dstufft before doing that.

**Comment by jaraco** [comment] 2018-10-23 18:46
@pfmoore confirmed - happy to share administrative burden with all mentioned above.

**Comment by pfmoore** [comment] 2018-10-23 19:16
OK, I've given @pypa/pip-committers and @pypa/setuptools-developers admin rights to the Appveyor pypa account.

**Closed** 2018-10-23 19:40 UTC
Labels: trivial
