### ISSUE TITLE
bdist_wheel fails on WSL Ubuntu 18.04

### ISSUE THREAD

**Issue by phetdam** [pypa/setuptools#2348] opened 2020-08-30 00:50 UTC
Edit: `--dry-run` also results in errors, which I assume is because no directories are actually being created.

Was building a pure Python project using setuptools 49.6.0 in a virtual environment using Python 3.8.2 on WSL Ubuntu 18.04. Running `python3 setup.py sdist bdist_wheel` causes `setup.py` to raise an error right after printing `running install_scripts` to the console, right before it adds the license and starts building the wheel. The error reads as follows (project is called touketsu):

`error: [('build/bdist.linux-x86_64/wheel/touketsu-0.1.0-py3.8.egg-info', 'build/bdist.linux-x86_64/wheel/touketsu-0.1.0.dist-info', "[Errno 16] Device or resource busy: 'build/bdist.linux-x86_64/wheel/touketsu-0.1.0.dist-info'")]`

Here `.` would be the repository's top level directory. Not sure why this is happening; checked the file permissions (`rwx` for all groups) and even used `sudo`, but kept getting the same error.

Help would be greatly appreciated. Thanks :)

**Comment by jaraco** [comment] 2020-08-30 20:26
I suspect what's happening here is some part of the logic is attempting to remove a file that's in use, which is allowed on Unix but not on Windows, and because you're running Unix on a filesystem backed by Windows, the code doesn't expect to have to give the Windows-relevant treatment. The next step is going to be to figure out what process is holding that file/directory open. It could be something in the installation step... or it could be something external, like a virus scan.

Could you disable Windows Defender and [disable Indexing](https://windowsreport.com/indexing-windows-8/) and retry the operation and see if it still fails?

**Comment by phetdam** [comment] 2020-08-31 08:26
Yup, that's what I was also thinking. I didn't realize that search indexing could be a problem, however.

I don't have Windows Defender active, rather Trend Micro, but I disabled search indexing and it seems to be ok now. This is strange behavior however, as I have built wheels locally using Python 3.8 installed for x86-64 Windows in the recent past. I guess it just has something to do with WSL then.

Thanks!

**Comment by GoelPri** [comment] 2021-09-22 12:18
could anyone resolve this? getting the same issue

**Comment by phetdam** [comment] 2021-09-22 17:38
Been a while since I had this issue now that I usually just build wheels on remote CI machines but I think this is a WSL thing and may not necessarily be directly resolvable by tweaking `setuptools`. As mentioned, try disabling search indexing.

@s27y I also was running VS Code in WSL; with search indexing disabled I could keep VS Code open when building the wheel.

@GoelPri Maybe try @s27y's workaround first? Again, this might be a WSL issue. Also, if you are interested in distributing wheels, I recommend you get in the habit of using a CI service, ex. through GitHub Actions, and try ensuring your wheel builds on multiple platforms. This usually shouldn't be too bad unless you have C extensions in your project, in which case I would recommend using [`cibuildwheel`](https://cibuildwheel.readthedocs.io/) to build [`manylinux`](https://github.com/pypa/manylinux) wheels for you. I've built `manylinux` wheels "by hand" before, i.e. with my own hacky shell scripts, and that was definitely a not-fun experience I would like other people to avoid.

**Comment by GoelPri** [comment] 2021-10-11 06:28
> Been a while since I had this issue now that I usually just build wheels on remote CI machines but I think this is a WSL thing and may not necessarily be directly resolvable by tweaking `setuptools`. As mentioned, try disabling search indexing.
> 
> @s27y I also was running VS Code in WSL; with search indexing disabled I could keep VS Code open when building the wheel.
> 
> @GoelPri Maybe try @s27y's workaround first? Again, this might be a WSL issue. Also, if you are interested in distributing wheels, I recommend you get in the habit of using a CI service, ex. through GitHub Actions, and try ensuring your wheel builds on multiple platforms. This usually shouldn't be too bad unless you have C extensions in your project, in which case I would recommend using [`cibuildwheel`](https://cibuildwheel.readthedocs.io/) to build [`manylinux`](https://github.com/pypa/manylinux) wheels for you. I've built `manylinux` wheels "by hand" before, i.e. with my own hacky shell scripts, and that was definitely a not-fun experience I would like other people to avoid.

Thank you so much! It works now

**Comment by phetdam** [comment] 2021-10-11 09:42
No problem. Glad to hear that things worked out.

**Comment by abravalheri** [comment] 2022-01-28 16:45
Hi @phetdam for reporting the problem and also the solution.

I use WSL all the time here and I have never faced such problem. I assume it might be related to the code editor or IDE?

I think we can close this issue now since it does not seem to be related to `setuptools` directly, but please let me know if I am wrong and I will re-open it (it would be nice to have some dummy repository with a reproduction to try it out).

**Closed by abravalheri** 2022-01-28 16:45 UTC

**Comment by phetdam** [comment] 2022-01-28 21:04
No problem and thanks. I'm sure if someone else has the same issue their Google search will eventually lead them here.
