### ISSUE TITLE
Setuptools creates non-UTF8 Python files with no encoding specified

### ISSUE THREAD

**Issue by me21** [pypa/setuptools#1400] opened 2018-06-27 07:39 UTC
My environment is: Windows 10 x64 LTSB Russian, Python x64 3.6.5, Pip 10.0.1, Setuptools 39.2.0.

I install PyInstaller with `pip install pyinstaller`. It installs, but doesn't work: `pyinstaller myscript.py` fails due to `pyinstaller-script.py` in the `Scripts` subfolder containing non-UTF-8 codes. In fact, its encoding is CP1251 on my machine but no encoding is specified inside the file.
The offending line contains the path to the Python interpreter executable. This is because I run all commands in the virtual environment located in path with non-latin characters. If I run commands in virtual environment placed in latin-only path, no errors are thrown.

The output is:
```
File "C:\Users\Зарубкин\Documents\Python Projects\uno-db\venv\Scripts\pyinstaller-script.py", line 1
SyntaxError: Non-UTF-8 code starting with '\xc7' in file C:\Users\Зарубкин\Documents\Python Projects\uno-db\venv\Scripts\pyinstaller-script.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

I think Setuptools should either create files in UTF8 encoding or specify the encoding inside the Python file.

**Comment by pganssle** [comment] 2018-10-22 17:33
So with this issue, is this `py-installer.py` something generated *by* `setuptools`, or is it something that `setuptools` is merely packaging? If you try and package a script using `setuptools` and don't specify an encoding, I don't think there's much if anything we can do about that. If `setuptools` is generating the files, then they should have the encoding specified, and probably they should be in UTF-8.

One possibility is we could take anything without an encoding specified and decode it with UTF-8, then write the output with UTF-8 to try and break this earlier in the pipeline, but I do worry that this might end up generating a bunch of mojibake and not *actually* failing.

Another option would be to decode anything with no encoding specified using UTF-8, and if it fails throw a warning/error, but otherwise leave the script unchanged. That may help some people who unknowingly have this issue, even if it's not a perfect fix.

**Comment by me21** [comment] 2018-10-22 17:49
I think that file is generated by `setuptools`, because it contains path to my virtual environment.

**Comment by pganssle** [comment] 2018-10-23 13:31
I believe this is a duplicate of #1246, so I'm consolidating the discussion there. If the two are actually different issues, please let me know and we can re-open this one.

**Closed by pganssle** 2018-10-23 13:31 UTC
Labels: bug, duplicate
