### ISSUE TITLE
Console script in windows can't take unicode arguments[BUG] 

### ISSUE THREAD

**Issue by Deshdeepak1** [pypa/setuptools#3268] opened 2022-04-14 18:01 UTC
### setuptools version

60.4.2

### Python version

3.9

### OS

Windows10

### Description

setup.py consolescripts can't take unicode command line arguments on windows, while the respective .py file can.

e.g. all_dl.py 

console_script in setup.py:
all-dl=all_dl:main

def main():
  print(sys.argv[1])

if __name__ == "__main__":
 main()

python all_dl.py एक परिचय

ouputs एक परिचय.

but 

all-dl एक परिचय.

outputs ??????

### Expected behavior

The latter output should be similar to former

### How to Reproduce

1. Write the small py file
2. make a console script for that file
3. pass unicode arg to py file and the exe file
4. See the difference

### Output

```console

```
1st case -  एक परिचय.
2nd case - ???????

**Comment by abravalheri** [comment] 2022-04-14 20:53
Hi @Deshdeepak1 thank you very much for reporting this.

Question, how are you creating the exe file? Are you installing your project with `pip install` and then trying to call the executable?

**Comment by Deshdeepak1** [comment] 2022-04-15 05:59
Yes the .exe file was created by pip install

**Comment by abravalheri** [comment] 2022-04-15 07:23
In this case, maybe it is worthy to file this issue against pip.

To keep things cross platform, the script wrappers are not included in the created wheel or sdist.

Instead, pip creates the script wrappers for console_scripts during the installation (with the help of distlib)[^1].

[^1]: Unless you are using the `-e` option .

**Comment by uranusjr** [comment] 2022-04-17 15:33
To correctly take input and print output of a given character range, you must use a console capable of receiving and emitting an encoding covering the character range, and have your application use that encoding. There are modern tools on Windows that can handle this correctly, but your environment may not.

The bottom line is, this is not a bug in pip (or setuptools, or distlib, or Python), but just how old Windows things do not handle non-ASCII well. You may have better luck finding help on a general Python Q&A forum, or a local user group (where people tend to have more experience dealing with the local language).

**Comment by abravalheri** [comment] 2022-04-17 16:27
Thank you very much @uranusjr for clarifying the problem.

I think I will go ahead and close this issue, since there isn't a direct action point.

**Closed** 2022-04-17 16:27 UTC
Labels: bug, Needs Triage
