### ISSUE TITLE
[BUG] The new version 70.0.0 creates the following exception when I execute my tool:Traceback (most recent call last):   File "PyInstaller/hooks/rthooks/pyi_rth_pkgres.py", line 158, in <module>   File "PyInstaller/hooks/rthooks/pyi_rth_pkgres.py", line 36, in _pyi_rthook   File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module   File "pkg_resources/__init__.py", line 77, in <module> ModuleNotFoundError: No module named 'pkg_resources.extern' [14522] Failed to execute script 'pyi_rth_pkgres' due to unhandled exception! I switch back to 69.5.1 for now.

### ISSUE THREAD

**Issue by kleve-ops** [pypa/setuptools#4407] opened 2024-05-30 22:15 UTC
### setuptools version

70.0.0

### Python version

3.11.1

### OS

sles12

### Description

The new version 70.0.0 creates the following exception when I execute my tool:Traceback (most recent call last):   File "PyInstaller/hooks/rthooks/pyi_rth_pkgres.py", line 158, in <module>   File "PyInstaller/hooks/rthooks/pyi_rth_pkgres.py", line 36, in _pyi_rthook   File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module   File "pkg_resources/__init__.py", line 77, in <module> ModuleNotFoundError: No module named 'pkg_resources.extern' [14522] Failed to execute script 'pyi_rth_pkgres' due to unhandled exception! I switch back to 69.5.1 for now.

### Expected behavior

Normal app start

### How to Reproduce

Run a single file app with was build via 70.0.0

### Output

```console
Traceback (most recent call last):
  File "PyInstaller/hooks/rthooks/pyi_rth_pkgres.py", line 158, in <module>
  File "PyInstaller/hooks/rthooks/pyi_rth_pkgres.py", line 36, in _pyi_rthook
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "pkg_resources/__init__.py", line 77, in <module>
ModuleNotFoundError: No module named 'pkg_resources.extern'
[14522] Failed to execute script 'pyi_rth_pkgres' due to unhandled exception!
```

**Comment by abravalheri** [comment] 2024-05-30 23:03
Hi @kleve-ops, this seems to be a duplicate of https://github.com/pypa/setuptools/issues/4374.

Please have a look at that thread to understand the root cause of the problem and the available solutions.

**Closed** 2024-05-30 23:04 UTC
Labels: bug, Needs Triage
