### ISSUE TITLE
Error: 'pyasn1' distribution was not found and is required by service-identity

### ISSUE THREAD

**Issue by cas--** [pypa/setuptools#1510] opened 2018-10-16 16:14 UTC
I think I have found the following an issue in setuptools when trying to install service_identity with `setup.py install`:

A minimal test case:
```
from setuptools import setup

setup(
    name='service_identity_test',
    install_requires=['service_identity'],
)
```

Run the install inside a new virtualenv. Trimmed the output to where it attempts to install `pyasn1` but instead reinstalls `pyasn1-modules`:

```  
(.venv) $ pip list
Package    Version
---------- -------
pip        18.1   
setuptools 40.4.3 
wheel      0.32.1 

(.venv) $ python setup.py install

...
Searching for pyasn1
Downloading https://files.pythonhosted.org/packages/37/33/74ebdc52be534e683dc91faf263931bc00ae05c6073909fde53999088541/pyasn1-modules-0.2.2.tar.gz#sha256=a0cf3e1842e7c60fde97cb22d275eb6f9524f5c5250489e292529de841417547
Best match: pyasn1 modules-0.2.2
Processing pyasn1-modules-0.2.2.tar.gz
Writing /tmp/easy_install-2PinDy/pyasn1-modules-0.2.2/setup.cfg
Running pyasn1-modules-0.2.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-2PinDy/pyasn1-modules-0.2.2/egg-dist-tmp-X3VWf7
no previously-included directories found matching 'doc/build'
Removing /.venv/lib/python2.7/site-packages/pyasn1_modules-0.2.2-py2.7.egg
Moving pyasn1_modules-0.2.2-py2.7.egg to /.venv/lib/python2.7/site-packages
pyasn1-modules 0.2.2 is already the active version in easy-install.pth

Installed /.venv/lib/python2.7/site-packages/pyasn1_modules-0.2.2-py2.7.egg
error: The 'pyasn1' distribution was not found and is required by service-identity
```

Using `pip install service_identity` there is no issue.

## Workaround
The workaround is to explicitly add `pyasn1` to `install_requires`:

    install_requires=['service_identity', 'pyasn1'],

**Comment by benoit-pierre** [comment] 2018-10-16 16:19
This is a duplicate of #498.

**Closed by benoit-pierre** 2018-10-16 16:19 UTC
