### ISSUE TITLE
[BUG] module 'importlib_metadata' has no attribute 'EntryPoints'

### ISSUE THREAD

**Issue by daniel-larraz** [pypa/setuptools#4490] opened 2024-07-18 17:35 UTC
### setuptools version

setuptools == {71.0.0, 71.0.1, 71.0.2, 71.0.3}

### Python version

Python 3.8

### OS

Ubuntu 20.04

### Description

When running `python setup.py build_ext --inplace`, I get the following error:
```
Traceback (most recent call last):
    File "setup.py", line 23, in <module>
      from setuptools import setup
    File "/home/runner/work/cvc5/cvc5/build-shared/venv-3.8.10/lib/python3.8/site-packages/setuptools/__init__.py", line 19, in <module>
      from .dist import Distribution
    File "/home/runner/work/cvc5/cvc5/build-shared/venv-3.8.10/lib/python3.8/site-packages/setuptools/dist.py", line 30, in <module>
      from . import _entry_points
    File "/home/runner/work/cvc5/cvc5/build-shared/venv-3.8.10/lib/python3.8/site-packages/setuptools/_entry_points.py", line 44, in <module>
      def validate(eps: metadata.EntryPoints):
  AttributeError: module 'importlib_metadata' has no attribute 'EntryPoints'
```
Using setuptools < 71.0.0, or installing the latest version of `importlib_metadata` together setuptools >= 71.0.0 solves the issue.

### Expected behavior

Setuptools doesn't fail.

### How to Reproduce

I was not able to quickly find a minimal reproducer. I will try to find one.

### Output

See description

**Comment by rcramblit** [comment] 2024-07-18 17:55
This seems like an issue for both Python 3.8 and 3.9. `EntryPoints` was added to `importlib.resources` in Python 3.10.

**Comment by daniel-larraz** [comment] 2024-07-18 18:02
@rcramblit You are right. It's Python 3.8. Sorry the confusion.

**Comment by jaraco** [comment] 2024-07-18 22:54
This issue is a duplicate of #4478. I'll pin it for now for better visibility.

**Closed by jaraco** 2024-07-18 22:54 UTC
Labels: bug, Needs Triage
