### ISSUE TITLE
[BUG] pkg_resources.DistInfoDistribution has incorrect project_name and cannot compare keys between Distribution and Requirement

### ISSUE THREAD

**Issue by f3flight** [pypa/setuptools#4250] opened 2024-03-01 22:24 UTC
### setuptools version

latest

### Python version

latest

### OS

CentOS7

### Description

I've found that pkg_resources.DistInfoDistribution has incorrect project_name for projects which have a dot `.` in their name, and that in this case we cannot compare keys between Distribution and Requirement.

One example of where this causes issues is a tool called `pipdeptree`, which prints a tree of dependencies:
```
(repro_distinfo_issue) [ ~/temp ]$ pipdeptree -f
example_package @ file:///home/user/temp
  flufl.lock
flufl.lock==8.0.2
  atpublic==4.0
  psutil==5.9.8
pip==22.3.1
pipdeptree==2.15.1
setuptools==65.5.0
```
In this case, it cannot align dist with requirement, causing the second line to have no `==version` next to `flufl.lock`.

So here I have two asks:
1 - fix `DistInfoDistribution` project name, which is not read from METADATA / PKG-INFO, but recovered from folder name, losing '.' in the process (gets converted to `_` when installing the package then to `-` when `DistInfoDistribution` object is created). I.e. `safe_name` must be applied over METADATA, not over folder name -> regex (`EGG_NAME`)-> assumed project name.

2 - align keys to make distribution and requirement keys comparable.
I think that since ultimately requirements are resolved via index and passed through pep503 regex, it would make sense to at least have ".key" also pep503 normalized, so that requirement "flufl.lock" = requirement "flufl-lock", and so that distribution key can be matched with them too.

Either change would, I think, fix `pipdeptree`, but it would be better to do both. Then project name would be "flufl.lock" while key would be "flufl-lock" for both Requirement and Distribution objects. 

### Expected behavior

`DistInfoDistribution.project_name == "flufl.lock"`
`DistInfoDistribution.key == Requirement.key`

### How to Reproduce

See console

### Output

```console
[ ~/temp ]$ python -m venv repro_distinfo_issue
[ ~/temp ]$ . repro_distinfo_issue/bin/activate
(repro_distinfo_issue) [ ~/temp ]$ pip install flufl.lock
Collecting flufl.lock
  Downloading flufl_lock-8.0.2-py3-none-any.whl (11 kB)
Collecting atpublic
  Downloading atpublic-4.0-py3-none-any.whl (4.9 kB)
Collecting psutil
  Downloading psutil-5.9.8-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (288 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.2/288.2 kB 1.9 MB/s eta 0:00:00
Installing collected packages: psutil, atpublic, flufl.lock
Successfully installed atpublic-4.0 flufl.lock-8.0.2 psutil-5.9.8

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
(repro_distinfo_issue) [ ~/temp ]$ python
Python 3.11.1 (main, Feb 22 2024, 22:53:22) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pkg_resources import DistInfoDistribution
>>> d = DistInfoDistribution.from_location('/home/user/temp/repro_distinfo_issue/lib/python3.11/site-packages/flufl_lock-8.0.2.dist-info', 'flufl_lock-8.0.2.dist-info')
>>> d.project_name
'flufl-lock'
>>> d.key
'flufl-lock'
```
The package name is incorrectly set as "flufl-lock". The key is the same. Why it matters, besides just being misleading?
Because one may wrongly assume that they can connect `DistInfoDistribution` with `Requirement` by comparing `.key` and this way building the dependency tree. However, `Requirement` class preserves `.` in the package name, resulting in:
```
>>> from pkg_resources import Requirement
>>> r = Requirement.parse('flufl.lock')
>>> r.project_name
'flufl.lock'
>>> r.key
'flufl.lock'
```

It is worth noting that the issue surfaced with the release of `flufl.lock` version 8, which switched from `pdm-pep517` 1.0.4 build backend to `pdm-backend` 2.1.4.
![image](https://github.com/pypa/setuptools/assets/6680260/61aa8001-1319-47f1-9261-9d4152315d45)

@warsaw FYI

**Comment by gaborbernat** [comment] 2024-03-01 23:38
> The package name is incorrectly set as "flufl-lock". The key is the same. Why it matters, besides just being misleading?

The normalized name is correct per https://packaging.python.org/en/latest/specifications/name-normalization/#name-normalization

**Comment by f3flight** [comment] 2024-03-02 00:02
> The normalized name is correct per

`pkg_resources` does not use pep503 normalization, so this reference is not truly valid. It uses a different regex which allows dots to remain - https://github.com/pypa/setuptools/blob/main/pkg_resources/__init__.py#L1372. based on this regex, the correct normalized name for this package should be `flufl.lock`. However since it is not read from metadata, but folder name instead, it is mutated. Now, I don't know if there's a "standard" to .dist-info folder naming. If there is, we need to check if "a_b-ver.dist-info" is a valid name for "a.b==ver" package. If not, then pdm devs should fix their build backend (`pdm-pep517` did not have this behavior). If it is not regulated, however, then it might be more valid to make `pkg_resources` use pep503 for keys and extract real name from metadata.

**Comment by abravalheri** [comment] 2024-03-02 18:23
Hi @f3flight , please note that `pkg_resources` is mostly maintained for backwards compatibility.

The recommendation is to use `importlib.metadata`/`importlib.resources` (and / or their backport) instead.

Can your use case be solved by migrating to `importlib.metadata`?

---

On a side note, please note that the [documentation](https://setuptools.pypa.io/en/latest/pkg_resources.html#distribution-attributes) mentions that `project_name` is preprocessed:

> project_name
>
> A string, naming the project that this distribution is for. Project names are defined by a project’s setup script, and they are used to identify projects on PyPI. When a `Distribution` is constructed, the `project_name` argument is passed through the `safe_name()` utility function to filter out any unacceptable characters.

With that in mind, the implementation seems to be working as expected... And because `pkg_resources` is in "maintenance mode", it makes sense to avoid changes at this stage.

**Comment by f3flight** [comment] 2024-03-03 02:54
I solved the issue in pipdeptree for now - https://github.com/tox-dev/pipdeptree/pull/325, feel free to close,I understand that implications and that this is on maintenance mode, and yes, It seems that using `importlib.metadata.packages_distributions()` https://docs.python.org/3/library/importlib.metadata.html#mapping-import-to-distribution-packages can provide a list of available packages with true names, and from there it may be possible to use `metadata` to extract requirements, though `pkg_resources` seems to be still needed to parse requirements.

**Comment by abravalheri** [comment] 2024-03-04 11:19
Hi @f3flight, thank you for the feedback. I am glad that you managed to work around this limitation of `pipdeptree`.

I think I will close this issue for now, since the documentation mentions that `project_name` is pre-processed during the construction of the object, so at first glance the behaviour seems to be intended and not a bug.

**Closed by abravalheri** 2024-03-04 11:19 UTC
Labels: bug, Needs Triage
