### ISSUE TITLE
[BUG] FileNotFoundError jaraco/text/Lorem ipsum.txt when importing pkg_resources

### ISSUE THREAD

**Issue by thinhha** [pypa/setuptools#3072] opened 2022-02-02 14:07 UTC
### setuptools version

setuptools==60.7.0

### Python version

3.9

### OS

Debian 11

### Description

FileNotFoundError when importing `pkg_resources`

```
  File "/home/aaa/env/lib/python3.9/site-packages/google/api_core/client_info.py", line 23, in <module>
    import pkg_resources
  File "/tmp/aaa/pypi__setuptools/pkg_resources/__init__.py", line 74, in <module>
    from pkg_resources.extern.jaraco.text import (
  File "/tmp/aaa/pypi__setuptools/pkg_resources/_vendor/jaraco/text/__init__.py", line 227, in <module>
    lorem_ipsum: str = files(__name__).joinpath('Lorem ipsum.txt').read_text()
  File "/home/aaa/.pyenv/versions/3.9.7/lib/python3.9/pathlib.py", line 1266, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/home/aaa/.pyenv/versions/3.9.7/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/home/aaa/.pyenv/versions/3.9.7/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/aaa/py_deps/pypi__setuptools/pkg_resources/_vendor/jaraco/text/Lorem ipsum.txt'
```

### Expected behavior

Pinning setuptools==60.6.0 in requirements.txt works fine. This issue started with setuptools==60.7.0.

### How to Reproduce

Using Bazel and [rules_python](https://github.com/bazelbuild/rules_python), build a zip executable using: 
```
bazel build //<target> --output_groups=python_zip_file
python3 bazel-bin/<target>/<target>.zip 
```

### Output

```console
...
  File "/home/aaa/env/lib/python3.9/site-packages/google/api_core/client_info.py", line 23, in <module>
    import pkg_resources
  File "/tmp/aaa/pypi__setuptools/pkg_resources/__init__.py", line 74, in <module>
    from pkg_resources.extern.jaraco.text import (
  File "/tmp/aaa/pypi__setuptools/pkg_resources/_vendor/jaraco/text/__init__.py", line 227, in <module>
    lorem_ipsum: str = files(__name__).joinpath('Lorem ipsum.txt').read_text()
  File "/home/aaa/.pyenv/versions/3.9.7/lib/python3.9/pathlib.py", line 1266, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/home/aaa/.pyenv/versions/3.9.7/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/home/aaa/.pyenv/versions/3.9.7/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/aaa/py_deps/pypi__setuptools/pkg_resources/_vendor/jaraco/text/Lorem ipsum.txt'
```

**Comment by abravalheri** [comment] 2022-02-02 14:22
Hi @thinhha thank you very much for opening the issue.

I just double checked the `wheel` published on PyPI, and it seems to include the file:

![image](https://user-images.githubusercontent.com/320755/152170344-1a518235-4e61-4438-81a1-76f98f3f12f0.png)

If I build setuptools locally with `python -m build`, I am also able to find the file.

I also double checked in setuptools' own configuration file, and this file is being included in the `package_data` option:

https://github.com/pypa/setuptools/blob/763cf01ef7df80a5d0b64ec69427336a9cb419b8/setup.py#L16

which, according to [this table](https://github.com/abravalheri/experiment-setuptools-package-data#results-for-setuptools6060), indicates that they should be included in the distribution.

Any chance this problem is being caused by the tool you are using to build a zip executable?

Can you reproduce this issue, without using `bazel`?

**Comment by edward-watson-oxb** [comment] 2022-02-02 19:51
This is linked to the issue that Bazel [does not play nicely with spaces in file names](https://github.com/bazelbuild/bazel/issues/4327).

I've just been bitten with this whilst using a Poetry rule from Bazel, with no way to pin the `setuptools` version that I can find right now. So much for my deterministic build!

I've confirmed that renaming the file to use an underscore allows Bazel to symlink it into the runfiles just fine.

**Comment by abravalheri** [comment] 2022-02-02 20:37
Thank you very much for the investigation @edward-watson-oxb !

Would you (or any other member of the community) be interested in providing a PR with the name change to https://github.com/jaraco/jaraco.text? (As a temporary workaround for the bazel limitation)

I think that if the reasons are well explained, the upstream project has good chances of accepting it... Otherwise I am afraid that the fix will have to come from the bazel side...

**Comment by jaraco** [comment] 2022-02-03 00:05
Actually, I'll be unlikely to accept a change to rename the file without spaces. Setuptools itself has files that have spaces in the name. See #134. Can you look into how it is that bazel is able to build setuptools<60.7 without the issue?

**Comment by jaraco** [comment] 2022-02-03 00:18
One thing that makes this issue particularly problemmatic is that the behavior is invoked on import, and it's behavior that Setuptools doesn't even need. I'm slightly tempted to move the functionality to another library entirely. It just feels like a whole lot of overhead to create an entirely new project to host functionality to be shared by pkg_resources and setuptools.

**Comment by jaraco** [comment] 2022-02-03 00:19
I may consider patching jaraco.text when it's vendored to eliminate the file or rename it.

**Comment by jaraco** [comment] 2022-02-03 01:17
I looked into [making that property lazy-loaded](https://github.com/jaraco/jaraco.text/tree/feature/lazy-property), but that only led me to a [deficiency in doctests](https://bugs.python.org/issue46619). I'd probably have just inlined those two lines of text, except Python linters are hostile to long lines (hobgoblins of our collective minds), and I want to cleanly present the content (without introducing intervening characters to accommodate Python).

**Comment by edge0701** [comment] 2022-02-03 09:43
> Can you look into how it is that bazel is able to build setuptools<60.7 without the issue?

As far as I can tell, the manifest file is [only used on Windows](https://github.com/pypa/setuptools/blob/763cf01ef7df80a5d0b64ec69427336a9cb419b8/setuptools/command/easy_install.py#L2237). If Bazel is running on a Linux host, there is no attempt for the file to loaded.

In some cases of Bazel rules, they [ignore these files entirely](https://github.com/martinxsliu/rules_python_poetry/blob/5676129f4deb4a7668751f79022fd616b8203c59/internal/toolchain/toolchain.bzl#L12).

And in others, I would imagine they have to just manually patch packages when they are downloaded - but I have no public examples of this.

**Comment by rahul-theorem** [comment] 2023-10-19 04:07
@jaraco would you be willing to reopen this? This is breaking our usage of a package that depends on `cherrypy` (which in turn pulls in `jaraco.collections` & `jaraco.text`) in our Bazel build, and we'd love to figure out if there's a way to move forward.

**Comment by robert-moyai** [comment] 2024-08-27 13:14
> This is linked to the issue that Bazel [does not play nicely with spaces in file names](https://github.com/bazelbuild/bazel/issues/4327).
> 
> I've just been bitten with this whilst using a Poetry rule from Bazel, with no way to pin the `setuptools` version that I can find right now. So much for my deterministic build!
> 
> I've confirmed that renaming the file to use an underscore allows Bazel to symlink it into the runfiles just fine.

How or where did you rename the file as a hotfix @edward-watson-oxb?

**Comment by jaraco** [comment] 2024-09-24 20:19
Re-opening as #4457 re-introduced the offending behavior.

**Comment by jaraco** [comment] 2024-09-24 20:25
> try and apply a patch to the dependency using Bazel to make this more permanent

Indeed. By applying the workaround in #3077, it masked the flaw in Bazel and left developers there complacent to the concern. Now that Setuptools no longer maintains patched copies of dependencies, it's no longer feasible for the vendored copies to be altered to address downstream issues. Instead, the best recommendation would be for affected environments (Bazel) to patch the offending project (jaraco.text) directly (either vendored or unvendored, and preferably the latter), or even better, implement support for valid filenames.

See #4487.

**Closed by jaraco** 2024-09-24 20:25 UTC
Labels: Needs Repro, Waiting User Feedback
