### ISSUE TITLE
[BUG] pkg_resources old version of pyparsing breaks pip in 3.10.0 and 3.10.1 on Linux

### ISSUE THREAD

**Issue by ptmcg** [pypa/setuptools#2988] opened 2021-12-31 00:35 UTC
### setuptools version

setuptools===60.2.0

### Python version

Python 3.10

### OS

Ubuntu 18.04

### Additional environment information

Installed python 3.10 on Ubuntu using "sudo apt install python3.10"

### Description

After installing Python 3.10, running "python3.10 -m pip" gives this error.

```
$ python3.10 -m pip
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 22, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 73, in <module>
    vendored("pkg_resources")
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 33, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 77, in <module>
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/extern/__init__.py", line 43, in load_module
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/pyparsing.py", line 943, in <module>

AttributeError: module 'collections' has no attribute 'MutableMapping'
```

After looking at the contents of the pkg_resources /_vendor/ directory, I see that pyparsing is at version 2.1.10.

I tried upgrading setuptools by downloading the source package for 60.2.0 and running "sudo python3.10 setup.py install". This installation appeared to succeed, but I still have the same error when doing "python3.10 -m pip".

How can I replace the old vendored pyparsing with a new py3.10-compatible version? (2.2.1 would do the trick).

### Expected behavior

No error

### How to Reproduce

<install on Ubuntu - I believe other Linuxes also have issues>
$ python3.10 -m pip

### Output

```console
pmcguire@pmcguire-py:/tmp/setuptools-60.2.0$ python3.10 -m pip
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 22, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 73, in <module>
    vendored("pkg_resources")
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 33, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 77, in <module>
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/extern/__init__.py", line 43, in load_module
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/pyparsing.py", line 943, in <module>

AttributeError: module 'collections' has no attribute 'MutableMapping'
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ptmcg** [comment] 2021-12-31 00:35
Let me know if there is anything I can do to help with this.

**Comment by ptmcg** [comment] 2021-12-31 14:20
Further testing:
- not a problem on macOS 12.1
- not a problem on Windows 10

**Comment by Niccolum** [comment] 2022-01-08 10:15
Also created issue on pip repo

https://github.com/pypa/pip/issues/10770

**Comment by pradyunsg** [comment] 2022-01-08 10:45
This is likely a bug with Debian's debundling of pip and how it handles virtualenv. See https://gist.github.com/tiran/2dec9e03c6f901814f6d1e8dad09528e for some more details on this.

The best folks to reach out to, are the maintainers for Debian's Python.

**Comment by Niccolum** [comment] 2022-01-08 13:34
According previous issue, next steps solve problem:

- add deadsnake repo (default or nightly)
- `sudo apt install python3.10`
- `python3.10 -m pip`
- `git clone git@github.com:pypa/setuptools.git && cd setuptools && python3.10 setup.py install`
- `sudo apt install python3.10-distutils`
- `curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10`

Don't know, is it needed to clone setuptools and installed this locally for solving problem. Just my steps.
@ptmcg

**Comment by ptmcg** [comment] 2022-01-08 20:55
I had to change the git clone line to:

    git clone https://github.com/pypa/setuptools.git && cd setuptools && sudo python3.10 setup.py install

But otherwise, this took care of things, thanks!!!

**Comment by jaraco** [comment] 2022-01-08 21:31
FYI, I would not invoke 'setup.py install'. Instead, use an installer like pip to install... or not install setuptools at all if you don't need it.

This issue is a duplicate of #1401.

**Closed by jaraco** 2022-01-08 21:31 UTC
Labels: bug, Needs Triage

**Comment by ptmcg** [comment] 2022-01-08 21:35
Jaraco - the problem is that pip is broken, otherwise I would do so.
Thanks for chiming in, though - I'll take all the help I can get!

**Comment by jaraco** [comment] 2022-01-08 22:25
I created this dockerfile to bootstrap pip:

```Dockerfile
FROM ubuntu:18.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt upgrade -y
RUN apt install -y software-properties-common
RUN apt-add-repository -y ppa:deadsnakes
RUN apt update
RUN apt install -y build-essential curl git python3.10 python3.10-distutils
RUN curl -Ss https://bootstrap.pypa.io/get-pip.py | python3.10
RUN python3.10 -m pip install path
```

And it runs to completion. From there, you can pip install setuptools. Maybe that helps?

If I leave out `python3.10-distutils`, then the pip invocation fails when `distutils.cmd` doesn't exist (different error than reported above). That seems to coincide with the answer in the pip issue.

In any case, hope that helps.

**Comment by dennlinger** [comment] 2022-01-27 10:14
FWIW, trying to run `sudo apt-add-repository -y ppa:deadsnakes` causes another issue for me:

```python
Traceback (most recent call last):
  File "/usr/bin/apt-add-repository", line 12, in <module>
    from softwareproperties.SoftwareProperties import SoftwareProperties, shortcut_handler
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 67, in <module>
    from gi.repository import Gio
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3/dist-packages/gi/__init__.py)
```
