### ISSUE TITLE
[Docs] Quickstart: missing contents for "Resources on Python packaging"

### ISSUE THREAD

**Issue by ananthp** [pypa/setuptools#2674] opened 2021-05-16 07:41 UTC
### Summary

Quickstart guide has a section titled [Resources on Python packaging](https://github.com/pypa/setuptools/blob/main/docs/userguide/quickstart.rst#resources-on-python-packaging). However, it doesn't point to any resources. 

### Additional Information

> Packaging in Python is hard. Here we provide a list of links for those that want to learn more.

It would be a good idea to provide those useful links.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by SnoopJeDi** [comment] 2021-05-17 19:19
Just came here to report the same. Looks like the [commit in question](https://github.com/pypa/setuptools/commit/b2af2ea980386f86afe5e104e7fe1bf047ac1df9) was intended to be a WIP, but got merged in an incomplete state. Not sure what the original author intended, but the [PyPA packaging overview](https://packaging.python.org/overview/) would be a natural choice for this section.

**Comment by phetdam** [comment] 2021-08-21 04:31
Me too. Other helpful links, especially since using `distutils` still seems to be the way to build C/C++ extensions, would be the official Python [Building C and C++ Extensions](https://docs.python.org/3/extending/building.html) docs and the supplementary [Building C and C++ Extensions on Windows](https://docs.python.org/3/extending/windows.html).

**Comment by abravalheri** [comment] 2022-01-05 20:46
Hello @ananthp, @SnoopJeDi and @phetdam, thank you very much for bringing this issue up...

It seems that you guys have some ideas of useful links to include there, any chance one of you is interested in providing a PR? That would be really helpful!

**Comment by ananthp** [comment] 2022-01-07 12:44
As [Python Packaging User Guide](https://packaging.python.org/en/latest/) is supposedly officially curated list of resources, and hopefully gets updated as things evolve, just mentioning about it here would be sufficient. I'll do that.

**Closed** 2022-01-07 18:32 UTC
Labels: Needs Triage, documentation
