### ISSUE TITLE
Docs are a bit out of date

### ISSUE THREAD

**Issue by ionelmc** [pypa/setuptools#603] opened 2016-06-03 14:24 UTC
Just noticed that the docs don't have the latest changelog entries: https://pythonhosted.org/setuptools/history.html

**Comment by jaraco** [comment] 2016-06-03 17:24
Acknowledging that you reported this first, I'm going to mark this duplicate of the ticket I filed on the same issue: #604.

**Closed by jaraco** 2016-06-03 17:24 UTC
