### ISSUE TITLE
setuptools finds 'Flask WTF' to be the best match for a requires on 'flask'

### ISSUE THREAD

**Issue by jeremycline** [pypa/setuptools#1013] opened 2017-04-13 20:17 UTC
I have a project and it depends on, among other things, Flask and Flask-WTF. However, ``python setup.py install`` doesn't work. I'm not _sure_ if this is a setuptools issue or Flask-WTF issue, but I thought I'd bring it up here first. Here's a reproducing setup.py:
```
#!/usr/bin/env python

"""
Setup script
"""

from setuptools import setup, find_packages


setup(
    name='Test',
    description='This is a test.',
    version='0.1.0',
    author='Jeremy',
    license='GPLv2+',
    packages=find_packages(),
    install_requires=['flask', 'flask-WTF'],
)
```

Then just try to install it:
```
python setup.py install
running install
running bdist_egg
running egg_info
creating Test.egg-info
writing dependency_links to Test.egg-info/dependency_links.txt
writing requirements to Test.egg-info/requires.txt
writing top-level names to Test.egg-info/top_level.txt
writing Test.egg-info/PKG-INFO
writing manifest file 'Test.egg-info/SOURCES.txt'
reading manifest file 'Test.egg-info/SOURCES.txt'
writing manifest file 'Test.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying Test.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Test.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Test.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Test.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Test.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/Test-0.1.0-py3.5.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing Test-0.1.0-py3.5.egg
Copying Test-0.1.0-py3.5.egg to /home/jcline/.virtualenvs/test4/lib/python3.5/site-packages
Adding Test 0.1.0 to easy-install.pth file

Installed /home/jcline/.virtualenvs/test4/lib/python3.5/site-packages/Test-0.1.0-py3.5.egg
Processing dependencies for Test==0.1.0
Searching for flask-WTF
Reading https://pypi.python.org/simple/flask-WTF/
Downloading https://pypi.python.org/packages/ba/15/00a9693180f214225a2c0b1bb9077f3b0b21f2e86522cbba22e8ad6e570c/Flask-WTF-0.14.2.tar.gz#md5=586f50f233926cade42e3d744aca3e8f
Best match: Flask-WTF 0.14.2
Processing Flask-WTF-0.14.2.tar.gz
Writing /tmp/easy_install-gel4w07x/Flask-WTF-0.14.2/setup.cfg
Running Flask-WTF-0.14.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-gel4w07x/Flask-WTF-0.14.2/egg-dist-tmp-0d48lmv_
warning: no previously-included files matching '*.pyc' found under directory 'tests'
warning: no previously-included files matching '*.pyo' found under directory 'tests'
no previously-included directories found matching 'docs/_build'
warning: no previously-included files found matching 'docs/_themes/.git*'
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'docs'
creating /home/jcline/.virtualenvs/test4/lib/python3.5/site-packages/Flask_WTF-0.14.2-py3.5.egg
Extracting Flask_WTF-0.14.2-py3.5.egg to /home/jcline/.virtualenvs/test4/lib/python3.5/site-packages
Adding Flask-WTF 0.14.2 to easy-install.pth file

Installed /home/jcline/.virtualenvs/test4/lib/python3.5/site-packages/Flask_WTF-0.14.2-py3.5.egg
Searching for flask
Downloading https://pypi.python.org/packages/ba/15/00a9693180f214225a2c0b1bb9077f3b0b21f2e86522cbba22e8ad6e570c/Flask-WTF-0.14.2.tar.gz#md5=586f50f233926cade42e3d744aca3e8f
Best match: Flask WTF-0.14.2
Processing Flask-WTF-0.14.2.tar.gz
Writing /tmp/easy_install-73yqdlk5/Flask-WTF-0.14.2/setup.cfg
Running Flask-WTF-0.14.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-73yqdlk5/Flask-WTF-0.14.2/egg-dist-tmp-lzch3t_m
warning: no previously-included files matching '*.pyc' found under directory 'tests'
warning: no previously-included files matching '*.pyo' found under directory 'tests'
no previously-included directories found matching 'docs/_build'
warning: no previously-included files found matching 'docs/_themes/.git*'
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'docs'
removing '/home/jcline/.virtualenvs/test4/lib/python3.5/site-packages/Flask_WTF-0.14.2-py3.5.egg' (and everything under it)
creating /home/jcline/.virtualenvs/test4/lib/python3.5/site-packages/Flask_WTF-0.14.2-py3.5.egg
Extracting Flask_WTF-0.14.2-py3.5.egg to /home/jcline/.virtualenvs/test4/lib/python3.5/site-packages
Flask-WTF 0.14.2 is already the active version in easy-install.pth

Installed /home/jcline/.virtualenvs/test4/lib/python3.5/site-packages/Flask_WTF-0.14.2-py3.5.egg
error: The 'flask' distribution was not found and is required by flask-WTF, Test
```

**Comment by jaraco** [comment] 2017-04-14 04:06
Duplicate of #196

**Closed by jaraco** 2017-04-14 04:06 UTC
