### ISSUE TITLE
cannot bootstrap any more using ez_setup.py, 404 for setuptools

### ISSUE THREAD

**Issue by binhex** [pypa/setuptools#562] opened 2016-04-26 12:09 UTC
This was working but in the last 24 hours has stopped working, looks like somebody has changed the location of setuptools :-

C:\temp\>python ez_setup.py

returns the following:-

```
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-20.10.1.zip
test
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At line:1 char:106
+ ... redentials; (new-object System.Net.WebClient).DownloadFile("https://p ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Traceback (most recent call last):
  File "ez_setup.py", line 415, in <module>
    sys.exit(main())
  File "ez_setup.py", line 411, in main
    archive = download_setuptools(**_download_args(options))
  File "ez_setup.py", line 336, in download_setuptools
    downloader(url, saveto)
  File "ez_setup.py", line 236, in download_file_powershell
    _clean_check(cmd, target)
  File "ez_setup.py", line 210, in _clean_check
    subprocess.check_call(cmd)
  File "D:\Program Files\Apps\Python\lib\subprocess.py", line 488, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['powershell', '-Command', '[System.Net.WebRequest]::DefaultWebProxy.Credentials = [System.Net.CredentialCache]::DefaultCredentials; (new-object System.Net.WebClient).DownloadFile("https://pypi.python.org/packages/source/s/setuptools/setuptools-20.10.1.zip", "C:\\temo33\\setuptools-20.10.1.zip")']' returned non-zero exit status 1
```

**Comment by jaraco** [comment] 2016-04-26 13:46
This appears to be a duplicate of #557, but answers a question I had not yet asked - does this issue affect non-Unix systems as well.

**Closed by jaraco** 2016-04-26 13:46 UTC
Labels: duplicate

**Comment by jaraco** [comment] 2016-04-26 14:22
I've confirmed the new script also works on Windows. Ensure you have the latest ez_setup.py script and when you run it, you should see 'pypi.io' in the 'Downloading'. If you don't see that, you need to ensure you don't already have setuptools*.zip in the current directory and that you have the latest bootstrap script:

```
C:\Users\jaraco> python ez_setup.py
﻿Downloading https://pypi.io/packages/source/s/setuptools/setuptools-20.10.1.zip
```

**Comment by binhex** [comment] 2016-04-27 10:17
thankyou jaraco.
