### ISSUE TITLE
[BUG] Modifying setuptools.command.build.build.sub_commands has no effect

### ISSUE THREAD

**Issue by bdrung** [pypa/setuptools#4040] opened 2023-09-06 11:48 UTC
### setuptools version

68.1.2-1

### Python version

3.11.4

### OS

Debian unstable / Ubuntu 23.10 (mantic)

### Description

The [setuptools-gettext 0.1.4 plugin](https://github.com/breezy-team/setuptools-gettext/blob/v0.1.4/setuptools_gettext/__init__.py) uses following mechanism to add its subcommand to setuptools:

```python3
from distutils.command.clean import clean
from distutils.command.install import install
from setuptools.command.build import build

build.sub_commands.append(('build_mo', has_gettext))
clean.sub_commands.append(('clean_mo', has_gettext))
install.sub_commands.append(('install_mo', has_gettext))
```

Apport tries to use this plug-in and the Debian packaging is running something like this:
```
python3 -m build --skip-dependency-check --no-isolation --wheel
```

The build step `build_mo` is not executed (but `install_mo` is).

### Expected behavior

There should be a way that plugin could use to register new build commands.

### How to Reproduce

[example setuptools extension plugin](https://github.com/bdrung/setuptools-skunkworks) contains a stripped down plugin. The [build-not-working](https://github.com/bdrung/setuptools-skunkworks/tree/build-not-working) branch demonstrates the failing behavior.

Install this plugin, e.g. by building and installing the Debian package:
```
debuild --no-lintian -b && sudo debi
```

Then run `python3 -m build --skip-dependency-check --no-isolation --wheel` on any project.

### Output

```console
$ python3 -m build --skip-dependency-check --no-isolation --wheel
* Building wheel...
SKUNKWORKS: finalize_distribution_options(<setuptools.dist.Distribution object at 0x7ffaa0270950>) called.
running bdist_wheel
running build
running build_py
running egg_info
writing setuptools_skunkworks.egg-info/PKG-INFO
writing dependency_links to setuptools_skunkworks.egg-info/dependency_links.txt
writing entry points to setuptools_skunkworks.egg-info/entry_points.txt
writing top-level names to setuptools_skunkworks.egg-info/top_level.txt
reading manifest file 'setuptools_skunkworks.egg-info/SOURCES.txt'
writing manifest file 'setuptools_skunkworks.egg-info/SOURCES.txt'
installing to build/bdist.linux-x86_64/wheel
running install
SKUNKWORKS: has_skunkworks_units(<setuptools.command.install.install object at 0x7ffa9f420810>) called.***
running install_lib
creating build/bdist.linux-x86_64/wheel
copying build/lib/setuptools_skunkworks.py -> build/bdist.linux-x86_64/wheel
running install_egg_info
Copying setuptools_skunkworks.egg-info to build/bdist.linux-x86_64/wheel/setuptools_skunkworks-0.1.egg-info
running install_scripts
running install_skunkworks
SKUNKWORKS: install_skunkworks.initialize_options() called.
SKUNKWORKS: install_skunkworks.finalize_options() called.
SKUNKWORKS: install_skunkworks.run() called.
creating build/bdist.linux-x86_64/wheel/setuptools_skunkworks-0.1.dist-info/WHEEL
creating '[...]/dist/.tmp-cnmmi8dt/setuptools_skunkworks-0.1-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'setuptools_skunkworks.py'
adding 'setuptools_skunkworks-0.1.dist-info/METADATA'
adding 'setuptools_skunkworks-0.1.dist-info/WHEEL'
adding 'setuptools_skunkworks-0.1.dist-info/entry_points.txt'
adding 'setuptools_skunkworks-0.1.dist-info/top_level.txt'
adding 'setuptools_skunkworks-0.1.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Successfully built setuptools_skunkworks-0.1-py3-none-any.whl
```

**Comment by abravalheri** [comment] 2023-09-06 12:34
Hi @bdrung please note that if you define `entry-points` in your `pyproject.toml` they are only going to be available for setuptools to use/discover ***after*** you install your project.

That works well if you have a plugin in your `[build-system] requires = [...]`, but if you are trying to use code in CWD to customize the way CWD itself is build, I don't think that will work.
For that case you have to specifically set `cmdclass` parameter in `setup.py`.

**Comment by abravalheri** [comment] 2023-09-06 12:51
Also note that since running `python setup.py ...` directly is deprecated defining `clean` and `install` sub-commands might not have the effect you expect.

`clean` is very likely to not be called at all, and `install` is actually going to be called by `bdist_wheel` (implemented in the `pypa/wheel` project, not in `setuptools`) to add files inside the `wheel` artifact during the build. It will not be called when the pre-built artifact is being installed in the end-user computer.

**Comment by bdrung** [comment] 2023-09-06 13:05
> please note that if you define `entry-points` in your `pyproject.toml` they are only going to be available for `setuptools`[1](#user-content-fn-1-29f7fa4a83ebec9a24d135d8dbae3715) to use/discover _**after**_ you install your project.

Self consuming the plugin is not needed. I updated the description to make it clearer that I am not trying to do that.

> Also note that since running `python setup.py ...` directly is deprecated, defining sub-commands for `clean` and `install` might not have the effect you expect.
> 
> `clean` is very likely to not be called at all, and `install` is actually going to be called by `bdist_wheel` (implemented in the `pypa/wheel` project, not in `setuptools`) to add files inside the `.whl` archive during the build. It will not be called when the pre-built archive is being installed in the end-user computer.

I am trying to make the plugin work nicely with `python3 -m build`. The reported issue can also be seen when using `python3 setup.py build` directly.

**Comment by abravalheri** [comment] 2023-09-06 13:07
Hi @bdrung, could you please confirm if `debuild --no-lintian -b && sudo debi` can be simply replaced with a `pip` install in non-debian systems?

**Comment by abravalheri** [comment] 2023-09-06 15:14
I am not sure...

In which directory does `debuild --no-lintian -b && sudo debi` installs the package? What is the output of `python3 -m site`?

Do you know what is the output of the following command after you run `debuild --no-lintian -b && sudo debi`?

```bash
python3 -c "from pprint import pprint; from importlib.metadata import entry_points; pprint(list(entry_points(group='distutils.commands')))"
```

How about:

```bash
python3 -c "from pprint import pprint; from setuptools.extern.importlib_metadata import entry_points; pprint(list(entry_points(group='distutils.commands')))"
```
?

**Comment by bdrung** [comment] 2023-09-06 15:24
I found the culprit: If you install `python3-distutils-extra` it breaks. Example:

```
schroot-wrapper -p python3-build,python3-distutils-extra,../python3-setuptools-skunkworks_0.1-1_all.deb -c unstable
cat <<EOF > pyproject.toml
[project]
name = "hello-world"
version = "0.41"
EOF
python3 -m build --skip-dependency-check --no-isolation --wheel
```

> In which directory does `debuild --no-lintian -b && sudo debi` installs the package?

It created a Debian package which is installed on the system:
```
dpkg -L python3-setuptools-skunkworks 
/.
/usr
/usr/lib
/usr/lib/python3
/usr/lib/python3/dist-packages
/usr/lib/python3/dist-packages/setuptools_skunkworks-0.1.dist-info
/usr/lib/python3/dist-packages/setuptools_skunkworks-0.1.dist-info/METADATA
/usr/lib/python3/dist-packages/setuptools_skunkworks-0.1.dist-info/RECORD
/usr/lib/python3/dist-packages/setuptools_skunkworks-0.1.dist-info/WHEEL
/usr/lib/python3/dist-packages/setuptools_skunkworks-0.1.dist-info/entry_points.txt
/usr/lib/python3/dist-packages/setuptools_skunkworks-0.1.dist-info/top_level.txt
/usr/lib/python3/dist-packages/setuptools_skunkworks.py
/usr/share
/usr/share/doc
/usr/share/doc/python3-setuptools-skunkworks
/usr/share/doc/python3-setuptools-skunkworks/changelog.Debian.gz
/usr/share/doc/python3-setuptools-skunkworks/copyright
```

> Do you know what is the output of the following command after you run `debuild --no-lintian -b && sudo debi`?
> 
> ```shell
> python3 -c "from pprint import pprint; from importlib.metadata import entry_points; pprint(list(entry_points(group='distutils.commands')))"
> ```
> 
> How about:
> 
> ```shell
> python3 -c "from pprint import pprint; from setuptools.extern.importlib_metadata import entry_points; pprint(list(entry_points(group='distutils.commands')))"
> ```
> 
> ?

In the unstable schroot mentioned above:
```
$ python3 -c "from pprint import pprint; from importlib.metadata import entry_points; pprint(list(entry_points(group='distutils.commands')))"
[EntryPoint(name='build_skunkworks', value='setuptools_skunkworks:build_skunkworks', group='distutils.commands'),
 EntryPoint(name='clean_skunkworks', value='setuptools_skunkworks:clean_skunkworks', group='distutils.commands'),
 EntryPoint(name='install_skunkworks', value='setuptools_skunkworks:install_skunkworks', group='distutils.commands'),
 EntryPoint(name='build', value='DistUtilsExtra.command.build_extra:build', group='distutils.commands'),
 EntryPoint(name='build_help', value='DistUtilsExtra.command.build_help:build_help', group='distutils.commands'),
 EntryPoint(name='build_i18n', value='DistUtilsExtra.command.build_i18n:build_i18n', group='distutils.commands'),
 EntryPoint(name='build_icons', value='DistUtilsExtra.command.build_icons:build_icons', group='distutils.commands'),
 EntryPoint(name='clean_i18n', value='DistUtilsExtra.command.clean_i18n:clean_i18n', group='distutils.commands'),
 EntryPoint(name='pylint', value='DistUtilsExtra.command.pylint:pylint', group='distutils.commands'),
 EntryPoint(name='alias', value='setuptools.command.alias:alias', group='distutils.commands'),
 EntryPoint(name='bdist_egg', value='setuptools.command.bdist_egg:bdist_egg', group='distutils.commands'),
 EntryPoint(name='bdist_rpm', value='setuptools.command.bdist_rpm:bdist_rpm', group='distutils.commands'),
 EntryPoint(name='build', value='setuptools.command.build:build', group='distutils.commands'),
 EntryPoint(name='build_clib', value='setuptools.command.build_clib:build_clib', group='distutils.commands'),
 EntryPoint(name='build_ext', value='setuptools.command.build_ext:build_ext', group='distutils.commands'),
 EntryPoint(name='build_py', value='setuptools.command.build_py:build_py', group='distutils.commands'),
 EntryPoint(name='develop', value='setuptools.command.develop:develop', group='distutils.commands'),
 EntryPoint(name='dist_info', value='setuptools.command.dist_info:dist_info', group='distutils.commands'),
 EntryPoint(name='easy_install', value='setuptools.command.easy_install:easy_install', group='distutils.commands'),
 EntryPoint(name='editable_wheel', value='setuptools.command.editable_wheel:editable_wheel', group='distutils.commands'),
 EntryPoint(name='egg_info', value='setuptools.command.egg_info:egg_info', group='distutils.commands'),
 EntryPoint(name='install', value='setuptools.command.install:install', group='distutils.commands'),
 EntryPoint(name='install_egg_info', value='setuptools.command.install_egg_info:install_egg_info', group='distutils.commands'),
 EntryPoint(name='install_lib', value='setuptools.command.install_lib:install_lib', group='distutils.commands'),
 EntryPoint(name='install_scripts', value='setuptools.command.install_scripts:install_scripts', group='distutils.commands'),
 EntryPoint(name='rotate', value='setuptools.command.rotate:rotate', group='distutils.commands'),
 EntryPoint(name='saveopts', value='setuptools.command.saveopts:saveopts', group='distutils.commands'),
 EntryPoint(name='sdist', value='setuptools.command.sdist:sdist', group='distutils.commands'),
 EntryPoint(name='setopt', value='setuptools.command.setopt:setopt', group='distutils.commands'),
 EntryPoint(name='test', value='setuptools.command.test:test', group='distutils.commands'),
 EntryPoint(name='upload_docs', value='setuptools.command.upload_docs:upload_docs', group='distutils.commands'),
 EntryPoint(name='bdist_wheel', value='wheel.bdist_wheel:bdist_wheel', group='distutils.commands')]
```

```
(unstable)bdrung@deep-thought:~$ python3 -c "from pprint import pprint; from setuptools.extern.importlib_metadata import entry_points; pprint(list(entry_points(group='distutils.commands')))"
[EntryPoint(name='build_skunkworks', value='setuptools_skunkworks:build_skunkworks', group='distutils.commands'),
 EntryPoint(name='clean_skunkworks', value='setuptools_skunkworks:clean_skunkworks', group='distutils.commands'),
 EntryPoint(name='install_skunkworks', value='setuptools_skunkworks:install_skunkworks', group='distutils.commands'),
 EntryPoint(name='build', value='DistUtilsExtra.command.build_extra:build', group='distutils.commands'),
 EntryPoint(name='build_help', value='DistUtilsExtra.command.build_help:build_help', group='distutils.commands'),
 EntryPoint(name='build_i18n', value='DistUtilsExtra.command.build_i18n:build_i18n', group='distutils.commands'),
 EntryPoint(name='build_icons', value='DistUtilsExtra.command.build_icons:build_icons', group='distutils.commands'),
 EntryPoint(name='clean_i18n', value='DistUtilsExtra.command.clean_i18n:clean_i18n', group='distutils.commands'),
 EntryPoint(name='pylint', value='DistUtilsExtra.command.pylint:pylint', group='distutils.commands'),
 EntryPoint(name='alias', value='setuptools.command.alias:alias', group='distutils.commands'),
 EntryPoint(name='bdist_egg', value='setuptools.command.bdist_egg:bdist_egg', group='distutils.commands'),
 EntryPoint(name='bdist_rpm', value='setuptools.command.bdist_rpm:bdist_rpm', group='distutils.commands'),
 EntryPoint(name='build', value='setuptools.command.build:build', group='distutils.commands'),
 EntryPoint(name='build_clib', value='setuptools.command.build_clib:build_clib', group='distutils.commands'),
 EntryPoint(name='build_ext', value='setuptools.command.build_ext:build_ext', group='distutils.commands'),
 EntryPoint(name='build_py', value='setuptools.command.build_py:build_py', group='distutils.commands'),
 EntryPoint(name='develop', value='setuptools.command.develop:develop', group='distutils.commands'),
 EntryPoint(name='dist_info', value='setuptools.command.dist_info:dist_info', group='distutils.commands'),
 EntryPoint(name='easy_install', value='setuptools.command.easy_install:easy_install', group='distutils.commands'),
 EntryPoint(name='editable_wheel', value='setuptools.command.editable_wheel:editable_wheel', group='distutils.commands'),
 EntryPoint(name='egg_info', value='setuptools.command.egg_info:egg_info', group='distutils.commands'),
 EntryPoint(name='install', value='setuptools.command.install:install', group='distutils.commands'),
 EntryPoint(name='install_egg_info', value='setuptools.command.install_egg_info:install_egg_info', group='distutils.commands'),
 EntryPoint(name='install_lib', value='setuptools.command.install_lib:install_lib', group='distutils.commands'),
 EntryPoint(name='install_scripts', value='setuptools.command.install_scripts:install_scripts', group='distutils.commands'),
 EntryPoint(name='rotate', value='setuptools.command.rotate:rotate', group='distutils.commands'),
 EntryPoint(name='saveopts', value='setuptools.command.saveopts:saveopts', group='distutils.commands'),
 EntryPoint(name='sdist', value='setuptools.command.sdist:sdist', group='distutils.commands'),
 EntryPoint(name='setopt', value='setuptools.command.setopt:setopt', group='distutils.commands'),
 EntryPoint(name='test', value='setuptools.command.test:test', group='distutils.commands'),
 EntryPoint(name='upload_docs', value='setuptools.command.upload_docs:upload_docs', group='distutils.commands'),
 EntryPoint(name='bdist_wheel', value='wheel.bdist_wheel:bdist_wheel', group='distutils.commands')]
```

**Comment by bdrung** [comment] 2023-09-06 15:44
distutils-extra overrides the build entry point:
```
$ cat /usr/lib/python3/dist-packages/python_distutils_extra-2.50.egg-info/entry_points.txt
[distutils.commands]
build = DistUtilsExtra.command.build_extra:build
build_help = DistUtilsExtra.command.build_help:build_help
build_i18n = DistUtilsExtra.command.build_i18n:build_i18n
build_icons = DistUtilsExtra.command.build_icons:build_icons
clean_i18n = DistUtilsExtra.command.clean_i18n:clean_i18n
pylint = DistUtilsExtra.command.pylint:pylint
```

**Comment by abravalheri** [comment] 2023-09-06 15:46
> I found the culprit: If you install `python3-distutils-extra` it breaks.

Very likely this package overwrites the `build` command to something that is different from either `setuptools.command.build.buil` or `distutils.command.build.build`.

I don't know if `distutils-extra-python` on PyPI is the same package as `python3-distutils-extra`, but if it is, we can confirm this hypothesis by having a look on:

https://inspector.pypi.io/project/distutils-extra-python/2.39.2/packages/86/2a/1c21f7fcf3a79eced356bd85c022262c51b63116471186def0a399f91317/distutils_extra_python-2.39.2-py3-none-any.whl/distutils_extra_python-2.39.2.dist-info/entry_points.txt

With that in mind, I believe that we can close this ticket since there is nothing that can be done from the point of view of setuptools. The implementation of `setuptools-gettext` and the reproducer `setuptools-skunkworks`, do seem not account for the possibility that either another plugin or the user itself overwrites the class for the `build` command (at least not without user intervention).

> In the unstable schroot mentioned above:

I was thinking more of the system where the problem was happening (I understood that in the `schroot` things were working fine...) 😅.

**Comment by bdrung** [comment] 2023-09-06 16:05
Thanks for helping to debug it. Is there a way to make plugins continue working with overridden build commands? Modifying both (distutils-extra and setuptools-gettext/setuptools-skunkworks) is also possible (with my Debian/Ubuntu packaging hat on).

**Comment by abravalheri** [comment] 2023-09-06 16:28
I think it is possible... using the `finalize_distribution_options` hook you can defer adding the sub-commands. Something like the following (untested, just sketching things from memory, better to double check):

```python
def finalize_distribution_options(dist: Distribution):
    build = dist.get_command_class("build")

    class my_build(build):
       def finalize_options(self):
           super().finalize_options()
           self.sub_commands.append(...)

    dist.cmdclass["build"] = my_build

finalize_distribution_options.order = 9999  # not strictly necessary but we can try to delay the hook as much as possible.
```

**Comment by abravalheri** [comment] 2023-09-06 17:17
I will close the issue because I don't think there is a bug here, but we can keep using the comments for discussion.

**Closed by abravalheri** 2023-09-06 17:17 UTC
Labels: Needs Repro

**Comment by bdrung** [comment] 2023-09-08 15:52
Thanks. Adding the entry points in [finalize_distribution_options](https://setuptools.pypa.io/en/latest/userguide/extension.html#customizing-distribution-options) works:

```python3
def finalize_distribution_options(dist: Distribution) -> None:
    """Plug the extension into setuptools."""
    build = dist.get_command_class("build")
    build.sub_commands.append(("build_skunkworks", has_skunkworks))

    install = dist.get_command_class("install")
    install.sub_commands.append(("install_skunkworks", has_skunkworks))
```

I also pushed that change to https://github.com/bdrung/setuptools-skunkworks
