### ISSUE TITLE
[FR] Support Combination of Multiple `extras_require` Items in `setup.cfg`

### ISSUE THREAD

**Issue by ChihweiLHBird** [pypa/setuptools#3010] opened 2022-01-07 08:46 UTC
### What's the problem this feature will solve?

```
[options.extras_require]
a = pkg_a>=1.0
b = pkg_b>=1.0
all = a + b
```

OR:

```
[options.extras_require]
a = pkg_a>=1.0
b = pkg_b + a
```

The `all` option that combines `a` and `b` in the first case is currently not available (if I didn't miss any docs).
So does `b` in the second case.

### Describe the solution you'd like

It would be very nice to support the `all` option mentioned above.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment] 2022-01-07 09:16
Hi @ChihweiLHBird thank you very much for bringing this up.

Since it is very likely that setuptools is going to move its configuration towards [PEP621](https://www.python.org/dev/peps/pep-0621/), I think it does not make much sense to implement this syntax in a `setup.cfg` basis...

Therefore, if you would to see this syntax change implemented in the future via `pyproject.toml`, I recommend posting your suggestion to https://discuss.python.org/c/packaging/14 (but adapting it to fit a PEP 621 context)

For the general effect you are after, this issue seems to be a duplicate of https://github.com/pypa/setuptools/issues/1260. If you give a look on what Jason proposed there on ways to move this issue forward and would like to submit a PR, that would be amazing!

Meanwhile, please note that modern versions of `pip` seem to understand the concept of "self-dependency" that would allow you to achieve the end result you are after. So you could try:

```ini
all =
    mypkg[a]
    mypkg[b]
```

(This is `pip` specific implementation,  it might not work, though... I haven't tried)

**Closed** 2022-01-07 09:18 UTC
Labels: duplicate
