### ISSUE TITLE
Do we need EasyInstall anymore?

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#449] opened 2015-10-16 09:46 UTC
Originally reported by: **graingert (Bitbucket: [graingert](http://bitbucket.org/graingert), GitHub: [graingert](http://github.com/graingert))**

---

Now that pip (ensurepip) is shipped by default with Python does EasyInstall still need to be a documented feature?

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/449

**Comment by pganssle** [comment] 2018-10-25 19:33
I think this can be consolidated into #917 even if that one is a duplicate of this.

**Closed by pganssle** 2018-10-25 19:33 UTC
Labels: duplicate, major, proposal
