### ISSUE TITLE
No module name Feature from setuptools

### ISSUE THREAD

**Issue by DontBe3Greedy** [pypa/setuptools#2022] opened 2020-03-13 22:47 UTC
When i try to install pyscss, it tells me no module called feature is found

``   
 ERROR: Command errored out with exit status 1:
     command: /srv/www/greedyguides.com/.local/share/virtualenvs/tmp-XVr6zr33/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rwtbx187/pyscss/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rwtbx187/pyscss/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-rwtbx187/pyscss/pip-egg-info
         cwd: /tmp/pip-install-rwtbx187/pyscss/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rwtbx187/pyscss/setup.py", line 9, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature' from 'setuptools' (/srv/www/greedyguides.com/.local/share/virtualenvs/tmp-XVr6zr33/lib/python3.8/site-packages/setuptools/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output. 
``

**Comment by pganssle** [comment] 2020-03-13 23:20
This is a duplicate of #2017, this was an expected change with a long deprecation period. See the other ticket for more details. Sorry that this broke your workflow! Hopefully the ecosystem will adjust soon!

**Closed by pganssle** 2020-03-13 23:20 UTC
