### ISSUE TITLE
Setuptools' sdist doesn't use data_files while distutils does

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#521] opened 2016-03-23 20:32 UTC
Originally reported by: **ionelmc (Bitbucket: [ionelmc](http://bitbucket.org/ionelmc), GitHub: [ionelmc](http://github.com/ionelmc))**

----------------------------------------

Distutils has this: https://github.com/python/cpython/blob/master/Lib/distutils/command/sdist.py#L270-L282

However that code is not copies in the sdist provided by setuptools. 

This can be problematic if you don't inlcude a file in MANIFEST.in but you have it in data_files - python's docs will most certainly mislead you as they say that sdist uses data_files: https://docs.python.org/3/distutils/sourcedist.html?highlight=data_files#specifying-the-files-to-distribute (last bullet)

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/521

**Comment by jaraco** [comment] 2016-08-20 22:05
Here's an updated link to the distutils code with the line numbers matching: https://github.com/python/cpython/blob/8ed7551d57a6563fe9d8afaac2b12ff9e86e77ae/Lib/distutils/command/sdist.py#L270-L282

**Comment by jaraco** [comment] 2016-10-30 02:32
I'm just going to mark this as a duplicate of #274.

**Closed by jaraco** 2016-10-30 02:32 UTC
Labels: bug, major
