### ISSUE TITLE
error when pip install with pyproject.toml

### ISSUE THREAD

**Issue by craynic** [pypa/setuptools#1723] opened 2019-03-19 06:22 UTC
I have a repo that can successfully build wheel, build src dist, and install by pip.
Now I have some build dependencies. So I added `pyproject.toml`
> [build-system]
> requires = ["avro-python3", "setuptools", "wheel"]

and run `pip install .`, got error:

    Looking in indexes: https://mirrors.shu.edu.cn/pypi/web/simple, https://****:****@****/repository/pypi-internal/simple
    Processing /home/craynic/code/my-project
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
        Preparing wheel metadata: started
        Preparing wheel metadata: finished with status 'done'
    Building wheels for collected packages: my-project
      Building wheel for my-project (PEP 517): started
      Building wheel for my-project (PEP 517): finished with status 'error'
      Complete output from command /home/craynic/.virtualenvs/test3/bin/python /home/craynic/.virtualenvs/test3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp73mqsh3_:
      running bdist_wheel
      running build
      running build_py
      copying all_my_files -> build/lib/my_package
      installing to build/bdist.linux-x86_64/wheel
      running install
      running install_lib
      creating build/bdist.linux-x86_64/wheel
      creating build/bdist.linux-x86_64/wheel/my_package
      ...copying files
      running install_egg_info
      running egg_info
      writing my_package.egg-info/PKG-INFO
      writing dependency_links to my_project.egg-info/dependency_links.txt
      writing top-level names to my_project.egg-info/top_level.txt
      reading manifest file 'my_project.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      writing manifest file 'my_project.egg-info/SOURCES.txt'
      Copying my_project.egg-info to build/bdist.linux-x86_64/wheel/my_project-11.0.0-py3.7.egg-info
      running install_scripts
      creating build/bdist.linux-x86_64/wheel/my_package-11.0.0.dist-info/WHEEL
      creating 'dist/my_package-11.0.0-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
      adding all my files
      adding 'my_package-11.0.0.dist-info/METADATA'
      adding 'my_package-11.0.0.dist-info/WHEEL'
      adding 'my_package-11.0.0.dist-info/top_level.txt'
      adding 'my_package-11.0.0.dist-info/RECORD'
      removing build/bdist.linux-x86_64/wheel
      Traceback (most recent call last):
        File "/home/craynic/.virtualenvs/test3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
          main()
        File "/home/craynic/.virtualenvs/test3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/craynic/.virtualenvs/test3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 141, in build_wheel
          metadata_directory)
        File "/tmp/pip-build-env-cbiy7zlf/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 178, in build_wheel
          return _file_with_extension(wheel_directory, '.whl')
        File "/tmp/pip-build-env-cbiy7zlf/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 94, in _file_with_extension
          file, = matching
      ValueError: too many values to unpack (expected 1)
    
      ----------------------------------------
      Running setup.py clean for my-package
    Failed to build my-package

Some information has been hidden.
Got same error when I install from a source distribution.
It seems that setuptools cannot find the wheel file just built.

**Comment by benoit-pierre** [comment] 2019-03-19 10:59
Duplicate of #1671.

**Closed by benoit-pierre** 2019-03-19 10:59 UTC
