### ISSUE TITLE
[BUG]  invalid command 'bdist_wininst' during bdist_wheel

### ISSUE THREAD

**Issue by teije01** [pypa/setuptools#3525] opened 2022-08-15 15:08 UTC
### setuptools version

setuptools==65.0.0

### Python version

python 3.8

### OS

Debian GNU/Linux 11 (bullseye)

### Additional environment information

Last known working version was setuptools 63.4.3, did not test with 64.*.*

### Description

Latest setuptools causes pip install to exit with the following error:

`error: invalid command 'bdist_wininst'`

### Expected behavior

```
  Building wheel for vds-base-cli (setup.py): started
  Building wheel for vds-base-cli (setup.py): finished with status 'done'
```

### How to Reproduce

Created an environment with conda:

```bash
conda create -n test python=3.8 --yes
conda activate test
pip install "setuptools==65.0.0"
pip install vds-api-client
pip install --no-cache-dir --force --no-deps --no-binary :all: vds-api-client  # Fails
```

And then re-installing with setuptools 63.4.3 succeeds

```bash
pip install setuptools==63.4.3
pip install --no-cache-dir --force --no-deps --no-binary :all: vds-api-client
```

### Output

traceback during pip install

```console
pip install --no-cache-dir --force --no-deps --no-binary :all: vds-api-client
Looking in indexes: https://pypi.org/simple, https://__token__:****@gitlab.vandersat.com/api/v4/projects/178/packages/pypi/simple, https://pypi.prod.planet-labs.com/simple/
Collecting vds-api-client
  Downloading vds_api_client-2.1.4.tar.gz (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 kB 73.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Skipping wheel build for vds-api-client, due to binaries being disabled for it.
Installing collected packages: vds-api-client
  Attempting uninstall: vds-api-client
    Found existing installation: vds-api-client 2.1.4
    Uninstalling vds-api-client-2.1.4:
      Successfully uninstalled vds-api-client-2.1.4
  Running setup.py install for vds-api-client ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for vds-api-client did not run successfully.
  │ exit code: 1
  ╰─> [65 lines of output]
      /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/setuptools/dist.py:771: 
        warnings.warn(
      /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      /tmp/pip-install-2gpji5lc/vds-api-client_ede23293a8c14325ba6de91913c551d3/.eggs/PyScaffold-2.5.11-py3.8.egg/pyscaffold/contrib/pbr/pbr/core.py:120: UserWarning: Unknown distribution option: 'project_urls'
        warnings.warn(msg)
      /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'author-email' will not be supported in future versions. Please use the underscore name 'author_email' instead
        warnings.warn(
      /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'long-description' will not be supported in future versions. Please use the underscore name 'long_description' instead
        warnings.warn(
      /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'long-description-content-type' will not be supported in future versions. Please use the underscore name 'long_description_content_type' instead
        warnings.warn(
      /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'project-urls' will not be supported in future versions. Please use the underscore name 'project_urls' instead
        warnings.warn(
      /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      running install
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/vds_api_client
      copying vds_api_client/types.py -> build/lib/vds_api_client
      copying vds_api_client/__init__.py -> build/lib/vds_api_client
      copying vds_api_client/requester.py -> build/lib/vds_api_client
      copying vds_api_client/vds_api_base.py -> build/lib/vds_api_client
      copying vds_api_client/api_cli.py -> build/lib/vds_api_client
      copying vds_api_client/api_v2.py -> build/lib/vds_api_client
      running egg_info
      writing vds_api_client.egg-info/PKG-INFO
      writing dependency_links to vds_api_client.egg-info/dependency_links.txt
      writing entry points to vds_api_client.egg-info/entry_points.txt
      writing requirements to vds_api_client.egg-info/requires.txt
      writing top-level names to vds_api_client.egg-info/top_level.txt
      [pbr] Reusing existing SOURCES.txt
      running install_lib
      creating /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/vds_api_client
      copying build/lib/vds_api_client/types.py -> /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/vds_api_client
      copying build/lib/vds_api_client/__init__.py -> /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/vds_api_client
      copying build/lib/vds_api_client/requester.py -> /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/vds_api_client
      copying build/lib/vds_api_client/vds_api_base.py -> /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/vds_api_client
      copying build/lib/vds_api_client/api_cli.py -> /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/vds_api_client
      copying build/lib/vds_api_client/api_v2.py -> /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/vds_api_client
      byte-compiling /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/vds_api_client/types.py to types.cpython-38.pyc
      byte-compiling /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/vds_api_client/__init__.py to __init__.cpython-38.pyc
      byte-compiling /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/vds_api_client/requester.py to requester.cpython-38.pyc
      byte-compiling /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/vds_api_client/vds_api_base.py to vds_api_base.cpython-38.pyc
      byte-compiling /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/vds_api_client/api_cli.py to api_cli.cpython-38.pyc
      byte-compiling /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/vds_api_client/api_v2.py to api_v2.cpython-38.pyc
      running install_egg_info
      Copying vds_api_client.egg-info to /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/vds_api_client-2.1.4-py3.8.egg-info
      running install_scripts
      error: invalid command 'bdist_wininst'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  WARNING: No metadata found in ./miniconda3/envs/test/lib/python3.8/site-packages
  Rolling back uninstall of vds-api-client
  Moving to /home/teije/miniconda3/envs/test/bin/vds-api
   from /tmp/pip-uninstall-obvs9abo/vds-api
  Moving to /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/vds_api_client-2.1.4.dist-info/
   from /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/~ds_api_client-2.1.4.dist-info
  Moving to /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/vds_api_client/
   from /home/teije/miniconda3/envs/test/lib/python3.8/site-packages/~ds_api_client
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> vds-api-client

```

**Comment by abravalheri** [comment] 2022-08-15 15:23
Hi @teije01, I have the impression that this might be caused by the existence of an old setuptools installation somewhere in the directories listed as "site-packages" (can be listed in via `python -m site`).

Any chance you have an old setuptools hanging around? Could you try repeating this installation inside of an isolated virtual environment (with the latest setuptools) to check if this hypothesis holds?

**Comment by jaraco** [comment] 2022-08-15 23:43
Setuptools 65 removed the `bdist_wininst` and `bdist_msi` commands as they were marked as deprecated and have been for some time. I was unaware that `install_scripts` [attempts to call `bdist_wininst`](https://github.com/pypa/setuptools/blob/0a1906819c568ceb3ffccc61d531fecd6b8662de/setuptools/command/install_scripts.py#L38), but it also appears to trap an exception. I'm only slightly surprised that the tests don't cover this behavior.

Probably the best fix is to just remove that code as it should never succeed now.

**Comment by jaraco** [comment] 2022-08-15 23:45
I was able to replicate the issue simply with:

```
docker run -it jaraco/multipy-tox pip install --no-deps --no-binary vds-api-client vds-api-client
```

**Comment by jaraco** [comment] 2022-08-15 23:50
I can also replicate the failure with: `docker run -it jaraco/multipy-tox pip-run -q git+https://github.com/pypa/setuptools -- -m pip install --no-deps --no-binary vds-api-client vds-api-client --no-build-isolation`

**Comment by jaraco** [comment] 2022-08-16 00:38
I pushed a fix, but even attempting to build against it doesn't work around the issue.

Tracing the issue, I see that the issue is rooted in PyScaffold and its vendored copy of pbr:

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/jaraco/code/public/pypa/setuptools/vds_api_client-2.1.4/setup.py", line 21, in <module>
    setup(use_pyscaffold=True, setup_requires=['pyscaffold>=2.5a0,<2.6a0'])
  File "/Users/jaraco/code/public/pypa/setuptools/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/Users/jaraco/code/public/pypa/setuptools/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/Users/jaraco/code/public/pypa/setuptools/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/Users/jaraco/code/public/pypa/setuptools/setuptools/_distutils/dist.py", line 974, in run_commands
    self.run_command(cmd)
  File "/Users/jaraco/code/public/pypa/setuptools/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/Users/jaraco/code/public/pypa/setuptools/setuptools/_distutils/dist.py", line 993, in run_command
    cmd_obj.run()
  File "/Users/jaraco/code/public/pypa/setuptools/vds_api_client-2.1.4/.eggs/PyScaffold-2.5.11-py3.10.egg/pyscaffold/contrib/pbr/pbr/packaging.py", line 449, in run
    self.get_finalized_command("bdist_wininst"), '_is_running', False
  File "/Users/jaraco/code/public/pypa/setuptools/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
    cmd_obj = self.distribution.get_command_obj(command, create)
  File "/Users/jaraco/code/public/pypa/setuptools/setuptools/_distutils/dist.py", line 865, in get_command_obj
    klass = self.get_command_class(command)
  File "/Users/jaraco/code/public/pypa/setuptools/setuptools/dist.py", line 957, in get_command_class
    return _Distribution.get_command_class(self, command)
  File "/Users/jaraco/code/public/pypa/setuptools/setuptools/_distutils/dist.py", line 848, in get_command_class
    raise ValueError(command)
ValueError: bdist_wininst
```

Looking into pbr, I can see that two years ago, [pbr removed that call](https://opendev.org/openstack/pbr/commit/e52e608e35938da27dd9ec7209e4fa858ed8adb6).

It seems the issue is that [vds_api_client depends](https://github.com/vandersat/vds-api-client/blob/008fba54f8d19893505eaa5d4248fa5fb7342fc5/setup.py#L21) on an [old PyScaffold](https://pypi.org/project/PyScaffold/2.5.11/) which vendors an old `pbr`.

I'm afraid the only option here is to make sure to build the project using older Setuptools versions. You may want to report this issue downstream to vds_api_client so they can update their dependency.

I'm still going to remove the Setuptools code that can never succeed, but there's not much this project can do to address the issue, so I'm going to close it.

**Closed by jaraco** 2022-08-16 00:38 UTC
Labels: bug, blocker

**Comment by teije01** [comment] 2022-08-17 15:14
I can confirm that the problem is indeed with pyscaffold version 2. Upgrading a project to Pyscaffold version 3 does solve the issue.

Thanks @jaraco for your suggestions, this has helped us greatly.
