### ISSUE TITLE
pkg_resources.parse_requirements does not have support for find-links

### ISSUE THREAD

**Issue by peterroelants** [pypa/setuptools#3600] opened 2022-09-21 13:57 UTC
### setuptools version

65.3.0

### Python version

Python 3.10.6

### OS

Ubuntu 20.04.5

### Description

I tried to run the following piece of code:
```python
from pathlib import Path
import pkg_resources

# Read requirements
with Path("requirements.txt").open() as f_in:
    for pkg in pkg_resources.parse_requirements(f_in):
        print(pkg.name)
```

on the following `requirements.txt` file:
```
jax[cuda11_cudnn82]==0.3.17
jaxlib==0.3.15
--find-links https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```

And get a `InvalidRequirement` error saying: `pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'--find-l'": Expected W:(0-9A-Za-z)`. Which seems to fail at the `--find-links`.

### Expected behavior

I expect the [`--find-links` option from pip install](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-f) to not cause an issue when parsing the requirements file.

To be clear pip installing the requirements file does not cause any issues. E.g. the following works fine:
```
pip install -r requirements.txt
```

### How to Reproduce

Minimal reproduction:
```python
import pkg_resources

requirements = """
jax[cuda11_cudnn82]==0.3.17
jaxlib==0.3.15
--find-links https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
"""

for pkg in pkg_resources.parse_requirements(requirements):
    print(pkg.name)
```

### Output

```console
jax
jaxlib
Traceback (most recent call last):
  File "./env/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 102, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "./env/lib/python3.10/site-packages/pkg_resources/_vendor/pyparsing/core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pkg_resources._vendor.pyparsing.exceptions.ParseException: Expected W:(0-9A-Za-z), found '-'  (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./src/tests/run.py", line 6, in <module>
    for pkg in pkg_resources.parse_requirements(f_in):
  File "./env/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3102, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "./env/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 104, in __init__
    raise InvalidRequirement(
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'--find-l'": Expected W:(0-9A-Za-z)

```

### Note
I wasn't sure where to post this, but the [`pkg_resources` repo](https://github.com/pypa/pkg_resources) refereces to the `pypa/setuptools` repo.

**Comment by abravalheri** [comment] 2022-09-21 15:14
Hi @peterroelants, I believe this issue is kind of a duplicate of #3465 and #2549.

The main motivation behind`pkg_resources.parse_requirements` is to parse a string where each line corresponds to a dependency specification (PEP 508). Therefore this functions is not compatible with `requirements.txt` files, since this kind of files may contain pip specific syntax (for example the `--find-links` flag), and therefore do not fit in the same mindset.

I personally don't think this kind of feature would fit nicely within the `pkg_resources` or `setuptools` packages (it seems to be a bit outside of the scope of the project, considering the previous issues/discussions about `requirements.txt`). Moreover `pkg_resources` is on its way to retirement, so adding features to the library does not make much sense.

Maybe other alternatives, like using [pip-tools](https://github.com/jazzband/pip-tools/), could expand the file into a proper flat list of PEP 508 requirements (I am not sure). Have you tried to investigate that approach?

**Comment by peterroelants** [comment] 2022-09-21 15:20
Hi @abravalheri thank you for that context. I will explore pip-tools, or other solutions.

**Closed** 2022-09-21 15:40 UTC
Labels: out-of-scope
