### ISSUE TITLE
[BUG] Calling pip within setup.py in a project that contains a pyproject.toml & a setup.py results in error "No module named pip"

### ISSUE THREAD

**Issue by greg-is-kub** [pypa/setuptools#4440] opened 2024-06-26 17:46 UTC
### setuptools version

setuptool>=68

### Python version

3.10.12

### OS

Ubuntu 22.04

### Additional environment information

```Dockerfile
FROM nvidia/cuda:12.5.0-devel-ubuntu22.04

RUN apt-get update && \
    apt-get install -y \
    bash \
    sudo \
    curl \
    git \
    jq \
    && rm -rf /var/lib/apt/lists/*
RUN apt-get install sudo

# Create a new user and set up the home directory
RUN useradd -ms /bin/bash greg

# Create a new user named greg, set the password, and add to sudo group
# Password for docker is greg
RUN id -u greg &>/dev/null || useradd -ms /bin/bash greg \
    && echo "greg:greg" | chpasswd \
    && usermod -aG sudo greg
# Switch to the new user
USER greg

# Set the working directory to the user's home
WORKDIR /home/greg
```

### Description

I have a poorly oranized project I need to package.  There is a meta package that holds every sub-package.
Hence to build the meta package I need to iterate over each package and just `pip install` them.
Having a (minimal) pyproject.toml and a setup.py results in an error : 
```
 /usr/bin/python3: No module named pip
```

### Expected behavior

I expect to have pip list displayed during the pip install and instead I don't have any output.

#### pyproject.toml
Here is the `pyproject.toml` : 
```toml
[build-system]
requires = [
    "setuptools>=68",
    "setuptools-scm",
    "cmake",
    "toml"
]
build-backend = "setuptools.build_meta"
```

#### `setup.py`:
```python
#!/usr/bin/env python3
import sys
import pathlib
import os
import subprocess

from setuptools import setup, Extension, find_packages
from setuptools.command.build_ext import build_ext


class BuildExtension(Extension):
    def __init__(self, name):
        super().__init__(name, sources=[])


class PkgBuild(build_ext):
    def run(self):
        subprocess.call([f"{sys.executable}", "-m", "pip", "list"])


def clean_eggs():
    eggs_dir = ".eggs"
    if os.path.isdir(eggs_dir):
        shutil.rmtree(eggs_dir)
        print(f"Removed {eggs_dir} directory")


if __name__ == "__main__":
    setup(
        name="Project",
        python_requires=">= 3.7",
        # setup_requires=[
        #     "setuptools>=64",
        #     "setuptools_scm[toml]==7.1.0",
        #     "shutil",
        # ],
        packages=find_packages(where="."),
        include_package_data=True,
        ext_modules=[BuildExtension("aidge")],
        cmdclass={
            "build_ext": PkgBuild,
        },
        zip_safe=False,
    )

    clean_eggs()
```

Here is my bug. 
My project is open source, if you wish to have access to it, I can provide more informations.

### Output

:warning:  Now its important to note that calling `pip install . -v` results in an error BUT not calling `python setup.py build`

### `pip install . -v` output 
:warning: note the "no module named pip".
```console
Using pip 24.1 from /home/greg/.local/lib/python3.10/site-packages/pip (python 3.10)
Defaulting to user installation because normal site-packages is not writeable
Processing /home/greg/workspace/cea/aidge_group/aidge
  Running command pip subprocess to install build dependencies
  Using pip 24.1 from /home/greg/.local/lib/python3.10/site-packages/pip (python 3.10)
  Collecting setuptools>=68
    Obtaining dependency information for setuptools>=68 from https://files.pythonhosted.org/packages/b
3/7a/629889a5d76200287aa5483d753811bd247bbd1b03175186f759e0c7d3a7/setuptools-70.1.1-py3-none-any.whl.m
etadata
    Using cached setuptools-70.1.1-py3-none-any.whl.metadata (6.0 kB)
  Collecting setuptools-scm
    Obtaining dependency information for setuptools-scm from https://files.pythonhosted.org/packages/a
0/b9/1906bfeb30f2fc13bb39bf7ddb8749784c05faadbd18a21cf141ba37bff2/setuptools_scm-8.1.0-py3-none-any.wh
l.metadata
    Using cached setuptools_scm-8.1.0-py3-none-any.whl.metadata (6.6 kB)
  Collecting cmake
    Obtaining dependency information for cmake from https://files.pythonhosted.org/packages/ad/78/bc40
496264f8e940e90c9466c511da3fec5302457ab71d296012f8d508f8/cmake-3.29.6-py3-none-manylinux_2_17_x86_64.m
anylinux2014_x86_64.whl.metadata
    Using cached cmake-3.29.6-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.1 kB
)
  Collecting toml
    Obtaining dependency information for toml from https://files.pythonhosted.org/packages/44/6f/71206
76b6d73228c96e17f1f794d8ab046fc910d781c8d151120c3f1569e/toml-0.10.2-py2.py3-none-any.whl.metadata
    Using cached toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
  Collecting packaging>=20 (from setuptools-scm)
    Obtaining dependency information for packaging>=20 from https://files.pythonhosted.org/packages/08
/aa/cc0199a5f0ad350994d660967a8efb233fe0416e4639146c089643407ce6/packaging-24.1-py3-none-any.whl.metad
ata
    Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
  Collecting tomli>=1 (from setuptools-scm)
    Obtaining dependency information for tomli>=1 from https://files.pythonhosted.org/packages/97/75/1
0a9ebee3fd790d20926a90a2547f0bf78f371b2f13aa822c759680ca7b9/tomli-2.0.1-py3-none-any.whl.metadata
    Using cached tomli-2.0.1-py3-none-any.whl.metadata (8.9 kB)
  Using cached setuptools-70.1.1-py3-none-any.whl (883 kB)
  Using cached setuptools_scm-8.1.0-py3-none-any.whl (43 kB)
  Using cached cmake-3.29.6-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.7 MB)
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
  Using cached packaging-24.1-py3-none-any.whl (53 kB)
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
  Installing collected packages: tomli, toml, setuptools, packaging, cmake, setuptools-scm
    Creating /tmp/pip-build-env-liy5nit7/overlay/local/bin
    changing mode of /tmp/pip-build-env-liy5nit7/overlay/local/bin/cmake to 755
    changing mode of /tmp/pip-build-env-liy5nit7/overlay/local/bin/cpack to 755
    changing mode of /tmp/pip-build-env-liy5nit7/overlay/local/bin/ctest to 755
  Successfully installed cmake-3.29.6 packaging-24.1 setuptools-70.1.1 setuptools-scm-8.1.0 toml-0.10.
2 tomli-2.0.1
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  running egg_info
  writing Project.egg-info/PKG-INFO
  writing dependency_links to Project.egg-info/dependency_links.txt
  writing top-level names to Project.egg-info/top_level.txt
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'CMakeLists.txt'
  adding license file 'LICENSE'
  writing manifest file 'Project.egg-info/SOURCES.txt'
  Getting requirements to build wheel ... done
  Running command Preparing metadata (pyproject.toml)
  running dist_info
  creating /tmp/pip-modern-metadata-5vagzgzw/Project.egg-info
  writing /tmp/pip-modern-metadata-5vagzgzw/Project.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-modern-metadata-5vagzgzw/Project.egg-info/dependency_links.txt
  writing top-level names to /tmp/pip-modern-metadata-5vagzgzw/Project.egg-info/top_level.txt
  writing manifest file '/tmp/pip-modern-metadata-5vagzgzw/Project.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'CMakeLists.txt'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-modern-metadata-5vagzgzw/Project.egg-info/SOURCES.txt'
  creating '/tmp/pip-modern-metadata-5vagzgzw/Project-0.0.0.dist-info'
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: Project
  Running command Building wheel for Project (pyproject.toml)
  running bdist_wheel
  running build
  running build_ext
  /usr/bin/python3: No module named pip
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  warning: install_lib: 'build/lib.linux-x86_64-cpython-310' does not exist -- no Python modules to install

  running install_egg_info
  running egg_info
  writing Project.egg-info/PKG-INFO
  writing dependency_links to Project.egg-info/dependency_links.txt
  writing top-level names to Project.egg-info/top_level.txt
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'CMakeLists.txt'
  adding license file 'LICENSE'
  writing manifest file 'Project.egg-info/SOURCES.txt'
  Copying Project.egg-info to build/bdist.linux-x86_64/wheel/Project-0.0.0-py3.10.egg-info
  running install_scripts
  creating build/bdist.linux-x86_64/wheel/Project-0.0.0.dist-info/WHEEL
  creating '/tmp/pip-wheel-ywai3z7g/.tmp-qm7v0e0a/Project-0.0.0-cp310-cp310-linux_x86_64.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
  adding 'Project-0.0.0.dist-info/LICENSE'
  adding 'Project-0.0.0.dist-info/METADATA'
  adding 'Project-0.0.0.dist-info/WHEEL'
  adding 'Project-0.0.0.dist-info/top_level.txt'
  adding 'Project-0.0.0.dist-info/RECORD'
  removing build/bdist.linux-x86_64/wheel
  Building wheel for Project (pyproject.toml) ... done
  Created wheel for Project: filename=Project-0.0.0-cp310-cp310-linux_x86_64.whl size=6299 sha256=581bb1decb014b6836069abab747a53735c979ac7a361fa064087989a9ff68fe
  Stored in directory: /tmp/pip-ephem-wheel-cache-6h1ns_8g/wheels/22/7e/f1/e6fb9632e0926def55e312e4357daafac1c777f1507855d1bb
Successfully built Project
Installing collected packages: Project
  Attempting uninstall: Project
    Found existing installation: Project 0.0.0
    Uninstalling Project-0.0.0:
      Removing file or directory /home/greg/.local/lib/python3.10/site-packages/Project-0.0.0.dist-info/
      Successfully uninstalled Project-0.0.0
Successfully installed Project-0.0.0
```

#### python setup.py build output : 
```console
running build
running build_ext
Package    Version
---------- -------
aidge      0.0.0
numpy      2.0.0
onnx       1.16.1
pip        24.1
Project    0.0.0
protobuf   5.27.2
setuptools 59.6.0
wheel      0.37.1
```

**Comment by Avasam** [comment] 2024-06-26 18:10
(disclaimer, I'm not an expert in this area but I can try to help you out with the following hints)

pip isn't necessarily the package installer that a user might be using (for example: `uv` or `poetry`). With https://peps.python.org/pep-0517/ it can't be assumed that pip will be available. If you have a hard requirement on it, it should likely part of your `requires`.

It's just a guess, but you could add it to your requirements and try again with or w/o the `--use-pep517` flag
https://pip.pypa.io/en/stable/reference/build-system/#controlling-which-build-system-interface-is-used
https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-use-pep517

Lastly, grasping at straws a bit, but from my python experience on Ubuntu, are we sure that `/usr/bin/python3` and `/home/greg/.local/lib/python3.10` point to the same executable (it should given your script), and check out https://docs.python.org/3/library/ensurepip.html#command-line-interface

**Comment by webknjaz** [comment] 2024-06-26 18:19
Yeah, adding `pip` to `[build-system]requires` will make it available. However, you should stop using it instead. The reason is that the build front-ends (like `python -Im build` or `python -Im pip install .` would create ephemeral tmp virtualenvs and populate them with everything your build backend of choice would need. Inside those venvs, there wouldn't be `pip` by default. But even if it was there, `pip list` would only list stuff within that ephemeral venv which is roughly whatever's in `[build-system]requires`.

In general, it's a bad idea to keep doing what you do.

**Comment by greg-is-kub** [comment] 2024-06-27 07:39
> Yeah, adding `pip` to `[build-system]requires` will make it available. However, you should stop using it instead. The reason is that the build front-ends (like `python -Im build` or `python -Im pip install .` would create ephemeral tmp virtualenvs and populate them with everything your build backend of choice would need. Inside those venvs, there wouldn't be `pip` by default. But even if it was there, `pip list` would only list stuff within that ephemeral venv which is roughly whatever's in `[build-system]requires`.
> 
> In general, it's a bad idea to keep doing what you do.

Oh my god I can't wrap my head around the fact that I spent a whole week not thinking about adding pip to build requires. 
Why isn't pip shipped with python by default ? That would make sense to me.

Yeah the `pip list` was just here for demonstration purpose. But i don't use the `-I` Option by myself so how can this bother me because I check for subpkg installation to avoid re-installing them. 
But since I don't use `-I`, `pip` should be installed right ?

**Comment by abravalheri** [comment] 2024-06-27 09:54
> Why isn't pip shipped with python by default ? That would make sense to me.
> But since I don't use `-I`, `pip` should be installed right ?

That is not how `pip` works, since PEP 517 it will create the equivalent of a brand new and blank virtual environment from scratch just for calling setuptools. Nothing else than the specified requirements will be installed there.

---

Ok since we identified the root cause of the problem, I will go ahead and close this issue. Thanks @Avasam and @webknjaz!

**Closed by abravalheri** 2024-06-27 09:54 UTC
Labels: invalid, question
