### ISSUE TITLE
False positive when checking for inconsistent setup script path on Windows

### ISSUE THREAD

**Issue by uranusjr** [pypa/setuptools#1519] opened 2018-10-23 17:21 UTC
```
> python setup.py develop
running develop
Checking .pth file support in C:\project\venv\Lib\site-packages\
C:\project\venv\Scripts\pythonw.exe -E -c pass
TEST PASSED: C:\project\venv\Lib\site-packages\ appears to support .pth files
error: ("Can't get a consistent path to setup script from installation directory", 'c:\\project\\', 'c:\\project')
```

I am not sure what exactly is the cause (I did not have this problem previously, but suddenly sees it when coming back to work on an old project), but it seems to come from a quirk of `realpath()`:

```pycon
>>> import os
>>> os.path.realpath('.')
'C:\\Users\\uranusjr\\'
>>> os.path.realpath('../')
'C:\\Users\\'
>>> os.path.realpath('..')
'C:\\Users'
```

**Comment by pganssle** [comment] 2018-10-23 18:16
@uranusjr Can you provide a [minimal reproducing example](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) for this? It seems that the error is being raised from [here](https://github.com/pypa/setuptools/blob/e0433cf32dfdf39c0c14a3740c3920c496f09486/setuptools/command/develop.py#L91), based on the error message, but without a failing test or a minimal reproducing example, it's hard to tell how to fix it.

**Comment by uranusjr** [comment] 2018-10-23 18:34
Of course!

```
> mkdir project
> cd project
> mkdir src
> [create setup.py]
```

```python
from setuptools import find_packages, setup

setup(
    name='project',
    version='0.0.0',
    package_dir={'': 'src'},
    packages=find_packages('src'),
)
```

```
> python setup.py develop
running develop
Checking .pth file support in C:\Users\uranusjr\Documents\playground\project\.venv\Lib\site-packages\
C:\Users\uranusjr\Documents\playground\project\.venv\Scripts\pythonw.exe -E -c pass
TEST PASSED: C:\Users\uranusjr\Documents\playground\project\.venv\Lib\site-packages\ appears to support .pth files
error: ("Can't get a consistent path to setup script from installation directory", 'c:\\users\\uranusjr\\documents\\playground\\project\\', 'c:\\users\\uranusjr\\documents\\playground\\project')
```

**Comment by uranusjr** [comment] 2018-10-23 18:40
I did some digging and it seems the most straightforward fix is to call an additional `os.path.normpath` in [`normalize_path`](https://github.com/pypa/setuptools/blob/e0433cf32dfdf39c0c14a3740c3920c496f09486/pkg_resources/__init__.py#L2223) to normalise the trailing slash:

```python
def normalize_path(filename):
    """Normalize a file/dir name for comparison purposes"""
    return os.path.normcase(os.path.normpath(os.path.realpath(filename)))
```

This seems reasonable based on the function’s docstring, but I am not sure how accurate it is, and whether the change would have more implications.

**Comment by pganssle** [comment] 2018-10-23 18:53
I think based on the file's docstring, it makes sense to add the additional `normpath` call in there, since these *should* compare equal. For example, `pathlib` has them compare equal:

```python
>>> pathlib.Path("path/to/file") == pathlib.Path("path/to/file/")
True
```

**Comment by davidism** [comment] 2018-10-24 15:09
I can reproduce this. Have been working to move [ItsDangerous](https://github.com/pallets/itsdangerous) and [MarkupSafe](https://github.com/pallets/markupsafe) to a `src` directory structure, and became unable to do `pip install -e .` for them on Windows. Oddly, Tox has no problem building an sdist and installing them in its testing envs.

**Comment by zmwangx** [comment] 2018-11-03 16:54
Just experienced this myself when I upgraded to Python 3.7.1. This is due to a regression in `ntpath.abspath` in 3.7.1 — [bpo-31047](https://bugs.python.org/issue31047), and addressed in [GH-10082](https://github.com/python/cpython/pull/10082), which has already landed. But the damage is done. Seeing that this is a Python regression, I'm not sure what's the best resolution either.

**Comment by pganssle** [comment] 2018-11-03 17:02
@zmwangx I think we're just waiting on a final approval on PR #1521, then the issue can be resolved.

**Comment by zmwangx** [comment] 2018-11-03 17:02
Oh I missed the PR. Thanks for the pointer.

**Closed** 2018-11-10 15:35 UTC
Labels: Needs Implementation, bug, good first issue, help wanted
