### ISSUE TITLE
Non-deterministic builds when SOURCES.txt already exists

### ISSUE THREAD

**Issue by tekumara** [pypa/setuptools#2347] opened 2020-08-29 11:08 UTC
If I have a project and run `python setup.py sdist` it reuses any existing SOURCES.txt. This makes distributions dependent on prior builds, rather than being deterministic.

An example setup.py:
```python
from setuptools import find_packages, setup

setup(
    name="foo",
    packages=find_packages(),
)
```

With the following directory layout:
```
.
├── foo
│   └── bar.py
└── setup.py
```

The first build includes bar.py:

<pre>
$ python setup.py sdist
running sdist
running egg_info
creating foo.egg-info
writing foo.egg-info/PKG-INFO
writing dependency_links to foo.egg-info/dependency_links.txt
writing top-level names to foo.egg-info/top_level.txt
writing manifest file 'foo.egg-info/SOURCES.txt'
reading manifest file 'foo.egg-info/SOURCES.txt'
writing manifest file 'foo.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt, README.md

running check
warning: check: missing required meta-data: url

warning: check: missing meta-data: either (author and author_email) or (maintainer and maintainer_email) must be supplied

creating foo-0.0.0
creating foo-0.0.0/foo
creating foo-0.0.0/foo.egg-info
copying files to foo-0.0.0...
copying setup.py -> foo-0.0.0
copying foo/__init__.py -> foo-0.0.0/foo
<b>copying foo/bar.py -> foo-0.0.0/foo</b>
copying foo.egg-info/PKG-INFO -> foo-0.0.0/foo.egg-info
copying foo.egg-info/SOURCES.txt -> foo-0.0.0/foo.egg-info
copying foo.egg-info/dependency_links.txt -> foo-0.0.0/foo.egg-info
copying foo.egg-info/top_level.txt -> foo-0.0.0/foo.egg-info
Writing foo-0.0.0/setup.cfg
creating dist
Creating tar archive
removing 'foo-0.0.0' (and everything under it)
</pre>

Now I remove \_\_init\_\_.py so foo/ is no longer a package:
```
$ rm foo/__init__.py   
```

But when I rebuild, bar.py is still included:
<pre>
$ python setup.py sdist
running sdist
running egg_info
writing foo.egg-info/PKG-INFO
writing dependency_links to foo.egg-info/dependency_links.txt
writing top-level names to foo.egg-info/top_level.txt
reading manifest file 'foo.egg-info/SOURCES.txt'
writing manifest file 'foo.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt, README.md

running check
warning: check: missing required meta-data: url

warning: check: missing meta-data: either (author and author_email) or (maintainer and maintainer_email) must be supplied

creating foo-0.0.0
creating foo-0.0.0/foo
creating foo-0.0.0/foo.egg-info
copying files to foo-0.0.0...
copying setup.py -> foo-0.0.0
<b>copying foo/bar.py -> foo-0.0.0/foo</b>
copying foo.egg-info/PKG-INFO -> foo-0.0.0/foo.egg-info
copying foo.egg-info/SOURCES.txt -> foo-0.0.0/foo.egg-info
copying foo.egg-info/dependency_links.txt -> foo-0.0.0/foo.egg-info
copying foo.egg-info/top_level.txt -> foo-0.0.0/foo.egg-info
Writing foo-0.0.0/setup.cfg
Creating tar archive
removing 'foo-0.0.0' (and everything under it)
</pre>

I can get a clean build only by removing SOURCES.txt first. Now bar.py is correctly omitted:
``` 
$ rm foo.egg-info/SOURCES.txt
$ python setup.py sdist
running sdist
running egg_info
writing foo.egg-info/PKG-INFO
writing dependency_links to foo.egg-info/dependency_links.txt
writing top-level names to foo.egg-info/top_level.txt
writing manifest file 'foo.egg-info/SOURCES.txt'
reading manifest file 'foo.egg-info/SOURCES.txt'
writing manifest file 'foo.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt, README.md

running check
warning: check: missing required meta-data: url

warning: check: missing meta-data: either (author and author_email) or (maintainer and maintainer_email) must be supplied

creating foo-0.0.0
creating foo-0.0.0/foo.egg-info
copying files to foo-0.0.0...
copying setup.py -> foo-0.0.0
copying foo.egg-info/PKG-INFO -> foo-0.0.0/foo.egg-info
copying foo.egg-info/SOURCES.txt -> foo-0.0.0/foo.egg-info
copying foo.egg-info/dependency_links.txt -> foo-0.0.0/foo.egg-info
copying foo.egg-info/top_level.txt -> foo-0.0.0/foo.egg-info
Writing foo-0.0.0/setup.cfg
Creating tar archive
removing 'foo-0.0.0' (and everything under it)
```

This was run using setuptools 49.6.0

**Comment by jaraco** [comment] 2020-08-30 20:08
Dupe of #436

**Closed by jaraco** 2020-08-30 20:08 UTC
