### ISSUE TITLE
setuptools using distutils issue with bugtrack_url

### ISSUE THREAD

**Issue by AraHaan** [pypa/setuptools#906] opened 2016-12-30 21:12 UTC
There is a problem when setuptools does this in 1 of the source files to define setup that is also exported from setuptools doing:

```py
setup = distutils.core.setup
```

The problem with this is that bugtrack_url is not realized by distutils and the people who manage that thought this is an issue with setuptools which I ensured them it is not because doing:

```py
from setuptools import setup
```

is the same as doing:

```py
from distutils.core import setup
```

The issue from this that I also reported on the python bug tracker is here: http://bugs.python.org/issue29115 feel free to tell them that setuptools and distribute actually uses their distutils setup function.

But yeah using a package that defines bugtrack_url in their package generates this even if they are using setuptools because of the usage of distutils:

```cmd
H:\Python\Python360\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'bugtrack_url'
  warnings.warn(msg)
```

I would like if setuptools took the actual setup function from distutils instead of doing:

```py
setup = distutils.core.setup
```

So that way setuptools can fix this bug as the standard library devs that manage distutils are too lazy to fix it themselves.

The reason why I have to use ``bugtrack_url`` is so my package would have a known bug track url on pypi.python.org. I also have another package that has one back when I could override it online manually but I can only do so much to bypass this and now there is no way I can edit it online on the package itself without having to worry about this stupid warning that literally discards the ``bugtrack_url`` option. So please fix this by **NOT** using the distutils setup function and instead copying that code over to setuptools and then make it able to know about ``bugtrack_url``. That other package that defines the bug track url is no longer valid and must so I must change the bug track url option sadly setuptools has the problem with discarding it all because of distutils.

**Comment by berkerpeksag** [comment] 2016-12-30 22:51
This is a duplicate of #29.

**Comment by AraHaan** [comment] 2016-12-30 22:57
So, basically we have to monkey patch ``distutils.core.Distribution``  to actually add that option in. hmm

**Comment by jaraco** [comment] 2016-12-31 02:39
Reading the upstream ticket, it appears that bugtrack_url isn't a suppported parameter.  

> There isn't anything we can do about this in the Python stdlib and neither can setuptools (except write a filter for it).
> It's probably best to let the package authors still using the keyword know that they have to remove the keyword settings from their setup.py.

If the field is something that should be included in package metadata, and the community has agreed on how (e.g. Through a pep), then it could and should be added as an option.

Note that distribution keywords is something that setup tools implements through entry points so it may also be possible for a third party to implement the desired behavior. Though I am on cold medicine, so take that not as a recommendation.

**Closed by jaraco** 2016-12-31 02:39 UTC

**Comment by AraHaan** [comment] 2016-12-31 02:45
I need to be able to get the bugtrack_url or reset it in one of my packages which I will now link: https://pypi.python.org/pypi/TinyURL3

**Comment by jaraco** [comment] 2016-12-31 14:26
More history: https://twitter.com/dstufft/status/274407214830190592

Looks like you can edit the field manually in PyPI. I suggest deleting it and forget it ever existed.

**Comment by AraHaan** [comment] 2016-12-31 15:28
Was*, cant do it anymore.

**Comment by AraHaan** [comment] 2017-01-01 11:51
Ok, they are working on the issue with unable to edit packages on pypi itself, turns out it was an regression and only I noticed it until I opened a bug report to them and they checked it out to see and sure enough they might try to fix it.

**Comment by jaraco** [comment] 2017-01-01 14:38
That's good to hear!
