### ISSUE TITLE
add an opt-out for packages that do not want to be installed as eggs ever

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pypa/setuptools#534] opened 2016-04-06 07:40 UTC
this us an alternative to #529 

instead of adding yet another feature to easy_install, packages would simply mark themselves as not compatible with the command, and need a pip call as installer

i strongly prefer packages opting out of egg installation over easy_install growing support for pip installation

**Comment by jaraco** [comment] 2016-04-16 16:16
This proposal won't be viable until pip is a viable replacement for easy_install, which it is not, primarily due to #250. I'd also be strongly opposed to any option that allows or encourages packages to be hostile to certain environments. I much prefer the options proposed in #250 and #406 and #529 to allow users to have more control over how packages are installed and get pip to a place where it's a suitable replacement for the use cases of easy_install.

What is it you imagine would happen if this proposal were enacted?

**Comment by jaraco** [comment] 2016-04-16 16:25
Is this ticket a duplicate of #375?

**Comment by RonnyPfannschmidt** [comment] 2018-05-27 13:27
@jaraco no, this one is about a package that does not want to be an egg, #375 is about not using easy_install implicitly for setup_requires

**Closed** 2020-06-09 08:24 UTC
Labels: Needs Triage
