### ISSUE TITLE
Hyphen in package name (in install_requires) causes confusion in some cases (eg SQLAlchemy / SQLAlchemy-Utils)

### ISSUE THREAD

**Issue by andrewcooke-isti** [pypa/setuptools#2336] opened 2020-08-19 16:37 UTC
Full details below.

In short, if the `install_requires` contains `'sqlalchemy','sqlalchemy-utils'` **in that order** then setup gives the error:

error: The 'sqlalchemy' distribution was not found and is required by ...

But if the order of those two packages is swapped, it works just fine.

------

I am on Centos 7, using Python 3.6 and running the following script to install a package:

```
$ cat sh/make-env.sh 
#!/bin/bash

if [ ! -d py ] || [ ! -d sh ] || [ ! -d db ]; then
    echo "run script from root directory"
    exit 1
fi

rm -fr env
python3 -m venv env
source env/bin/activate
pip install --upgrade pip setuptools wheel
pushd py
python setup.py develop
```

If I use this setup.py:

```$ cat py/setup.py
import setuptools

with open("../README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="stp-db",
    version="0.0.1",
    author="ISTI (Andrew Cooke)",
    author_email="andrewcooke@isti.com",
    description="Load STP data into a Postgres database",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://code.usgs.gov/EEW/stp-db",
    packages=setuptools.find_packages(),
    install_requires=[
        'psycopg2',
        'sqlalchemy',
        'sqlalchemy-utils',
        'configargparse',
        'colorlog'
    ],
    entry_points={
        'console_scripts': [
            'load_stp=stp_db.load_results:main'
        ]
    },
    classifiers=[
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.6',
)
```

then i see this output:

```
$ sh/make-env.sh 
Collecting pip
  Using cached https://files.pythonhosted.org/packages/5a/4a/39400ff9b36e719bdf8f31c99fe1fa7842a42fa77432e584f707a5080063/pip-20.2.2-py2.py3-none-any.whl
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/c3/a9/5dc32465951cf4812e9e93b4ad2d314893c2fa6d5f66ce5c057af6e76d85/setuptools-49.6.0-py3-none-any.whl
Collecting wheel
  Using cached https://files.pythonhosted.org/packages/a7/00/3df031b3ecd5444d572141321537080b40c1c25e1caa3d86cdd12e5e919c/wheel-0.35.1-py2.py3-none-any.whl
Installing collected packages: pip, setuptools, wheel
  Found existing installation: pip 9.0.3
    Uninstalling pip-9.0.3:
      Successfully uninstalled pip-9.0.3
  Found existing installation: setuptools 39.2.0
    Uninstalling setuptools-39.2.0:
      Successfully uninstalled setuptools-39.2.0
Successfully installed pip-20.2.2 setuptools-49.6.0 wheel-0.35.1
~/stp-db/py ~/stp-db
running develop
running egg_info
writing stp_db.egg-info/PKG-INFO
writing dependency_links to stp_db.egg-info/dependency_links.txt
writing entry points to stp_db.egg-info/entry_points.txt
writing requirements to stp_db.egg-info/requires.txt
writing top-level names to stp_db.egg-info/top_level.txt
reading manifest file 'stp_db.egg-info/SOURCES.txt'
writing manifest file 'stp_db.egg-info/SOURCES.txt'
running build_ext
Creating /home/andrew/stp-db/env/lib/python3.6/site-packages/stp-db.egg-link (link to .)
Adding stp-db 0.0.1 to easy-install.pth file
Installing load_stp script to /home/andrew/stp-db/env/bin

Installed /home/andrew/stp-db/py
Processing dependencies for stp-db==0.0.1
Searching for colorlog
Reading https://pypi.org/simple/colorlog/
Downloading https://files.pythonhosted.org/packages/2a/81/12d77537c82c5d46aa2721dfee25a0e873ef5920ebd0827152f411effb57/colorlog-4.2.1-py2.py3-none-any.whl#sha256=43597fd822ce705190fc997519342fdaaf44b9b47f896ece7aa153ed4b909c74
Best match: colorlog 4.2.1
Processing colorlog-4.2.1-py2.py3-none-any.whl
Installing colorlog-4.2.1-py2.py3-none-any.whl to /home/andrew/stp-db/env/lib/python3.6/site-packages
Adding colorlog 4.2.1 to easy-install.pth file

Installed /home/andrew/stp-db/env/lib/python3.6/site-packages/colorlog-4.2.1-py3.6.egg
Searching for configargparse
Reading https://pypi.org/simple/configargparse/
Downloading https://files.pythonhosted.org/packages/bb/79/3045743bb26ca2e44a1d317c37395462bfed82dbbd38e69a3280b63696ce/ConfigArgParse-1.2.3.tar.gz#sha256=edd17be986d5c1ba2e307150b8e5f5107aba125f3574dddd02c85d5cdcfd37dc
Best match: ConfigArgParse 1.2.3
Processing ConfigArgParse-1.2.3.tar.gz
Writing /tmp/easy_install-wdtdnxpk/ConfigArgParse-1.2.3/setup.cfg
Running ConfigArgParse-1.2.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-wdtdnxpk/ConfigArgParse-1.2.3/egg-dist-tmp-7pag0gw3
zip_safe flag not set; analyzing archive contents...
Moving ConfigArgParse-1.2.3-py3.6.egg to /home/andrew/stp-db/env/lib/python3.6/site-packages
Adding ConfigArgParse 1.2.3 to easy-install.pth file

Installed /home/andrew/stp-db/env/lib/python3.6/site-packages/ConfigArgParse-1.2.3-py3.6.egg
Searching for sqlalchemy-utils
Reading https://pypi.org/simple/sqlalchemy-utils/
Downloading https://files.pythonhosted.org/packages/14/68/e5301c4c960c79a32333b8805e52cb69d3d237aa869a773b4157ccb3eb26/SQLAlchemy-Utils-0.36.8.tar.gz#sha256=fb66e9956e41340011b70b80f898fde6064ec1817af77199ee21ace71d7d6ab0
Best match: SQLAlchemy-Utils 0.36.8
Processing SQLAlchemy-Utils-0.36.8.tar.gz
Writing /tmp/easy_install-6rqth3f2/SQLAlchemy-Utils-0.36.8/setup.cfg
Running SQLAlchemy-Utils-0.36.8/setup.py -q bdist_egg --dist-dir /tmp/easy_install-6rqth3f2/SQLAlchemy-Utils-0.36.8/egg-dist-tmp-d_va4wps
warning: no previously-included files matching '*.pyc' found under directory 'tests'
warning: no previously-included files matching '*.pyc' found under directory 'docs'
no previously-included directories found matching 'docs/_build'
warning: no previously-included files found matching 'docs/_themes/.git'
creating /home/andrew/stp-db/env/lib/python3.6/site-packages/SQLAlchemy_Utils-0.36.8-py3.6.egg
Extracting SQLAlchemy_Utils-0.36.8-py3.6.egg to /home/andrew/stp-db/env/lib/python3.6/site-packages
Adding SQLAlchemy-Utils 0.36.8 to easy-install.pth file

Installed /home/andrew/stp-db/env/lib/python3.6/site-packages/SQLAlchemy_Utils-0.36.8-py3.6.egg
Searching for sqlalchemy
Downloading https://files.pythonhosted.org/packages/14/68/e5301c4c960c79a32333b8805e52cb69d3d237aa869a773b4157ccb3eb26/SQLAlchemy-Utils-0.36.8.tar.gz#sha256=fb66e9956e41340011b70b80f898fde6064ec1817af77199ee21ace71d7d6ab0
Best match: SQLAlchemy Utils-0.36.8
Processing SQLAlchemy-Utils-0.36.8.tar.gz
Writing /tmp/easy_install-6pcjaun4/SQLAlchemy-Utils-0.36.8/setup.cfg
Running SQLAlchemy-Utils-0.36.8/setup.py -q bdist_egg --dist-dir /tmp/easy_install-6pcjaun4/SQLAlchemy-Utils-0.36.8/egg-dist-tmp-nm8c14br
warning: no previously-included files matching '*.pyc' found under directory 'tests'
warning: no previously-included files matching '*.pyc' found under directory 'docs'
no previously-included directories found matching 'docs/_build'
warning: no previously-included files found matching 'docs/_themes/.git'
removing '/home/andrew/stp-db/env/lib/python3.6/site-packages/SQLAlchemy_Utils-0.36.8-py3.6.egg' (and everything under it)
creating /home/andrew/stp-db/env/lib/python3.6/site-packages/SQLAlchemy_Utils-0.36.8-py3.6.egg
Extracting SQLAlchemy_Utils-0.36.8-py3.6.egg to /home/andrew/stp-db/env/lib/python3.6/site-packages
SQLAlchemy-Utils 0.36.8 is already the active version in easy-install.pth

Installed /home/andrew/stp-db/env/lib/python3.6/site-packages/SQLAlchemy_Utils-0.36.8-py3.6.egg
error: The 'sqlalchemy' distribution was not found and is required by stp-db
```

but if the lines are reversed

```
$ grep sqlal py/setup.py
        'sqlalchemy-utils',
        'sqlalchemy',
```

then the output is:

```
$ sh/make-env.sh 
Collecting pip
  Using cached https://files.pythonhosted.org/packages/5a/4a/39400ff9b36e719bdf8f31c99fe1fa7842a42fa77432e584f707a5080063/pip-20.2.2-py2.py3-none-any.whl
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/c3/a9/5dc32465951cf4812e9e93b4ad2d314893c2fa6d5f66ce5c057af6e76d85/setuptools-49.6.0-py3-none-any.whl
Collecting wheel
  Using cached https://files.pythonhosted.org/packages/a7/00/3df031b3ecd5444d572141321537080b40c1c25e1caa3d86cdd12e5e919c/wheel-0.35.1-py2.py3-none-any.whl
Installing collected packages: pip, setuptools, wheel
  Found existing installation: pip 9.0.3
    Uninstalling pip-9.0.3:
      Successfully uninstalled pip-9.0.3
  Found existing installation: setuptools 39.2.0
    Uninstalling setuptools-39.2.0:
      Successfully uninstalled setuptools-39.2.0
Successfully installed pip-20.2.2 setuptools-49.6.0 wheel-0.35.1
~/stp-db/py ~/stp-db
running develop
running egg_info
writing stp_db.egg-info/PKG-INFO
writing dependency_links to stp_db.egg-info/dependency_links.txt
writing entry points to stp_db.egg-info/entry_points.txt
writing requirements to stp_db.egg-info/requires.txt
writing top-level names to stp_db.egg-info/top_level.txt
reading manifest file 'stp_db.egg-info/SOURCES.txt'
writing manifest file 'stp_db.egg-info/SOURCES.txt'
running build_ext
Creating /home/andrew/stp-db/env/lib/python3.6/site-packages/stp-db.egg-link (link to .)
Adding stp-db 0.0.1 to easy-install.pth file
Installing load_stp script to /home/andrew/stp-db/env/bin

Installed /home/andrew/stp-db/py
Processing dependencies for stp-db==0.0.1
Searching for colorlog
Reading https://pypi.org/simple/colorlog/
Downloading https://files.pythonhosted.org/packages/2a/81/12d77537c82c5d46aa2721dfee25a0e873ef5920ebd0827152f411effb57/colorlog-4.2.1-py2.py3-none-any.whl#sha256=43597fd822ce705190fc997519342fdaaf44b9b47f896ece7aa153ed4b909c74
Best match: colorlog 4.2.1
Processing colorlog-4.2.1-py2.py3-none-any.whl
Installing colorlog-4.2.1-py2.py3-none-any.whl to /home/andrew/stp-db/env/lib/python3.6/site-packages
Adding colorlog 4.2.1 to easy-install.pth file

Installed /home/andrew/stp-db/env/lib/python3.6/site-packages/colorlog-4.2.1-py3.6.egg
Searching for configargparse
Reading https://pypi.org/simple/configargparse/
Downloading https://files.pythonhosted.org/packages/bb/79/3045743bb26ca2e44a1d317c37395462bfed82dbbd38e69a3280b63696ce/ConfigArgParse-1.2.3.tar.gz#sha256=edd17be986d5c1ba2e307150b8e5f5107aba125f3574dddd02c85d5cdcfd37dc
Best match: ConfigArgParse 1.2.3
Processing ConfigArgParse-1.2.3.tar.gz
Writing /tmp/easy_install-kal09a6m/ConfigArgParse-1.2.3/setup.cfg
Running ConfigArgParse-1.2.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-kal09a6m/ConfigArgParse-1.2.3/egg-dist-tmp-nb7yhr5u
zip_safe flag not set; analyzing archive contents...
Moving ConfigArgParse-1.2.3-py3.6.egg to /home/andrew/stp-db/env/lib/python3.6/site-packages
Adding ConfigArgParse 1.2.3 to easy-install.pth file

Installed /home/andrew/stp-db/env/lib/python3.6/site-packages/ConfigArgParse-1.2.3-py3.6.egg
Searching for sqlalchemy
Reading https://pypi.org/simple/sqlalchemy/
Downloading https://files.pythonhosted.org/packages/26/27/18dbd04360651192ec84940190d660c7bdb6bc73d50ebad9cabbea3c606c/SQLAlchemy-1.3.19-cp36-cp36m-manylinux1_x86_64.whl#sha256=8280f9dae4adb5889ce0bb3ec6a541bf05434db5f9ab7673078c00713d148365
Best match: SQLAlchemy 1.3.19
Processing SQLAlchemy-1.3.19-cp36-cp36m-manylinux1_x86_64.whl
Installing SQLAlchemy-1.3.19-cp36-cp36m-manylinux1_x86_64.whl to /home/andrew/stp-db/env/lib/python3.6/site-packages
Adding SQLAlchemy 1.3.19 to easy-install.pth file

Installed /home/andrew/stp-db/env/lib/python3.6/site-packages/SQLAlchemy-1.3.19-py3.6-linux-x86_64.egg
Searching for sqlalchemy-utils
Reading https://pypi.org/simple/sqlalchemy-utils/
Downloading https://files.pythonhosted.org/packages/14/68/e5301c4c960c79a32333b8805e52cb69d3d237aa869a773b4157ccb3eb26/SQLAlchemy-Utils-0.36.8.tar.gz#sha256=fb66e9956e41340011b70b80f898fde6064ec1817af77199ee21ace71d7d6ab0
Best match: SQLAlchemy-Utils 0.36.8
Processing SQLAlchemy-Utils-0.36.8.tar.gz
Writing /tmp/easy_install-awt4608h/SQLAlchemy-Utils-0.36.8/setup.cfg
Running SQLAlchemy-Utils-0.36.8/setup.py -q bdist_egg --dist-dir /tmp/easy_install-awt4608h/SQLAlchemy-Utils-0.36.8/egg-dist-tmp-0_nshz3i
warning: no previously-included files matching '*.pyc' found under directory 'tests'
warning: no previously-included files matching '*.pyc' found under directory 'docs'
no previously-included directories found matching 'docs/_build'
warning: no previously-included files found matching 'docs/_themes/.git'
creating /home/andrew/stp-db/env/lib/python3.6/site-packages/SQLAlchemy_Utils-0.36.8-py3.6.egg
Extracting SQLAlchemy_Utils-0.36.8-py3.6.egg to /home/andrew/stp-db/env/lib/python3.6/site-packages
Adding SQLAlchemy-Utils 0.36.8 to easy-install.pth file

Installed /home/andrew/stp-db/env/lib/python3.6/site-packages/SQLAlchemy_Utils-0.36.8-py3.6.egg
Searching for psycopg2
Reading https://pypi.org/simple/psycopg2/
Downloading https://files.pythonhosted.org/packages/a8/8f/1c5690eebf148d1d1554fc00ccf9101e134636553dbb75bdfef4f85d7647/psycopg2-2.8.5.tar.gz#sha256=f7d46240f7a1ae1dd95aab38bd74f7428d46531f69219954266d669da60c0818
Best match: psycopg2 2.8.5
Processing psycopg2-2.8.5.tar.gz
Writing /tmp/easy_install-ewj8wtpl/psycopg2-2.8.5/setup.cfg
Running psycopg2-2.8.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ewj8wtpl/psycopg2-2.8.5/egg-dist-tmp-pno4p5ow
zip_safe flag not set; analyzing archive contents...
psycopg2.__pycache__._psycopg.cpython-36: module references __file__
creating /home/andrew/stp-db/env/lib/python3.6/site-packages/psycopg2-2.8.5-py3.6-linux-x86_64.egg
Extracting psycopg2-2.8.5-py3.6-linux-x86_64.egg to /home/andrew/stp-db/env/lib/python3.6/site-packages
Adding psycopg2 2.8.5 to easy-install.pth file

Installed /home/andrew/stp-db/env/lib/python3.6/site-packages/psycopg2-2.8.5-py3.6-linux-x86_64.egg
Searching for six
Reading https://pypi.org/simple/six/
Downloading https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl#sha256=8b74bedcbbbaca38ff6d7491d76f2b06b3592611af620f8426e82dddb04a5ced
Best match: six 1.15.0
Processing six-1.15.0-py2.py3-none-any.whl
Installing six-1.15.0-py2.py3-none-any.whl to /home/andrew/stp-db/env/lib/python3.6/site-packages
Adding six 1.15.0 to easy-install.pth file

Installed /home/andrew/stp-db/env/lib/python3.6/site-packages/six-1.15.0-py3.6.egg
Finished processing dependencies for stp-db==0.0.1
```

**Comment by andrewcooke** [comment] 2020-08-19 18:43
also noticed this on another project that was working fine not so long back (my life seems to revolve around sqlalchemy projects right now), so i suspect it's a regression.

**Comment by jaraco** [comment] 2020-08-30 20:03
You've encountered #196. Because you're using `setup.py develop` instead of `pip install -e`, you're triggering the deprecated `easy_install` to install the dependencies, and `easy_install` has a known bug resolving dependencies that share a prefix followed by a dash. It installs `sqlalchemy-utils`, then when it goes to install `sqlalchemy`, it thinks it already has the "utils" version of "sqlalchemy" installed, which satisfies the requirement.

Just replace `python setup.py develop` with `python -m pip install -e .` or just `pip install -e .` and you should be happy.

**Closed by jaraco** 2020-08-30 20:03 UTC

**Comment by andrewcooke** [comment] 2020-08-30 20:13
ok, thanks (sorry for the dup).
