### ISSUE TITLE
AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'

### ISSUE THREAD

**Issue by Zlopez** [pypa/setuptools#1694] opened 2019-02-21 13:09 UTC
I'm trying to install project I'm working on using `pip3 install -e "file:///home/vagrant/devel"`, but everytime I end up with:
```
$> pip3 install -e "file:///home/vagrant/devel"
Obtaining file:///home/vagrant/devel
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  Complete output from command /home/vagrant/.virtualenvs/anitya/bin/python3 /home/vagrant/.virtualenvs/anitya/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp6db90a_q:
  Traceback (most recent call last):
    File "/home/vagrant/.virtualenvs/anitya/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/home/vagrant/.virtualenvs/anitya/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/vagrant/.virtualenvs/anitya/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 48, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/home/vagrant/.virtualenvs/anitya/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 39, in _build_backend
      obj = getattr(obj, path_part)
  AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'
```

Maybe I'm just doing something wrong, but this worked few days ago.

**Comment by Zlopez** [comment] 2019-02-21 13:32
I'm using python 3.7.2

**Comment by pganssle** [comment] 2019-02-21 14:04
As far as I know, this is triggered when all of the following conditions are met:

1. You are using a `virtualenv` with `--system-site-packages`
2. You are using `pip >= 19.0.2`
3. Your *system* version of `setuptools` is less than 40.8.0.
4. The package you are installing does not specify `build-backend="setuptools.build_meta"` in its `pyproject.toml`.

It is a bug in `pip`'s PEP 517 build isolation code: pypa/pip#6264.

The best way to fix it at the moment is to explicitly specify `build-backend="setuptools.build_meta"` in your `pyproject.toml`, [like this](https://github.com/tox-dev/tox/blob/master/pyproject.toml#L1). Note that you'll also want to put `pyproject.toml` in your `MANIFEST.in`.

Assuming you need `--system-site-packages` in your virtualenv, the second best way to solve this is to upgrade your system version of `setuptools`.

I'm going to close this issue as not a bug in `setuptools`, but thank you for the report. I recommend giving a +1 on the `pip` thread, or chiming in there if you managed to trigger this in a different way.

**Closed by pganssle** 2019-02-21 14:04 UTC

**Comment by Zlopez** [comment] 2019-02-21 14:31
Thank you for your response. I will check when `setuptools` will be updated on Fedora 29.

**Comment by pganssle** [comment] 2019-02-21 14:39
@Zlopez Oh, also `pip install -e . --no-use-pep517` may work, not sure - I think it depends on whether the package in question was relying on the PEP 518 dependency satisfaction or not.

**Comment by Zlopez** [comment] 2019-02-21 14:46
@pganssle Thanks, I will try this

**Comment by janPesl** [comment] 2019-08-14 12:30
When trying to install scipy module on Python 3.5.2,
[GCC 5.4.0 20160609] on linux, I keep running into the same error message using setuptools 41.1.0.
```
    File `"/usit/abel/u1/user/.local/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py",` line 39, in _build_backend
      obj = getattr(obj, path_part)
  AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usit/abel/u1/user/.local/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpr85rmcv9 Check the logs for full command output.
(virtualenv) janpesl@freebio:~$ pip3 install --upgrade setuptools
Requirement already up-to-date: setuptools in ./.local/lib/python3.5/site-packages (41.1.0)
```
What is the recommended fix?

**Comment by Zlopez** [comment] 2019-08-14 12:34
@janPesl for me the solution from @pganssle worked. See https://github.com/pypa/setuptools/issues/1694#issuecomment-466023567

**Comment by Jovons** [comment] 2020-06-11 07:11
Same problem. Setuptools: 47.1.1, python: 3.5.2, pip: 20.1.1 virtualenv: 16.3.0

**Comment by peteeckel** [comment] 2021-01-09 20:34
> @Zlopez Oh, also `pip install -e --no-use-pep517 'file://whatever/vagrant/devel'` may work, not sure - I think it depends on whether the package in question was relying on the PEP 518 dependency satisfaction or not.

It does. Thanks!
