### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by cnpante-gme** [pypa/setuptools#2669] opened 2021-05-10 16:15 UTC
### setuptools version

setuptools>=38.6.0

### Python version

Python 3.6

### OS

Virtual Box, Vagrant Debian 9

### Description

I am using vagrant and virtual box to run a webserver. I use vagrant tasks to setup python and setuptools:
```
- name: Install python 3.6 dependencies
  become: true
  apt: 
    name: [
      'python-setuptools',
      'build-essential',
      'checkinstall',
      'libreadline-gplv2-dev',
      'libncursesw5-dev',
      'libssl-dev',
      'libsqlite3-dev',
      'tk-dev',
      'libgdbm-dev',
      'libc6-dev',
      'libbz2-dev']
    state: present

- name: Extract python 3.6.3
  become: true
  unarchive:
    src: https://www.python.org/ftp/python/3.6.3/Python-3.6.3.tgz
    dest: /opt/
    remote_src: true
  args:
    creates: /opt/Python-3.6.3/configure
```

At the time when installing `requirements.txt` I get an error: 
```
Collecting diff-match-patch==20181111 (from -r requirements.txt (line 25))
  Using cached https://files.pythonhosted.org/packages/f0/2a/5ba07def0e9107d935aba62cf632afbd0f7c723a98af47ccbcab753d2452/diff-match-patch-20181111.tar.gz
    Complete output from command python setup.py egg_info:
    No local packages or working download links found for setuptools>=38.6.0
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-993wiqll/diff-match-patch/setup.py", line 37, in <module>
        install_requires=[],
      File "/usr/local/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/vagrant/apps/venvs/operations-software/lib/python3.6/site-packages/setuptools/dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/vagrant/apps/venvs/operations-software/lib/python3.6/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/vagrant/apps/venvs/operations-software/lib/python3.6/site-packages/pkg_resources/__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/vagrant/apps/venvs/operations-software/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "/home/vagrant/apps/venvs/operations-software/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1134, in obtain
        return installer(requirement)
      File "/home/vagrant/apps/venvs/operations-software/lib/python3.6/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/vagrant/apps/venvs/operations-software/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 659, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools>=38.6.0')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-993wiqll/diff-match-patch/
```

### Expected behavior

I should be able to install all in my `requirements.txt`

### How to Reproduce

This could be really hard with the vagrant and virtualbox. I think I just need possible reason of such error: `distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools>=38.6.0')`

and what things can I do?

I have tried `pip install --upgrade setuptools`, but my pip will try to look for compatible versions of my requirements.

```
Requirement already satisfied: setuptools in /home/vagrant/apps/venvs/operations-software/lib/python3.6/site-packages (from kiwisolver==1.1.0->-r requirements.txt (line 46)) (56.2.0)
INFO: pip is looking at multiple versions of tablib to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of sqlparse to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of snuggs to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of sklearn to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of six to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of shapely to determine which version is compatible with other requirements. This could take a while.
```

### Output

```console

```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by webknjaz** [comment] 2021-05-10 22:10
> [BUG] #2669

Please, fill out the issue title so that we could understand what it is you're asking about.

So... While it's not entirely obvious why you filed the issue on this specific tracker (it seems to belong elsewhere), I'll attempt to describe what I see here.

> setuptools>=38.6.0

It is important to understand that setuptools does not backport patches so one should always verify if the problem is reproducible with the latest release or even the main branch from Git. If something's been fixed in a newer release, it'd be pointless to keep such an issue open.

> Virtual Box

This is definitely not something setuptools maintainers support. You should seek support from the Virtualbox folks directly.

> using vagrant

This is another thing that is not going to be debugged by the setuptools maintainers.

> setup python and setuptools

That code snippet seems like an incomplete Ansible playbook. I don't think most of the maintainers are well-familiar with it. Normally, if you want to provide a reproducer for a problem with a project, you should demonstrate a sequence of steps only using the said project. If there's a problem with setuptools, we need a reproducer that uses setuptools and doesn't use third-party software.

But since I happen to know a thing or two about the said technologies, here's a few things that I find weird:
- you seem to attempt to install system-wide python-setuptools which is tightly coupled with the default system Python version but then you compile another CPython distribution in a separate location — these two will not play well together
- also note that debian usually ships old and/or patched setuptools (https://gist.github.com/tiran/2dec9e03c6f901814f6d1e8dad09528e) so if their patches influence your experience, it should be reported on their tracker as we have nothing to do with that
- it's usually easier to just use deadsnakes PPA on deb'ish distros (https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa / https://github.com/deadsnakes/docs/blob/master/Ansible.md) as they already have it compiled and well-packaged

> This could be really hard with the vagrant and virtualbox. I think I just need possible reason of such error: `distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools>=38.6.0')`

It's really hard to guess what happens exactly without a reproducer. I don't even know what command you run — you seem to imply that you don't want to use pip but at the same time you want `requirements.txt` installed which is mutually exclusive.

I'm pretty sure that the package that is causing trouble for you (`diff-match-patch`) is poorly packaged. First of all, there's no packaging infra at all in their repository (no `setup.py` etc) meaning that they generate it on the fly probably, before pushing to PyPI. You can only inspect what's inside that file by unpacking the dist tarball.
But even without looking into it, I can see a few problems in the traceback:
- it clearly has `from distutils.core import setup` which is deprecated and `from setuptools import setup` must be used in its place
- it seems to have that minimum setuptools version requirement either stated in `__requires__` or in `setup_requires` (also deprecated) in `setup.py` — build requirements are set in `pyproject.toml` (per PEP 517 / PEP 518) nowadays
- note that if they were to provide wheels, you, as a user, wouldn't have to deal with any of the build-related stuff

As for what to do: I think running `/home/vagrant/apps/venvs/operations-software/bin/python -m pip install setuptools pip wheel --upgrade` **before** installing from `requirements.txt` with probably solve most of your packaging problems.

P.S. Looking at https://pypi.org/project/diff-match-patch/20200713/#files, the latest release actually has a wheel so if you update your version pin to use a newer version, pip should just pick up a whl file and unzip it instead of trying to build from a source dist.

FWIW this does not look like a setuptools bug and doesn't seem to affect modern setuptools so I'm closing this issue.

**Closed by webknjaz** 2021-05-10 22:10 UTC
Labels: Needs Triage, bug
