### ISSUE TITLE
easy_install crashes

### ISSUE THREAD

**Issue by paullb514** [pypa/setuptools#978] opened 2017-02-19 06:10 UTC
I'm not sure what happened but easy_install now just crashes on the command line. 
i'm certainly no python expert so I'm not sure what happened, but it looks like an internal issue.

> bcmp-air:~ paullb$ easy_install
> Traceback (most recent call last):
>   File "/usr/local/bin/easy_install", line 7, in <module>
>     from setuptools.command.easy_install import main
>   File "/Library/Python/2.7/site-packages/setuptools/__init__.py", line 12, in <module>
>     import setuptools.version
>   File "/Library/Python/2.7/site-packages/setuptools/version.py", line 1, in <module>
>     import pkg_resources
>   File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
>     import packaging.requirements
>   File "/Library/Python/2.7/site-packages/packaging/requirements.py", line 59, in <module>
>     MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
> TypeError: __call__() takes exactly 2 arguments (1 given)

**Comment by jaraco** [comment] 2017-02-19 15:00
This is a duplicate of #969

**Closed by jaraco** 2017-02-19 15:00 UTC
Labels: duplicate
