### ISSUE TITLE
pkg_resources fails to find PyQt5

### ISSUE THREAD

**Issue by yurivict** [pypa/setuptools#2474] opened 2020-12-07 04:07 UTC
veusz-3.3.1 fails on FreeBSD 12.2:
```pkg_resources.DistributionNotFound: The 'PyQt5' distribution was not found and is required by veusz```

The testcase is:
```
$ cat test.py 
#!/usr/local/bin/python3.7

# EASY-INSTALL-ENTRY-SCRIPT: 'helloworld-qt==1.0.0','gui_scripts','helloworld-qt'
__requires__ = 'veusz==3.3.1'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('veusz==3.3.1', 'gui_scripts', 'veusz')()
    )
```

PyQt5 is installed:
```
$ pkg info | grep -i -- py37-qt5-
py37-qt5-core-5.15.0           Python bindings for the Qt5 toolkit, QtCore module
py37-qt5-gui-5.15.0            Python bindings for the Qt5 toolkit, QtGui module
py37-qt5-printsupport-5.15.0   Python bindings for the Qt5 toolkit, QtPrintSupport module
py37-qt5-svg-5.15.0            Python bindings for the Qt5 toolkit, QtSvg module
py37-qt5-widgets-5.15.0        Python bindings for the Qt5 toolkit, QtWidgets module
```

Regular PyQt5 testcases like this
```
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QVBoxLayout
app = QApplication([])
window = QWidget()
layout = QVBoxLayout()
layout.addWidget(QPushButton('Top'))
layout.addWidget(QPushButton('Bottom'))
window.setLayout(layout)
window.show()
app.exec_()
```
work fine.

So the problem is purely in setuptools.

This hasn't been fixed since this report in 2018: https://github.com/pypa/setuptools/issues/1445
Not sure why it was closed.

**Comment by yurivict** [comment] 2020-12-07 04:08
The problem seems to be in setuptools, I created a new report: https://github.com/pypa/setuptools/issues/2474

**Comment by jrollins** [comment] 2020-12-22 23:48
I am seeing this exact issue with a debian package of a pyqt5 app that uses an entry_point terminal script. It's not a 2->3 issue, since the app is purely python3 with python3-pyqt5.

**Comment by yurivict** [comment] 2021-02-22 07:29
3.3.1 still has this issue.

**Comment by benoit-pierre** [comment] 2021-02-22 17:49
As explained in #1445, pkg_resources relies on the proper metadata being available. Check if it's actually provided by your distribution package(s): there should be a `PyQt5-5.15.2.dist-info` directory in the site packages directory where the PyQt5 modules are installed. If you don't have this metadata, then there's nothing setuptools/pkg_resources can do about it: it's a distribution issue, and you'll have to work with the package(s) maintainer(s) to get this fixed.

**Comment by benoit-pierre** [comment] 2021-03-07 16:15
I'm going to go ahead and close this as a duplicate of #1445, feel free to re-open if you have more information that it's not.

**Closed by benoit-pierre** 2021-03-07 16:15 UTC
