### ISSUE TITLE
setuptools >= 48.0.0 broken in AIX for Python 3.7 

### ISSUE THREAD

**Issue by ayappanec** [pypa/setuptools#2367] opened 2020-09-01 09:44 UTC
Trying to build the master branch of scipy in AIX with python 3.7 fails with the below error message

Traceback (most recent call last):
File "/opt/freeware/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in
main()
File "/opt/freeware/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
json_out['return_val'] = hook(**hook_input['kwargs'])
File "/opt/freeware/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
return hook(config_settings)
File "/tmp/pip-build-env-9id221km/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 150, in get_requires_for_build_wheel
config_settings, requirements=['wheel'])
File "/tmp/pip-build-env-9id221km/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
self.run_setup()
File "/tmp/pip-build-env-9id221km/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 254, in run_setup
self).run_setup(setup_script=setup_script)
File "/tmp/pip-build-env-9id221km/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 145, in run_setup
exec(compile(code, file, 'exec'), locals())
File "setup.py", line 590, in
setup_package()
File "setup.py", line 586, in setup_package
setup(**metadata)
File "/tmp/pip-build-env-9id221km/overlay/lib/python3.7/site-packages/setuptools/init.py", line 152, in setup
_install_setup_requires(attrs)
File "/tmp/pip-build-env-9id221km/overlay/lib/python3.7/site-packages/setuptools/init.py", line 145, in _install_setup_requires
dist.parse_config_files(ignore_option_errors=True)
File "/tmp/pip-build-env-9id221km/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 665, in parse_config_files
self._parse_config_files(filenames=filenames)
File "/tmp/pip-build-env-9id221km/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 572, in _parse_config_files
filenames = self.find_config_files()
File "/tmp/pip-build-env-9id221km/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 350, in find_config_files
check_environ()
File "/tmp/pip-build-env-9id221km/overlay/lib/python3.7/site-packages/setuptools/_distutils/util.py", line 182, in check_environ
os.environ['PLAT'] = get_platform()
File "/tmp/pip-build-env-9id221km/overlay/lib/python3.7/site-packages/setuptools/_distutils/util.py", line 107, in get_platform
return get_host_platform()
File "/tmp/pip-build-env-9id221km/overlay/lib/python3.7/site-packages/setuptools/_distutils/util.py", line 82, in get_host_platform
from _aix_support import aix_platform
ModuleNotFoundError: No module named '_aix_support'

Looks like it's a problem with latest setuptools. _aix_support is added through this changeset python/cpython@39afa2d which targets python 3.9

**Comment by jaraco** [comment] 2020-09-01 15:29
Dupe of #2358.

**Closed** 2020-09-01 15:29 UTC
Labels: duplicate
