### ISSUE TITLE
Docs build fails with SphinX 2.0.0 under tox

### ISSUE THREAD

**Issue by webknjaz** [pypa/setuptools#1736] opened 2019-04-07 20:34 UTC
It doesn't fail in RTD, because RTD injects `sphinx<2`.

But:
```console
$ tox -e docs
docs create: ~/src/github/pypa/setuptools/.tox/docs
docs installdeps: -r~/src/github/pypa/setuptools/docs/requirements.txt
docs installed: alabaster==0.7.12,Babel==2.6.0,certifi==2019.3.9,chardet==3.0.4,docutils==0.14,idna==2.8,imagesize==1.1.0,jaraco.packaging==6.1,Jinja2==2.10.1,MarkupSafe==1.1.1,packaging==19.0,Pygments==2.3.1,pyparsing==2.3.1,python-dateutil==2.8.0,pytz==2018.9,requests==2.21.0,rst.linker==1.10,six==1.12.0,snowballstemmer==1.2.1,Sphinx==2.0.0,sphinxcontrib-applehelp==1.0.1,sphinxcontrib-devhelp==1.0.1,sphinxcontrib-htmlhelp==1.0.1,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-qthelp==1.0.2,sphinxcontrib-serializinghtml==1.1.3,urllib3==1.24.1
docs run-test-pre: PYTHONHASHSEED='2387760383'
docs run-test: commands[0] | python ~/src/github/pypa/setuptools/bootstrap.py
Regenerating egg_info
running egg_info
writing setuptools.egg-info/PKG-INFO
writing dependency_links to setuptools.egg-info/dependency_links.txt
writing entry points to setuptools.egg-info/entry_points.txt
writing requirements to setuptools.egg-info/requires.txt
writing top-level names to setuptools.egg-info/top_level.txt
reading manifest file 'setuptools.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching 'pyproject.toml'
writing manifest file 'setuptools.egg-info/SOURCES.txt'
...and again.
running egg_info
writing setuptools.egg-info/PKG-INFO
writing dependency_links to setuptools.egg-info/dependency_links.txt
writing entry points to setuptools.egg-info/entry_points.txt
writing requirements to setuptools.egg-info/requires.txt
writing top-level names to setuptools.egg-info/top_level.txt
reading manifest file 'setuptools.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching 'pyproject.toml'
writing manifest file 'setuptools.egg-info/SOURCES.txt'
docs run-test: commands[1] | sphinx-build -W -b html -d ~/src/github/pypa/setuptools/.tox/docs/tmp/doctrees docs docs/build/html
Running Sphinx v2.0.0
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 12 source files that are out of date
updating environment: 12 added, 0 changed, 0 removed
reading sources... [  8%] developer-guide
reading sources... [ 16%] development
reading sources... [ 25%] easy_install
reading sources... [ 33%] ez_setup
reading sources... [ 41%] formats
reading sources... [ 50%] history
reading sources... [ 58%] index
reading sources... [ 66%] pkg_resources
reading sources... [ 75%] python3
reading sources... [ 83%] releases
reading sources... [ 91%] roadmap
reading sources... [100%] setuptools

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  8%] developer-guide
writing output... [ 16%] development
writing output... [ 25%] easy_install
writing output... [ 33%] ez_setup
writing output... [ 41%] formats
writing output... [ 50%] history
writing output... [ 58%] index

Theme error:
An error happened in rendering the page index.
Reason: TemplateNotFound()
ERROR: InvocationError for command ~/src/github/pypa/setuptools/.tox/docs/bin/sphinx-build -W -b html -d ~/src/github/pypa/setuptools/.tox/docs/tmp/doctrees docs docs/build/html (exited with code 2)
___________________________________________________________________________________________ summary ___________________________________________________________________________________________
ERROR:   docs: commands failed
```

And also `sphinx < 2` prints this warning:
```console
~/src/github/pypa/setuptools/.tox/docs/lib/python3.7/site-packages/sphinx/builders/html.py:1171: RemovedInSphinx20Warning: Now html_sidebars only allows list of sidebar templates as a value. Support for a string value will be removed at Sphinx-2.0.
  self.add_sidebars(pagename, ctx)
```

**Comment by pganssle** [comment] 2019-07-23 14:05
Closed as duplicate of #1565

**Closed by pganssle** 2019-07-23 14:05 UTC
Labels: duplicate
