### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-t_utKw/pyodbc/

### ISSUE THREAD

**Issue by 9antriksh** [pypa/setuptools#1654] opened 2019-01-28 05:44 UTC
Getting this error for setuptools 40.7.0 only if I downgrade to 40.6.3 it works

`Collecting pyodbc==4.0.1
  Downloading 
https://files.pythonhosted.org/packages/09/2c/74d615f544292b160e4547a5f16609da7907fd802a1e8
873b45c07db6837/pyodbc-4.0.1.tar.gz (190kB)
    100% |████████████████████████████████| 194kB 332kB/s
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/pyodbc.egg-info
    writing pip-egg-info/pyodbc.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/pyodbc.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/pyodbc.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/pyodbc.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-t_utKw/pyodbc/setup.py", line 293, in <module>
        main()
      File "/tmp/pip-install-t_utKw/pyodbc/setup.py", line 112, in main
        setup(**kwargs)
      File "/home/user/.local/share/virtualenvs/project-_pLCgLR7/lib/python2.7/site-
packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/user/.local/share/virtualenvs/project-_pLCgLR7/lib/python2.7/site-
packages/setuptools/command/egg_info.py", line 296, in run
        self.find_sources()
      File "/home/user/.local/share/virtualenvs/project-_pLCgLR7/lib/python2.7/site-
packages/setuptools/command/egg_info.py", line 303, in find_sources
        mm.run()
      File "/home/user/.local/share/virtualenvs/project-_pLCgLR7/lib/python2.7/site-
packages/setuptools/command/egg_info.py", line 534, in run
        self.add_defaults()
      File "/home/user/.local/share/virtualenvs/project-_pLCgLR7/lib/python2.7/site-
packages/setuptools/command/egg_info.py", line 570, in add_defaults
        sdist.add_defaults(self)
      File "/home/user/.local/share/virtualenvs/project-_pLCgLR7/lib/python2.7/site-
packages/setuptools/command/py36compat.py", line 36, in add_defaults
        self._add_defaults_ext()
      File "/home/user/.local/share/virtualenvs/project-_pLCgLR7/lib/python2.7/site-
packages/setuptools/command/py36compat.py", line 119, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "/usr/lib64/python2.7/distutils/cmd.py", line 312, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/lib64/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "/home/user/.local/share/virtualenvs/project-_pLCgLR7/lib/python2.7/site-
packages/setuptools/command/build_ext.py", line 133, in finalize_options
 _build_ext.finalize_options(self)
File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 159, in finalize_options
self.include_dirs.append(py_include)
AttributeError: 'unicode' object has no attribute 'append'`

**Comment by 9antriksh** [comment] 2019-01-28 05:50
Downgrade to 40.6.3
`pip install setuptools==40.6.3`

**Comment by benoit-pierre** [comment] 2019-01-28 09:32
Another likely issue due to #1180.

**Comment by benoit-pierre** [comment] 2019-01-28 16:55
Closing as duplicate of #1653.

**Closed by benoit-pierre** 2019-01-28 16:55 UTC
Labels: duplicate
