### ISSUE TITLE
Maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by floppym** [pypa/setuptools#946] opened 2017-01-26 03:53 UTC
Some of our users are reporting recursion error when building python packages after upgrading to setuptools-34.0.2. Any tips on how we can figure out what is happening here?

https://bugs.gentoo.org/show_bug.cgi?id=607164

```
  File "/var/tmp/portage/dev-python/setuptools-34.0.2-r1/work/setuptools-34.0.2-python2_7/setuptools/dist.py", line 386, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/var/tmp/portage/dev-python/setuptools-34.0.2-r1/work/setuptools-34.0.2-python2_7/pkg_resources/__init__.py", line 2318, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/var/tmp/portage/dev-python/setuptools-34.0.2-r1/work/setuptools-34.0.2-python2_7/pkg_resources/__init__.py", line 851, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/var/tmp/portage/dev-python/setuptools-34.0.2-r1/work/setuptools-34.0.2-python2_7/pkg_resources/__init__.py", line 1123, in best_match
    return self.obtain(req, installer)
  File "/var/tmp/portage/dev-python/setuptools-34.0.2-r1/work/setuptools-34.0.2-python2_7/pkg_resources/__init__.py", line 1135, in obtain
    return installer(requirement)
  File "/var/tmp/portage/dev-python/setuptools-34.0.2-r1/work/setuptools-34.0.2-python2_7/setuptools/dist.py", line 417, in fetch_build_egg
    dist = self.__class__({'script_args': ['easy_install']})
  File "/var/tmp/portage/dev-python/setuptools-34.0.2-r1/work/setuptools-34.0.2-python2_7/setuptools/dist.py", line 320, in __init__
    _Distribution.__init__(self, attrs)
  File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/var/tmp/portage/dev-python/setuptools-34.0.2-r1/work/setuptools-34.0.2-python2_7/setuptools/dist.py", line 386, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/var/tmp/portage/dev-python/setuptools-34.0.2-r1/work/setuptools-34.0.2-python2_7/pkg_resources/__init__.py", line 2318, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/var/tmp/portage/dev-python/setuptools-34.0.2-r1/work/setuptools-34.0.2-python2_7/pkg_resources/__init__.py", line 844, in resolve
    env = Environment(self.entries)
  File "/var/tmp/portage/dev-python/setuptools-34.0.2-r1/work/setuptools-34.0.2-python2_7/pkg_resources/__init__.py", line 1051, in __init__
    self.scan(search_path)
  File "/var/tmp/portage/dev-python/setuptools-34.0.2-r1/work/setuptools-34.0.2-python2_7/pkg_resources/__init__.py", line 1080, in scan
    for dist in find_distributions(item):
  File "/var/tmp/portage/dev-python/setuptools-34.0.2-r1/work/setuptools-34.0.2-python2_7/pkg_resources/__init__.py", line 2010, in find_on_path
    path_item_entries = _by_version_descending(os.listdir(path_item))
  File "/var/tmp/portage/dev-python/setuptools-34.0.2-r1/work/setuptools-34.0.2-python2_7/pkg_resources/__init__.py", line 1994, in _by_version_descending
    return sorted(names, key=_by_version, reverse=True)
  File "/var/tmp/portage/dev-python/setuptools-34.0.2-r1/work/setuptools-34.0.2-python2_7/pkg_resources/__init__.py", line 1992, in _by_version
    return [packaging.version.parse(part) for part in parts]
  File "/usr/lib64/python2.7/site-packages/packaging/version.py", line 31, in parse
    return Version(version)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by s1113950** [comment] 2017-01-26 07:19
@floppym See here: https://github.com/pypa/setuptools/issues/944#issuecomment-275238738 I found a temporary solution to this; I demoed the upgrade in new docker containers with a very old setuptools (3.3) upgrading to 34.0.2

**Comment by jaraco** [comment] 2017-01-28 14:54
The issue here appears to be that something is calling `easy_install` to `fetch_build_eggs`. It's difficult to tell when or why this issue is triggered without more information, like which commands cause this error and what output happens prior. If I had to guess, though, the issue is that setuptools is missing its (new) dependencies and is trying to resolve them itself.

Please dig into the build scripts in Gentoo and distill the steps that you need to enact in a clean environment to replicate the error, at which point we should be able to describe the cause.

**Comment by floppym** [comment] 2017-01-29 02:16
A build log is here: https://bugs.gentoo.org/attachment.cgi?id=461384

I cannot reproduce the problem myself, so giving you "distilled" steps to reproduce it is difficult. At a high level, the source tarball is unpacked, and we run `/usr/bin/python2.7 setup.py build`.

The build dependencies stated in the package metadata are below.
```
    >=dev-python/packaging-16.8
    >=dev-python/six-1.10.0
    >=dev-python/appdirs-1.4.0-r1
```

**Comment by floppym** [comment] 2017-01-29 02:24
It is worth noting that the build process is being run in a private network namespace, with no access to outside systems. Fetching packages from pypi should fail in this case (not produce an infinite recursion).

**Comment by jaraco** [comment] 2017-01-29 15:10
The issue begins when at setuptools.dist:386, when setuptools is resolving the entry points for `distutils.setup_keywords`, which should resolve immediately without attempting to install anything. It's hard to be certain, but the entrypoint is likely referring to one of the `setuptools` entry points, and so it's the installer that's detecting that setuptools or one of its dependencies isn't installed.

Since you say the dependencies are installed, perhaps it's the case that they're installed in a way that's not recognized by pkg_resources.

Are you able to inject commands into the process? What happens if before setup.py build, you invoke `-c "import pkg_resources; print(pkg_resources.require('setuptools'))"`?

**Comment by floppym** [comment] 2017-01-29 15:59
That's doable. I have asked that someone perform this test on the Gentoo bug report.

**Comment by Grokzen** [comment] 2017-01-29 19:38
@jaraco I just started to get almost the same problem but with a different stack trace.

```
File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 292, in fetch_build_egg
    dist = self.__class__({'script_args':['easy_install']})
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 243, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 276, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2100, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer)))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 292, in fetch_build_egg
    dist = self.__class__({'script_args':['easy_install']})
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 243, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 276, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2100, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer)))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 292, in fetch_build_egg
    dist = self.__class__({'script_args':['easy_install']})
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 243, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 276, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2100, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer)))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 613, in resolve
    env = Environment(self.entries)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 782, in __init__
    self.scan(search_path)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 811, in scan
    for dist in find_distributions(item):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1773, in find_distributions
    importer = get_importer(path_item)
  File "/usr/lib/python2.7/pkgutil.py", line 394, in get_importer
    importer = ImpImporter(path_item)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

I run the following command inside a docker container

```
easy_install -U setuptools>=11.3
```

With the following setup/tools installed when executing the command

```
root@5577db2d4278:/# easy_install --version
setuptools 3.3
root@5577db2d4278:/# python --version
Python 2.7.6
root@5577db2d4278:/# pip --version
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg (python 2.7)
root@5577db2d4278:/# pip freeze
chardet==2.0.1
colorama==0.2.5
html5lib==0.999
pycurl==7.19.3
python-apt===0.9.3.5ubuntu1
requests==2.2.1
six==1.5.2
urllib3==1.7.1
```

When trying to install through pip there is no problem

**Comment by jaraco** [comment] 2017-02-03 20:22
Setuptools 34 specifically drops support for upgrading itself. I wouldn't expect `easy_install -U setuptools` to work unless `six>=1.6` and late `appdirs` and `packaging` are already installed (see setup.py for specific dependencies. Before 34.0.3, it required `six>=1.10.0`. Using `pip` is the best approach.

**Comment by FelikZ** [comment] 2017-04-14 10:22
`pip install -u setuptools pip` - helped me

**Comment by jaraco** [comment] 2017-05-31 00:06
Setuptools 36 restores support for self install by vendoring dependencies again.

**Closed by jaraco** 2017-05-31 00:06 UTC
