### ISSUE TITLE
Resolve multiple extras requirements for repeated requires entries

### ISSUE THREAD

**Issue by david-caro** [pypa/setuptools#696] opened 2016-07-27 10:47 UTC
For example, right now, if you have something like:

```
setup(
    ...
    extras_require={
        'withmysql': ['something[mysql]'],
    },
    install_requires=['something'],
...
)
```

running pip install -e withmysql will install 'something' and not 'something[mysql]'. I'm not sure if I'm using it wrong, but being able to resolve those dependencies by adding all the 'extras' would be the best solution imo.

Of course, if the version pattern on any of them is not the same as the others, it should probably complain, or ignore the latest conflicting entries (hopefully with a warn message or something).

**Comment by david-caro** [comment] 2016-07-27 15:20
I've sent a pull request to pip to handle it pypa/pip#3878 (I think that's where it's handled, not here).

**Comment by jaraco** [comment] 2016-07-30 00:45
Given that the issue is about pip and it's filed in pip, I'm closing here.

**Closed by jaraco** 2016-07-30 00:45 UTC
Labels: invalid
