### ISSUE TITLE
[BUG] Setuptools 64+ has incorrect entry point "dist.module_path"

### ISSUE THREAD

**Issue by djhoese** [pypa/setuptools#3527] opened 2022-08-15 17:03 UTC
### setuptools version

setuptools>=64.0.0

### Python version

Python 3.9

### OS

PopOS

### Description

When installing a package in editable mode with setuptools 64+ the resulting `entry_point.dist.module_path` points to the environment's `site-packages` instead of the location of the editable package source. This makes it impossible or at least not backwards compatible to get the location of an entry point's content (package data).

### Expected behavior

See the reproduction code below for exact expected values, but:

```
import pkg_resources
for entry_point in pkg_resources.iter_entry_points('a'):
    print(entry_point.dist.module_path)
```

I expect this to print the path to the package source that defined this entry point. It currently prints the path to `site-packages` (ex. `/home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages`).

### How to Reproduce

1. Create environment with setuptools installed.
2. Running the following bash commands or equivalent:

   ```bash
   cd /tmp
   mkdir -p mypkg/mypkg
   touch mypkg/mypkg/__init__.py
   ```
3. Create a pyproject.toml file in `/tmp/mypkg/pyproject.toml`:

   ```toml
   [project]
   name = "mypkg"
   version = "1.0.0"

   [tool.setuptools]
   packages = ["mypkg"]

   [project.entry-points.a]
   b = "c"

   [build-system]
   requires = ["setuptools>=64", "wheel"]
   build-backend = "setuptools.build_meta"
   ```
4. Create a `setup.py` file in `/tmp/mypkg/setup.py`:

   ```python
   from setuptools import setup
   setup()
   ```
5. Change to another directory to make sure you don't have access to `mypkg` by relative path: `cd ~`
6. Install the package in editable mode: `pip install -e /tmp/mypkg`
7. Run this example from bash:

   ```bash
   python <<EOF
   import pkg_resources
   for entry_point in pkg_resources.iter_entry_points('a'):
       print(entry_point.dist.module_path)
   EOF
   ```
8. Note the output is `site-packages`.
9. Change the pyproject.toml to use `<64` for setuptools, rerun `pip install -e /tmp/mypkg`, rerun above example and note the `/tmp/mypkg` result.

### Output

```console
$ cd /tmp
$ mkdir -p mypkg/mypkg
$ cd mypkg/
$ touch mypkg/__init__.py
$ vim pyproject.toml
$ vim setup.py
$ pip install -e .
Obtaining file:///tmp/mypkg
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Installing collected packages: mypkg
  Running setup.py develop for mypkg
Successfully installed mypkg-1.0.0
$ cd
$ python <<EOF
import pkg_resources
for entry_point in pkg_resources.iter_entry_points('a'):
    print(entry_point.module_name, entry_point.dist.module_path)

EOF
c /home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages

$ vim /tmp/mypkg/pyproject.toml  # change to <64
$ pip install -e /tmp/mypkg/
Obtaining file:///tmp/mypkg
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Installing collected packages: mypkg
  Attempting uninstall: mypkg
    Found existing installation: mypkg 1.0.0
    Uninstalling mypkg-1.0.0:
      Successfully uninstalled mypkg-1.0.0
  Running setup.py develop for mypkg
Successfully installed mypkg-1.0.0
$ python <<EOF
import pkg_resources
for entry_point in pkg_resources.iter_entry_points('a'):
    print(entry_point.module_name, entry_point.dist.module_path)

EOF
c /tmp/mypkg

$ vim /tmp/mypkg/pyproject.toml  # change to >=65 to make sure newer releases don't have important fixes
(satpy_py39) davidh@janet:~$ pip install -e /tmp/mypkg/
Obtaining file:///tmp/mypkg
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Building wheels for collected packages: mypkg
  Building editable for mypkg (pyproject.toml) ... done
  Created wheel for mypkg: filename=mypkg-1.0.0-0.editable-py3-none-any.whl size=2416 sha256=211f0d8240461cc126ad04f35d91b63b0523be802c23fd70328653bd7a1ea4d1
  Stored in directory: /tmp/pip-ephem-wheel-cache-n61anp3q/wheels/96/83/6b/d7d48eba2f2b8a9e7c44cf04a809888c8783c06cbbf4c7991d
Successfully built mypkg
Installing collected packages: mypkg
  Attempting uninstall: mypkg
    Found existing installation: mypkg 1.0.0
    Uninstalling mypkg-1.0.0:
      Successfully uninstalled mypkg-1.0.0
Successfully installed mypkg-1.0.0
$ python <<EOF
import pkg_resources
for entry_point in pkg_resources.iter_entry_points('a'):
    print(entry_point.module_name, entry_point.dist.module_path)

EOF
c /home/davidh/miniconda3/envs/satpy_py39/lib/python3.9/site-packages

$ cat /tmp/mypkg/pyproject.toml
[project]
name = "mypkg"
version = "1.0.0"

[tool.setuptools]
packages = ["mypkg"]

[project.entry-points.a]
b = "c"

[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

$ cat /tmp/mypkg/setup.py
from setuptools import setup
setup()
```

**Comment by abravalheri** [comment] 2022-08-15 17:55
Hi @djhoese, thank you very much for bringing this up for discussion.

For flat-layout projects the new implementation uses import hooks instead of a static `.pth` file, so I am not exactly sure how is the expected behaviour for that scenario.

I have a few questions:

- Do you have a link for where the `module_path` API is defined? I tried to look for it to understand exactly what should be the return value, but I could not find.

- Does the same error happens if you use the equivalent in `importlib_resources`? (`pkg_resources` is deprecated)

**Comment by djhoese** [comment] 2022-08-15 18:28
I don't know about documentation for `module_path`, I'm only maintaining/updating some code that someone else wrote that used it. I had no idea pkg_resources is deprecated and only just noticed the "discouraged" paragraph at the top of https://setuptools.pypa.io/en/latest/pkg_resources.html#. A nice red disclaimer/warning might help that page in the future. I will try importlib resources and get back to you.

**Comment by abravalheri** [comment] 2022-08-15 18:32
Sorry for the inconvenience @djhoese. Let me know if you need help, I can also try to submit a PR to the project to replace with `importlib_resources` if you point me out which parts of the script are problematic.

**Comment by djhoese** [comment] 2022-08-15 18:54
Thanks for the offer. Even if I didn't write this code originally I'm still a core developer of the library so still my responsibility. I was the one who chose to update things to be pyproject.toml-only so this is definitely in my umbrella of responsibility now.

As for importlib, it seems to work but it points out that my example is invalid. The `c` is meant to represent the package where this entry point was defined, but that package doesn't exist. If I do my real world case with my satpy library or manually type 'mypkg' for the module name then it works.

```
In [1]: import importlib.resources as impr
In [2]: from importlib.metadata import entry_points
In [3]: eps = entry_points()
In [4]: ep = eps['satpy.composites'][0]
In [5]: ep.module
Out[5]: 'satpy_cpe'
In [6]: impr.files(ep.module)
Out[6]: PosixPath('/home/davidh/repos/git/satpy-composites-plugin-example/satpy_cpe')

# from my example above
In [4]: ep = eps['a'][0]
In [5]: ep.module
Out[5]: 'c'

# Will fail: In [6]: impr.files(ep.module)

In [7]: impr.files('mypkg')
Out[7]: PosixPath('/tmp/mypkg/mypkg')
```

So I think this can be closed in the sense that importlib seems to handle things fine. Depending on what type of backwards compatibility you/setuptools was hoping for, things no longer work with pkg_resources.

Feel free to close this.

**Comment by abravalheri** [comment] 2022-08-15 19:09
Thank you very much @djhoese.

> I had no idea pkg_resources is deprecated and only just noticed the "discouraged" paragraph.

You are right, maybe I am jumping ahead and rushing to conclude it is deprecated.

But considering the `module_path` is not documented in the [API page](https://setuptools.pypa.io/en/latest/pkg_resources.html) and that it is not clear what it should represent in the case of import hook, I will (at lease momentarily) close this issue.

If anyone else is experience problems due to the change, I recommend also trying the suitable replacements from `importlib` (or `importlib_resources`/`importlib_metadata`). If those are no possibile, please let me know and we can re-debate/re-open this issue.

**Closed by abravalheri** 2022-08-15 19:09 UTC
Labels: bug, Needs Triage
