### ISSUE TITLE
"--requires" flag is broken in all versions of Python.

### ISSUE THREAD

**Issue by e4p** [pypa/setuptools#1181] opened 2017-10-26 23:22 UTC
When I run `python setupy.py --help` I see the following tantalizing option:

` --requires          print the list of packages/modules required`

But using it simply prints a newline to stdout. I've tried this on in 2.7/3.4 on my local Ubuntu install as well as on 2.7, 3.4, 3.5 and 3.6 CPython Docker images.

Expected behavior:
```
$ git clone https://github.com/pypa/sampleproject.git
$ cd sampleproject
$ python setup.py --requires
peppercorn
```

Observed behavior.

```
$ git clone https://github.com/pypa/sampleproject.git
$ cd sampleproject
$ python setup.py --requires

$ python3.4 setup.py --requires

```

**Comment by benoit-pierre** [comment] 2017-10-27 07:00
Duplicate of https://github.com/pypa/setuptools/issues/1153.

**Closed** 2017-10-27 14:39 UTC
