### ISSUE TITLE
sdist with --dist-dir on Windows produces incorrect archive

### ISSUE THREAD

**Issue by ofek** [pypa/setuptools#1185] opened 2017-11-02 21:00 UTC
@jaraco

Using a relative path works as expected (`python setup.py sdist --dist-dir dist`) 

![good](https://user-images.githubusercontent.com/9677399/32349696-54c457d4-bfee-11e7-9c37-e65e14de6feb.PNG)

however using an absolute path (`python setup.py sdist --dist-dir C:\Users\Ofek\Desktop\mypkg\dist`) includes the entire path structure starting at the drive/root

![bad](https://user-images.githubusercontent.com/9677399/32349952-2eb47492-bfef-11e7-89c1-feab6d3d0ac9.PNG)

**Comment by jaraco** [comment] 2017-11-13 15:55
It seems the issue does not happen on Unix:

```
$ cat > setup.py
__import__('setuptools').setup(name='mypkg', version='1')
$ python setup.py sdist --dist-dir=$(pwd)/dist --formats=zip,gztar
running sdist
running egg_info
writing mypkg.egg-info/PKG-INFO
writing dependency_links to mypkg.egg-info/dependency_links.txt
writing top-level names to mypkg.egg-info/top_level.txt
reading manifest file 'mypkg.egg-info/SOURCES.txt'
writing manifest file 'mypkg.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt, README.md

running check
warning: check: missing required meta-data: url

warning: check: missing meta-data: either (author and author_email) or (maintainer and maintainer_email) must be supplied

creating mypkg-1
creating mypkg-1/mypkg.egg-info
copying files to mypkg-1...
copying setup.py -> mypkg-1
copying mypkg.egg-info/PKG-INFO -> mypkg-1/mypkg.egg-info
copying mypkg.egg-info/SOURCES.txt -> mypkg-1/mypkg.egg-info
copying mypkg.egg-info/dependency_links.txt -> mypkg-1/mypkg.egg-info
copying mypkg.egg-info/top_level.txt -> mypkg-1/mypkg.egg-info
Writing mypkg-1/setup.cfg
creating '/Users/jaraco/yg/work/dist/mypkg-1.zip' and adding 'mypkg-1' to it
adding 'mypkg-1/PKG-INFO'
adding 'mypkg-1/setup.py'
adding 'mypkg-1/setup.cfg'
adding 'mypkg-1/mypkg.egg-info/PKG-INFO'
adding 'mypkg-1/mypkg.egg-info/SOURCES.txt'
adding 'mypkg-1/mypkg.egg-info/top_level.txt'
adding 'mypkg-1/mypkg.egg-info/dependency_links.txt'
Creating tar archive
removing 'mypkg-1' (and everything under it)
$ ls -la dist
total 16
drwxr-xr-x   4 jaraco  staff   128 Nov 13 10:50 .
drwxr-xr-x  10 jaraco  staff   320 Nov 13 10:51 ..
-rw-r--r--   1 jaraco  staff   570 Nov 13 10:51 mypkg-1.tar.gz
-rw-r--r--   1 jaraco  staff  1363 Nov 13 10:51 mypkg-1.zip
$ tar tzf dist/mypkg-1.tar.gz 
mypkg-1/
mypkg-1/PKG-INFO
mypkg-1/mypkg.egg-info/
mypkg-1/mypkg.egg-info/PKG-INFO
mypkg-1/mypkg.egg-info/SOURCES.txt
mypkg-1/mypkg.egg-info/top_level.txt
mypkg-1/mypkg.egg-info/dependency_links.txt
mypkg-1/setup.py
mypkg-1/setup.cfg
$ rwt -q openpack -- -m openpack.zip-listdir dist/mypkg-1.zip     
d mypkg-1
```

So the issue seems to be isolated to Windows.

**Comment by jaraco** [comment] 2017-11-13 16:16
Since sdist is largely implemented in distutils, I suspect the issue lies in the upstream implementation. Can you confirm the issue happens if you use distutils without setuptools?

**Comment by ofek** [comment] 2017-11-13 17:54
@jaraco Sure! What would those imports be?

**Comment by ofek** [comment] 2018-02-06 23:29
*respectful bump*

**Comment by jaraco** [comment] 2018-02-10 19:14
I tried replicating the issue on Windows with just distutils and could not. Here's the setup script I created:

```
__import__('distutils.core').core.setup(name='mypkg', version='1')
```

However, when I tried to replicate your experience in Setuptools, I can't make it happen:

```
PS C:\Users\jaraco\m\setuptools-1185> py -m easy_install --version
setuptools 38.5.1 from c:\python36\lib\site-packages (Python 3.6)
PS C:\Users\jaraco\m\setuptools-1185> cat setup.py
__import__('setuptools').setup(name='mypkg', version='1')
PS C:\Users\jaraco\m\setuptools-1185> py setup.py sdist --dist-dir=c:\Users\jaraco\dist
running sdist
running egg_info
writing mypkg.egg-info\PKG-INFO
writing dependency_links to mypkg.egg-info\dependency_links.txt
writing top-level names to mypkg.egg-info\top_level.txt
reading manifest file 'mypkg.egg-info\SOURCES.txt'
writing manifest file 'mypkg.egg-info\SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt, README.md

running check
warning: check: missing required meta-data: url

warning: check: missing meta-data: either (author and author_email) or (maintainer and maintainer_email) must be supplied

creating mypkg-1
creating mypkg-1\mypkg.egg-info
copying files to mypkg-1...
copying setup.py -> mypkg-1
copying mypkg.egg-info\PKG-INFO -> mypkg-1\mypkg.egg-info
copying mypkg.egg-info\SOURCES.txt -> mypkg-1\mypkg.egg-info
copying mypkg.egg-info\dependency_links.txt -> mypkg-1\mypkg.egg-info
copying mypkg.egg-info\top_level.txt -> mypkg-1\mypkg.egg-info
Writing mypkg-1\setup.cfg
creating c:\Users\jaraco\dist
Creating tar archive
removing 'mypkg-1' (and everything under it)
PS C:\Users\jaraco\m\setuptools-1185> py -m tarfile -l C:\users\jaraco\dist\mypkg-1.tar.gz
mypkg-1/
mypkg-1/PKG-INFO
mypkg-1/mypkg.egg-info/
mypkg-1/mypkg.egg-info/PKG-INFO
mypkg-1/mypkg.egg-info/SOURCES.txt
mypkg-1/mypkg.egg-info/top_level.txt
mypkg-1/mypkg.egg-info/dependency_links.txt
mypkg-1/setup.py
mypkg-1/setup.cfg
```

Even on Python 2 with distutils:

```
PS C:\Users\jaraco\m\setuptools-1185> cat .\setup-distutils.py
__import__('distutils.core').core.setup(name='mypkg', version='1')
PS C:\Users\jaraco\m\setuptools-1185> py -2 setup-distutils.py sdist --dist-dir=c:\users\jaraco\dist --formats=gztar
running sdist
running check
warning: check: missing required meta-data: url

warning: check: missing meta-data: either (author and author_email) or (maintainer and maintainer_email) must be supplied

warning: sdist: manifest template 'MANIFEST.in' does not exist (using default file list)

warning: sdist: standard file not found: should have one of README, README.txt

writing manifest file 'MANIFEST'
creating mypkg-1
copying files to mypkg-1...
copying setup-distutils.py -> mypkg-1
Creating tar archive
removing 'mypkg-1' (and everything under it)
PS C:\Users\jaraco\m\setuptools-1185> py -m tarfile -l C:\users\jaraco\dist\mypkg-1.tar.gz
mypkg-1/
mypkg-1/PKG-INFO
mypkg-1/setuptools-distutils.py
```

Whatever is happening in your environment isn't happening in mine. I suspect you either have an old version of setuptools or Python that has a bug that's since been fixed.

If you can find a way to replicate the issue with the latest Python and setuptools, please try with just distutils and report back here.

For now I'm going to close this ticket, but I'll certainly re-open if the issue can be replicated.

**Comment by Kaiser1989** [comment] 2020-06-04 07:15
Still a problem. Don't use py -m tarfile to test. Just unzip it with 7zip or anything else.
I don't want to provide my datastructure to others

**Comment by jaraco** [comment] 2020-06-27 01:02
Kaiser reported more details in the duplicate ticket:

> Do NOT test the tar.gz with "python -m tarfile", as this unpacks the tar.gz at once, and therefore showing the correct content. To reproduce, unpack the tar.gz file with 7zip. The "tar" archive contains the correct content. But the "gz" archive provides the full local path.

I also had a question I'd like to see answered:

> Do I understand correctly that there is no undesirable user-facing behavior, that the only problem is the leaking of local paths in the gzip file? I do agree it would be nice not to leak that information.

**Comment by jaraco** [comment] 2020-06-27 01:39
[Here's where the tarfile gets created](https://github.com/python/cpython/blob/2e0a920e9eb540654c0bb2298143b00637dc5961/Lib/distutils/archive_util.py#L107-L111). It doesn't do anything special with filenames. It just calls [TarFile.add](https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.add).

Can you supply some test that runs on Python that illustrates the undesirable behavior? I'm not even sure it's possible using the Python APIs to affect the name that appears in 7-Zip.

**Comment by ArtemSBulgakov** [comment] 2020-07-16 18:48
This is issue of tarfile. It incorrectly writes header for GZIP compression when user gives path with directories as name to [TarFile.add](https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.add). I created an issue at b.p.o. https://bugs.python.org/issue41316 and fixed this by PR https://github.com/python/cpython/pull/21511

**Comment by StefanD986** [comment] 2020-09-07 12:40
I also stumbled upon this bug when building using `python -m pep517.build .` I assume the [pep517 package ](https://pypi.org/project/pep517/) uses dist-dir somewhere internally.

Would be great if this could be merged soon because it limits the usefulness of pep517 on windows platforms.

**Comment by ArtemSBulgakov** [comment] 2020-12-24 14:42
[My fix](https://github.com/python/cpython/pull/21511) for the tarfile module is included in Python [3.8.7](https://docs.python.org/3.8/whatsnew/changelog.html#python-3-8-7-release-candidate-1) and [3.9.1](https://docs.python.org/3.9/whatsnew/changelog.html#python-3-9-1-release-candidate-1). This issue can be closed.

**Comment by jaraco** [comment] 2020-12-25 03:57
Well done. Thanks Artem!

**Comment by jaraco** [comment] 2021-03-12 15:18
Setuptools can still help by making sure that the fix is included in pypa/distutils and merged with this project. Indeed, that will be necessary to avoid a regression for users using `SETUPTOOLS_USE_DISTUTILS=local` or future versions that rely on adopted distutils exclusively.

**Comment by jaraco** [comment] 2021-03-12 15:35
On further examination, I see that the fix is in `tarfile` and not `distutils`, so the previous comment is incorrect. The only option is to use an updated Python or for someone to backport tarfile.

**Closed by jaraco** 2021-03-12 15:35 UTC
Labels: invalid
