### ISSUE TITLE
Having both virtualenv and virtualenv-clone as dependencies make setup() fail

### ISSUE THREAD

**Issue by giuscri** [pypa/setuptools#1291] opened 2018-03-15 11:53 UTC
As I understand this when searching for `virtualenv`, virtualenv-clone is considered a match (even a better one).

Note that:
* if install_requires consists of only `virtualenv` or virtualenv-clone install or develop go well.
* after failing if you retry to install, `virtualenv` is correctly fetched.

```
$ cat msetup.py
from setuptools import setup

required = ['virtualenv', 'virtualenv-clone']

setup(install_requires=required)
```

```
$ deactivate; rm -rf ~/pipenv-venv/; virtualenv ~/pipenv-venv/; source ~/pipenv-venv/bin/activate; python msetup.py install
Using base prefix '/usr'
New python executable in /home/g/pipenv-venv/bin/python
Installing setuptools, pip, wheel...done.
running install
running bdist_egg
running egg_info
writing UNKNOWN.egg-info/PKG-INFO
writing dependency_links to UNKNOWN.egg-info/dependency_links.txt
writing requirements to UNKNOWN.egg-info/requires.txt
writing top-level names to UNKNOWN.egg-info/top_level.txt
...
Extracting UNKNOWN-0.0.0-py3.6.egg to /home/g/pipenv-venv/lib/python3.6/site-packages
Adding UNKNOWN 0.0.0 to easy-install.pth file

Installed /home/g/pipenv-venv/lib/python3.6/site-packages/UNKNOWN-0.0.0-py3.6.egg
Processing dependencies for UNKNOWN==0.0.0
Searching for virtualenv-clone
Reading https://pypi.python.org/simple/virtualenv-clone/
Downloading https://pypi.python.org/packages/6d/c2/dccb5ccf599e0c5d1eea6acbd058af7a71384f9740179db67a9182a24798/virtualenv_clone-0.3.0-py2.py3-none-any.whl#md5=4c4678b4db796fbbe911ae74262a5f1d
Best match: virtualenv-clone 0.3.0
Processing virtualenv_clone-0.3.0-py2.py3-none-any.whl
Installing virtualenv_clone-0.3.0-py2.py3-none-any.whl to /home/g/pipenv-venv/lib/python3.6/site-packages
Adding virtualenv-clone 0.3.0 to easy-install.pth file
Installing virtualenv-clone script to /home/g/pipenv-venv/bin

Installed /home/g/pipenv-venv/lib/python3.6/site-packages/virtualenv_clone-0.3.0-py3.6.egg
Searching for virtualenv
Downloading https://pypi.python.org/packages/14/2f/84b6a8e380439cdfdb71e0ced2a805a66e343ac540d3304bde6bc28fbb46/virtualenv-clone-0.3.0.tar.gz#md5=6137126d81221f529c2552acbe304ec7
Best match: virtualenv clone-0.3.0
Processing virtualenv-clone-0.3.0.tar.gz
Writing /tmp/easy_install-v3cxbx06/virtualenv-clone-0.3.0/setup.cfg
Running virtualenv-clone-0.3.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-v3cxbx06/virtualenv-clone-0.3.0/egg-dist-tmp-366j2tjr
zip_safe flag not set; analyzing archive contents...
removing '/home/g/pipenv-venv/lib/python3.6/site-packages/virtualenv_clone-0.3.0-py3.6.egg' (and everything under it)
Moving virtualenv_clone-0.3.0-py3.6.egg to /home/g/pipenv-venv/lib/python3.6/site-packages
virtualenv-clone 0.3.0 is already the active version in easy-install.pth
Installing virtualenv-clone script to /home/g/pipenv-venv/bin

Installed /home/g/pipenv-venv/lib/python3.6/site-packages/virtualenv_clone-0.3.0-py3.6.egg
error: The 'virtualenv' distribution was not found and is required by UNKNOWN
```

**Comment by benoit-pierre** [comment] 2018-03-15 11:57
Duplicate of  #498, as a work around, try changing the order.

**Closed by benoit-pierre** 2018-03-15 11:57 UTC
Labels: duplicate
