### ISSUE TITLE
Install setuptools 36.2.1 through exception

### ISSUE THREAD

**Issue by nooperpudd** [pypa/setuptools#1101] opened 2017-07-24 05:31 UTC
OS:[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Python version: 3.6.2
pip version: 9.0.1
setuptools install version : 36.2.0
```Exception:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/locations.py", line 140, in distutils_scheme
    d = Distribution(dist_args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/dist.py", line 365, in __init__
    self._finalize_requires()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/dist.py", line 372, in _finalize_requires
    if not self.install_requires:
AttributeError: 'Distribution' object has no attribute 'install_requires'
```

**Comment by benoit-pierre** [comment] 2017-07-24 05:36
Duplicate of #1086.

**Comment by akszydelko** [comment] 2017-07-24 14:06
Getting the same error on new version 36.2.2, which were suppose to fix that as described in #1086.
I'm trying to update form version 36.2.0.

**Comment by benoit-pierre** [comment] 2017-07-24 14:08
The problem occurs when upgrading/downgrading setuptools from 36.2.0, with pip, and from source. What command do you use?

**Comment by akszydelko** [comment] 2017-07-24 14:13
`pip install -r requirements.txt --upgrade`

I do not have setuptools in my requirements, so it's a dependency of some other package.

**Comment by benoit-pierre** [comment] 2017-07-24 14:20
Do you have a directive to disable wheels support in your `requirements.txt`?

**Comment by akszydelko** [comment] 2017-07-24 14:29
No, just a list of packages, should I?

**Comment by benoit-pierre** [comment] 2017-07-24 14:37
I can only reproduce the issue if I force pip to install from source:
```bash
>  uname -s -m -o
Linux x86_64 GNU/Linux
> python --version
Python 3.6.2
> python -m venv env
> ./env/bin/pip install 'setuptools==36.2.0'
Collecting setuptools==36.2.0
  Using cached setuptools-36.2.0-py2.py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: setuptools 28.8.0
> ./env/bin/pip freeze --all
pip==9.0.1
setuptools==36.2.0
> ./env/bin/pip install --upgrade setuptools
Collecting setuptools
  Using cached setuptools-36.2.2-py2.py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: setuptools 36.2.0
    Uninstalling setuptools-36.2.0:
      Successfully uninstalled setuptools-36.2.0
Successfully installed setuptools-36.2.2
> ./env/bin/pip install 'setuptools==36.2.0'
Collecting setuptools==36.2.0
  Using cached setuptools-36.2.0-py2.py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: setuptools 36.2.2
    Uninstalling setuptools-36.2.2:
      Successfully uninstalled setuptools-36.2.2
Successfully installed setuptools-36.2.0
> ./env/bin/pip install --upgrade --no-binary :all: setuptools
Collecting setuptools
  Using cached setuptools-36.2.2.zip
Installing collected packages: setuptools
  Found existing installation: setuptools 36.2.0
    Uninstalling setuptools-36.2.0:
      Successfully uninstalled setuptools-36.2.0
  Running setup.py install for setuptools ... done
Exception:
Traceback (most recent call last):
  File "env/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "env/lib/python3.6/site-packages/pip/commands/install.py", line 350, in run
    isolated=options.isolated_mode,
  File "env/lib/python3.6/site-packages/pip/commands/install.py", line 436, in get_lib_location_guesses
    scheme = distutils_scheme('', *args, **kwargs)
  File "/home/bpierre/progs/src/tmp/env/lib/python3.6/site-packages/pip/locations.py", line 140, in distutils_scheme
    d = Distribution(dist_args)
  File "env/lib/python3.6/site-packages/setuptools/dist.py", line 365, in __init__
    Convert requirements in `extras_require` of the form
  File "env/lib/python3.6/site-packages/setuptools/dist.py", line 372, in _finalize_requires
    for r in pkg_resources.parse_requirements(v):
AttributeError: 'Distribution' object has no attribute 'install_requires'
```
Can you try upgrading setuptools by itself? And post the full log.

**Comment by akszydelko** [comment] 2017-07-24 14:56
Ok, upgrading on it's own works fine:
```
$ pip install --upgrade setuptools
Collecting setuptools
  Using cached setuptools-36.2.2-py2.py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: setuptools 36.2.0
    Uninstalling setuptools-36.2.0:
      Successfully uninstalled setuptools-36.2.0
Successfully installed setuptools-36.2.2
```

But I have found which package is causing the issue, when I install it through `pip install -r requirements.txt --upgrade`. It's actually a fork of mine, take a look https://github.com/akszydelko/django-positions.

I have changed some code there, but nothing in terms of package installation.

I am including this fork as follow in my requirements.txt:
```
git+git://github.com/akszydelko/django-positions.git#egg=positions
```

To complete the story here is the log of failing installation of all packages:
```
$ pip install -r htdocs/requirements/server/dev.txt --upgrade
Requirement already up-to-date: django==1.10.6 in ./venv/lib/python3.4/site-packages (from -r htdocs/requirements/server/../base.txt (line 1))
Requirement already up-to-date: pillow==4.0.0 in ./venv/lib/python3.4/site-packages (from -r htdocs/requirements/server/../base.txt (line 2))
Requirement already up-to-date: psycopg2==2.7.1 in ./venv/lib/python3.4/site-packages (from -r htdocs/requirements/server/../base.txt (line 3))
Requirement already up-to-date: requests==2.12.3 in ./venv/lib/python3.4/site-packages (from -r htdocs/requirements/server/../base.txt (line 4))
Requirement already up-to-date: httpagentparser==1.7.8 in ./venv/lib/python3.4/site-packages (from -r htdocs/requirements/server/../base.txt (line 6))
Requirement already up-to-date: django-annoying==0.10.3 in ./venv/lib/python3.4/site-packages (from -r htdocs/requirements/server/../base.txt (line 7))
Requirement already up-to-date: django-compressor==2.1 in ./venv/lib/python3.4/site-packages (from -r htdocs/requirements/server/../base.txt (line 8))
Requirement already up-to-date: django-tinymce==2.4.0 in ./venv/lib/python3.4/site-packages (from -r htdocs/requirements/server/../base.txt (line 9))
Requirement already up-to-date: sorl-thumbnail==12.3 in ./venv/lib/python3.4/site-packages (from -r htdocs/requirements/server/../base.txt (line 10))
Requirement already up-to-date: django-taggit==0.21.3 in ./venv/lib/python3.4/site-packages (from -r htdocs/requirements/server/../base.txt (line 11))
Requirement already up-to-date: django-jstemplate==1.3.8 in ./venv/lib/python3.4/site-packages (from -r htdocs/requirements/server/../base.txt (line 12))
Requirement already up-to-date: mailchimp==2.0.9 in ./venv/lib/python3.4/site-packages (from -r htdocs/requirements/server/../base.txt (line 13))
Requirement already up-to-date: django-js-reverse==0.7.3 in ./venv/lib/python3.4/site-packages (from -r htdocs/requirements/server/../base.txt (line 14))
Requirement already up-to-date: django_extensions==1.7.7 in ./venv/lib/python3.4/site-packages (from -r htdocs/requirements/server/../base.txt (line 15))
Requirement already up-to-date: uwsgi==2.0.14 in ./venv/lib/python3.4/site-packages (from -r htdocs/requirements/server/dev.txt (line 3))
Collecting positions from git+git://github.com/akszydelko/django-positions.git#egg=positions (from -r htdocs/requirements/server/dev.txt (line 4))
  Cloning git://github.com/akszydelko/django-positions.git to /tmp/pip-build-4rsujma1/positions
  Running setup.py (path:/tmp/pip-build-4rsujma1/positions/setup.py) egg_info for package positions produced metadata for project name django-positions. Fix your #egg=positions fragments.
Requirement already up-to-date: olefile in ./venv/lib/python3.4/site-packages (from pillow==4.0.0->-r htdocs/requirements/server/../base.txt (line 2))
Requirement already up-to-date: rcssmin==1.0.6 in ./venv/lib/python3.4/site-packages (from django-compressor==2.1->-r htdocs/requirements/server/../base.txt (line 8))
Requirement already up-to-date: django-appconf>=1.0 in ./venv/lib/python3.4/site-packages (from django-compressor==2.1->-r htdocs/requirements/server/../base.txt (line 8))
Requirement already up-to-date: rjsmin==1.0.12 in ./venv/lib/python3.4/site-packages (from django-compressor==2.1->-r htdocs/requirements/server/../base.txt (line 8))
Requirement already up-to-date: six in ./venv/lib/python3.4/site-packages (from django-jstemplate==1.3.8->-r htdocs/requirements/server/../base.txt (line 12))
Requirement already up-to-date: docopt==0.4.0 in ./venv/lib/python3.4/site-packages (from mailchimp==2.0.9->-r htdocs/requirements/server/../base.txt (line 13))
Collecting setuptools (from django-positions->-r htdocs/requirements/server/dev.txt (line 4))
  Using cached setuptools-36.2.2-py2.py3-none-any.whl
Installing collected packages: setuptools, django-positions
  Found existing installation: setuptools 36.2.0
    Uninstalling setuptools-36.2.0:
      Successfully uninstalled setuptools-36.2.0
  Rolling back uninstall of setuptools
Exception:
Traceback (most recent call last):
  File "/home/www/dev.doktor-medi.pl/venv/lib/python3.4/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/www/dev.doktor-medi.pl/venv/lib/python3.4/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/www/dev.doktor-medi.pl/venv/lib/python3.4/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/www/dev.doktor-medi.pl/venv/lib/python3.4/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/www/dev.doktor-medi.pl/venv/lib/python3.4/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/www/dev.doktor-medi.pl/venv/lib/python3.4/site-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/home/www/dev.doktor-medi.pl/venv/lib/python3.4/site-packages/pip/locations.py", line 140, in distutils_scheme
    d = Distribution(dist_args)
  File "/home/www/dev.doktor-medi.pl/venv/lib/python3.4/site-packages/setuptools/dist.py", line 365, in __init__
    self._finalize_requires()
  File "/home/www/dev.doktor-medi.pl/venv/lib/python3.4/site-packages/setuptools/dist.py", line 372, in _finalize_requires
    if not self.install_requires:
AttributeError: 'Distribution' object has no attribute 'install_requires'
```

So maybe there is something wrong with the fork, but it worked like that for quite a time.

**Comment by benoit-pierre** [comment] 2017-07-24 15:54
OK, `pip install --upgrade 'git+git://github.com/akszydelko/django-positions.git#egg=positions'` does trigger the issue too. The only solution is really to upgrade setuptools by itself **before** installing the requirements...

As to the reason as why the bug only occurs in some cases, it seems to be due to the way setuptools monkey-patches distutils. More precisely, the sequence of events triggering the bug are:
- setuptools is imported, has a result `distutils.dist.Distribution` has been monkey-patched to `setuptools.dist.Distribution`
- setuptools is uninstalled
- pip's code tries to create a Distribution object, but `setuptools.dist.Distribution` is used

This result in weird behavior in setuptools' code... I have not looked more deeply than that. But if I were to take a guess, I'd say maybe the use of entry-points (dynamic import) for some of setuptools own features is the culprit.

Case in point, applying the following patch to pip fix the issue:
```diff
diff --git i/pip/locations.py w/pip/locations.py
index e598ef10..94c98535 100644
--- i/pip/locations.py
+++ w/pip/locations.py
@@ -12,6 +12,25 @@ from distutils.command.install import install, SCHEME_KEYS  # noqa
 from pip.compat import WINDOWS, expanduser
 from pip.utils import appdirs
 
+# If setuptools is installed, make sure its entry-points are loaded,
+# so we don't end up in a weird state when it's uninstalled but
+# `distutils.dist.Distribution` is still monkey-patched to use
+# `setuptools.dist.Distribution`.
+try:
+    import setuptools
+except ImportError:
+    pass
+else:
+    import pkg_resources
+    for ep_type in (
+        'distutils.setup_keywords',
+        'distutils.commands',
+        'setuptools.installation',
+        'egg_info.writers'
+    ):
+        for ep in pkg_resources.iter_entry_points(ep_type):
+            if ep.dist.project_name == 'setuptools':
+                ep.load()
 
 # Application Directories
 USER_CACHE_DIR = appdirs.user_cache_dir("pip")
```

I don't know if that patch would be considered as acceptable for inclusion in pip, but this could prevent those kind of weird bugs (and allow for maybe some minor simplifications in setuptools' code).

@dstufft, @jaraco: thoughts?

**Comment by akszydelko** [comment] 2017-07-24 16:13
Wow, thanks for the research. So I think I will just update the setuptools manually and go along with that.

If you will use django-positions as a further issue triggering case, you can use the origin repo https://github.com/jpwatts/django-positions and install normally `pip install django-positions --upgrade`.
I have noticed that they finally merged my fix, so I have replaced my fork with the package name `django-positions==0.5.5` to get rid of installation through git repo. But the setuptools upgrade issue remained. So you do not have to bother with `git+git...` stuff.

Thanks again and good luck with pip improvements ;)

**Comment by benoit-pierre** [comment] 2017-08-06 15:38
Duplicate of #1086.

**Closed by benoit-pierre** 2017-08-06 15:38 UTC
