### ISSUE TITLE
[BUG] Unable to install `pkgutil`-style namespace package with `src`-layout

### ISSUE THREAD

**Issue by chrysle** [pypa/setuptools#4116] opened 2023-11-17 17:24 UTC
### setuptools version

setuptools=68.2.2

### Python version

Python 3.10.12

### OS

Ubuntu 22.04

### Additional environment information

I'm running this as a Docker container, as seen below.

### Description

I tried installing a `pkgutil`-style namespace package (inside a `venv` environment) migrated to `src`-layout. I know that's discouraged, but it serves for demonstration purposes (taken from [this repo](https://github.com/pypa/sample-namespace-packages)). I'd have expected it's Python 3.10-compatible. Afterwards, I tried to import the installed package from the project root directory. The module wasn't found, although it was listed by `pip`.

### Expected behavior

I expected to be able to import the namespace package and its sub-package `a` correctly after installing with `pip`.

### How to Reproduce

1. Clone the test package running `git clone https://github.com/pypa/sample-namespace-packages/tree/master/pkgutil`
2. **Migrate `pkgutil/pkg_a/` to `src`-layout** 
3. Launch it into a Docker environment: `docker run --rm -it -v ./pkgutil:/tmp/pkgutil ubuntu:22.04 /bin/bash`
4. Install necessary dependencies: `apt install python3-pip python3-venv`
5. Change working directory with `cd /tmp/pkgutil/pkg_a/`
6. Create a virtual environment and activate it: `python3 -m venv .venv/ && source .venv/bin/activate`
7. Install `wheel` to the virtualenv: `python3 -m pip install wheel`
8. Install the package with `python3 -m pip install .`
9. Change cwd to `/tmp/` and try importing the package with `cd /tmp/ && python3 -c "import example_pkg"`
10. Observe the failure and the confusing output of `python3 -m pip list`
11. Move to `flat`-layout and observe it's working

### Output

```console
....
root@6e4b0572c1cd:/tmp# tree pkgutil/
pkgutil/
|-- README.md
|-- pkg_a
|   |-- setup.py
|   `-- src
|       `-- example_pkg
|           |-- __init__.py
|           `-- a
|               |-- __init__.py
`-- pkg_b
    |-- setup.py
    `-- src
        `-- example_pkg
            |-- __init__.py
            `-- b
                |-- __init__.py
root@6e4b0572c1cd:/tmp# python3 -m venv .venv/
root@6e4b0572c1cd:/tmp# source .venv/bin/activate
(.venv) root@6e4b0572c1cd:/tmp# python3 -m pip install wheel
Collecting wheel
  Downloading wheel-0.41.3-py3-none-any.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.8/65.8 KB 1.2 MB/s eta 0:00:00
Installing collected packages: wheel
Successfully installed wheel-0.41.3
(.venv) root@6e4b0572c1cd:/tmp# python3 -m pip install --upgrade pip setuptools
Requirement already satisfied: pip in ./.venv/lib/python3.10/site-packages (22.0.2)
Collecting pip
  Downloading pip-23.3.1-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 6.0 MB/s eta 0:00:00
Requirement already satisfied: setuptools in ./.venv/lib/python3.10/site-packages (59.6.0)
Collecting setuptools
  Downloading setuptools-68.2.2-py3-none-any.whl (807 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 807.9/807.9 KB 6.4 MB/s eta 0:00:00
Installing collected packages: setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 59.6.0
    Uninstalling setuptools-59.6.0:
      Successfully uninstalled setuptools-59.6.0
  Attempting uninstall: pip
    Found existing installation: pip 22.0.2
    Uninstalling pip-22.0.2:
      Successfully uninstalled pip-22.0.2
Successfully installed pip-23.3.1 setuptools-68.2.2
(.venv) root@6e4b0572c1cd:/tmp# cd pkgutil/pkg_a/
(.venv) root@6e4b0572c1cd:/tmp/pkgutil/pkg_a# which python3
/tmp/.venv/bin/python3
(.venv) root@6e4b0572c1cd:/tmp/pkgutil/pkg_a# python3 -m pip install .
Processing /tmp/pkgutil/pkg_a
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: example-pkg-a
  Building wheel for example-pkg-a (setup.py) ... done
  Created wheel for example-pkg-a: filename=example_pkg_a-1-py3-none-any.whl size=1018 sha256=ad312d40658595a186fb87b0800bfb66f38a843f39684ff2e16284ea58f63067
  Stored in directory: /tmp/pip-ephem-wheel-cache-ew9d1v8q/wheels/65/b4/5f/13f92372b8f8b831dae39c654d8148beb33930870ccba2f54c
Successfully built example-pkg-a
Installing collected packages: example-pkg-a
Successfully installed example-pkg-a-1
(.venv) root@6e4b0572c1cd:/tmp/pkgutil/pkg_a# cd ../../
(.venv) root@6e4b0572c1cd:/tmp# python3 -c "import example_pkg"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'example_pkg'
(.venv) root@6e4b0572c1cd:/tmp# python3 -m pip list     
Package       Version
------------- -------
example-pkg-a 1
pip           23.3.1
setuptools    68.2.2
wheel         0.41.3
(.venv) root@6e4b0572c1cd:/tmp# cd pkgutil/pkg_a/
(.venv) root@6e4b0572c1cd:/tmp/pkgutil/pkg_a# ls
build  example_pkg_a.egg-info  setup.py  src
(.venv) root@6e4b0572c1cd:/tmp/pkgutil/pkg_a# mv src/example_pkg/ .
(.venv) root@6e4b0572c1cd:/tmp/pkgutil/pkg_a# rmdir src/
(.venv) root@6e4b0572c1cd:/tmp/pkgutil/pkg_a# python3 -m pip install .
Processing /tmp/pkgutil/pkg_a
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: example-pkg-a
  Building wheel for example-pkg-a (setup.py) ... done
  Created wheel for example-pkg-a: filename=example_pkg_a-1-py3-none-any.whl size=1799 sha256=53d94d6d1bf307669a8f9512a8a44b06733fbbec1aec51308e0cc4a335168fce
  Stored in directory: /tmp/pip-ephem-wheel-cache-ocylkge2/wheels/65/b4/5f/13f92372b8f8b831dae39c654d8148beb33930870ccba2f54c
Successfully built example-pkg-a
Installing collected packages: example-pkg-a
  Attempting uninstall: example-pkg-a
    Found existing installation: example-pkg-a 1
    Uninstalling example-pkg-a-1:
      Successfully uninstalled example-pkg-a-1
Successfully installed example-pkg-a-1
(.venv) root@6e4b0572c1cd:/tmp/pkgutil/pkg_a# cd /tmp/
(.venv) root@6e4b0572c1cd:/tmp# python3 -c "import example_pkg" --verbose
(.venv) root@6e4b0572c1cd:/tmp# python3 -c "import example_pkg.a" --verbose
(.venv) root@6e4b0572c1cd:/tmp# python3 -c "import example_pkg.a; print(a.name)" --verbose
a


```

**Comment by abravalheri** [comment] 2023-11-17 17:59
Hi @chrysle, could you please check for an error when designing the reproducer? The step 2, might have been left incomplete.

Please see an updated example below:

```bash
# docker run --rm -it python:3.10.12-bookworm /bin/bash

git clone https://github.com/pypa/sample-namespace-packages /tmp/sample-namespace-packages
cd /tmp/sample-namespace-packages/pkgutil/pkg_a
mkdir src
mv example_pkg src
sed -i '/find_packages()/d' setup.py
# ^--- enable auto-discovery; alternatively: 's/find_packages()/find_packages(where="src"), package_dir={"": "src"}/'

python3 -m venv .venv/ && source .venv/bin/activate
python3 -m pip install -U setuptools wheel
python3 -m pip install .

cd /tmp/ && python3 -c "import example_pkg; print(example_pkg)"
# <module 'example_pkg' from '/tmp/sample-namespace-packages/pkgutil/pkg_a/.venv/lib/python3.10/site-packages/example_pkg/__init__.py'>
```

**Comment by chrysle** [comment] 2023-11-18 13:52
Thank you, I somehow missed that step! Now it works. I originally wanted to reproduce that you can't install different namespace packages with the same namespace side-by-side if you use an editable and a normal install. Do you know what the cause is for that?

```console
(.venv) root@3bc5e70a0cc3:/tmp/sample-namespace-packages-2/pkg_resources/pkg_a# python3 -m pip install .   
Processing /tmp/sample-namespace-packages-2/pkg_resources/pkg_a
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: example-pkg-a
  Building wheel for example-pkg-a (setup.py) ... done
  Created wheel for example-pkg-a: filename=example_pkg_a-1-py3-none-any.whl size=2261 sha256=da37dfe1448f5c3c1773fa3b5ae44c73f94c405316cd12030332dfb29282afc0
  Stored in directory: /tmp/pip-ephem-wheel-cache-07gmbi7j/wheels/f5/74/a5/f6c53efe3c442566f561d52542e99755d2d740c3d14a67faa9
Successfully built example-pkg-a
Installing collected packages: example-pkg-a
Successfully installed example-pkg-a-1
(.venv) root@3bc5e70a0cc3:/tmp/sample-namespace-packages-2/pkg_resources/pkg_a# cd ../../pkgutil/pkg_b/
(.venv) root@3bc5e70a0cc3:/tmp/sample-namespace-packages-2/pkgutil/pkg_b# python3 -m pip install -e .
Obtaining file:///tmp/sample-namespace-packages-2/pkgutil/pkg_b
  Preparing metadata (setup.py) ... done
Installing collected packages: example-pkg-b
  Attempting uninstall: example-pkg-b
    Found existing installation: example-pkg-b 1
    Uninstalling example-pkg-b-1:
      Successfully uninstalled example-pkg-b-1
  Running setup.py develop for example-pkg-b
Successfully installed example-pkg-b-1
(.venv) root@3bc5e70a0cc3:/tmp/sample-namespace-packages-2/pkgutil/pkg_b# cd ../../
(.venv) root@3bc5e70a0cc3:/tmp/sample-namespace-packages-2# python3 -c "import example_pkg.a; print(example_pkg.a)"
<module 'example_pkg.a' from '/tmp/sample-namespace-packages-2/.venv/lib/python3.10/site-packages/example_pkg/a/__init__.py'>
(.venv) root@3bc5e70a0cc3:/tmp/sample-namespace-packages-2# python3 -c "import example_pkg.b; print(example_pkg.b)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'example_pkg.b'
```

**Comment by abravalheri** [comment] 2023-11-18 16:57
Editable installs are difficult. The discussion on the latest PEP about them ended with a conclusion not very different from "all editable installation methods are flawed and namespace packages are particularly nasty".

Depending on the layout of the project (src vs flat vs heavily customised) and how pip install the project (build backend APIs as specified in PEP 517 x calling `python setup.py`) there are some well know limitations.

For the combination "build backed APIs + src-layout", things should work fine.

For the combination "build backend APIs + flat/heavily-customised layout", there is a limitation because `setuptools` needs to use `MetaPathFinder`s and other kinds of import hooks to isolate code that is not really meant to be installed. However these hooks don't really play well with namespaces (if you scan through the `importlib` files in the CPython implementation you can have a glimpse of how complex the import machinery is and all the edge cases it has to deal with).
Since `pkgutil` and `pkg_resources` are considered deprecated, I haven't bothered the CPython team for looking a solution for those. However I have an issue open to bring clarity about the topic: #92054

If pip is calling `python setup.py`[^1], then we are in the grey area again, somethings may work, others don't. But this method is deprecated and not supported, so users are urged to add a `pyproject.toml` (even an empty file already forces pip to opt into build backend APIs).

In the docs we have a list of well-known (and "so far non-fixable") limitations of editable installs and suggestions for workarounds: https://setuptools.pypa.io/en/latest/userguide/development_mode.html#limitations (by no means this documentation is perfect, so any contribution is welcome).


[^1]: If your project does not have `pyproject.toml` it is non-obvious when `pip` is going to use this method or not, depending on `pip`'s internal heuristics and state of the currently active virtual environment.

**Comment by chrysle** [comment] 2023-11-19 13:51
Many thanks for this detailed explanation!

> For the combination "build backed APIs + src-layout", things should work fine.

I've tested this for the _sample namespace packages_ project and things seem to work out fine. I'll introduce it soon.
 
> However I have an issue open to bring clarity about the topic: #92054

Look like the developers are in a rush to get rid of `pkgutil`... Well, I think I understand them. 

> If pip is calling `python setup.py`[1](#user-content-fn-1-ba5958152704ffca947a1bfb2c0d30d2), then we are in the grey area again, somethings may work, others don't.

I'm not sure why, but concerning `pkg_resources`, combining the `namespace_packages` parameter with the `src-layout` configuration settings doesn't seem to work properly, although it installs without complaints:

```python
setup(
    ....
    packages=find_packages(where='src'),
    package_dir={'': 'src'},
    namespace_packages=['example_pkg'],
    ....
)
```
> But this method is deprecated and not supported, so users are urged to add a `pyproject.toml` (even an empty file already forces pip to opt into build backend APIs).

I'll look into measures to support this suggestion shortly (see pypa/sample-namespace-packages#21 for progress).

> In the docs we have a list of well-known (and "so far non-fixable") limitations of editable installs and suggestions for workarounds: https://setuptools.pypa.io/en/latest/userguide/development_mode.html#limitations (by no means this documentation is perfect, so any contribution is welcome).

Thanks for mentioning the page, real helpful!

**Comment by abravalheri** [comment] 2023-11-20 15:27
Hi @chrysle, thanks for the feedback, I will close this issue for now since the original problem discussed in the first post seems to have been solved.

Please feel free to open another issue/discussion about further topics (not however that if the limitation is already identified and documented, we might not be able to do much about it).

**Closed by abravalheri** 2023-11-20 15:27 UTC
Labels: bug, Needs Triage

**Comment by chrysle** [comment] 2023-11-20 15:31
Thank you for your help!
