### ISSUE TITLE
Support an option parameters which can install binary files also in last version

### ISSUE THREAD

**Issue by ZhangHarte** [pypa/setuptools#584] opened 2016-05-12 11:26 UTC
Dear Jason R,

We are failed to  install our libs to teams after upgrade the  setuptools to 20.2.2.  Some lib update is been stopped. And not find other good way to do the post handling.

We have to include some third party binary files during setup :(  as we cannot develop the python function to cover all requirement.

We are very eager for you to support an option parameters which can support install binary files also during setup.

Thanks!!

Best regards,
Harte.

**Comment by jaraco** [comment] 2016-05-19 00:10
Hi @ZhangHarte. Thanks for filing the ticket. This is a duplicate of #583.

**Closed** 2018-08-31 20:12 UTC
Labels: duplicate
