### ISSUE TITLE
setuptools finds flask-mail instead of flask

### ISSUE THREAD

**Issue by Zethson** [pypa/setuptools#1641] opened 2019-01-18 17:15 UTC
### Expected Behavior

Running it on a new VPS. setup.py used is:     
https://github.com/Zethson/dark-proteome-visualization/blob/development/setup.py    
with requirements.txt used:    
https://github.com/Zethson/dark-proteome-visualization/blob/development/requirements.txt

 ```python
python setup.py clean --all install
```

Finds flask and installs flask.

### Actual Behavior

Searching for flask
Downloading https://files.pythonhosted.org/packages/05/2f/6a545452040c2556559779db87148d2a85e78a26f90326647b51dc5e81e9/Flask-Mail-0.9.1.tar.gz#sha256=22e5eb9a940bf407bcf30410ecc3708f3c56cc44b29c34e1726fe85006935f41
Best match: Flask Mail-0.9.1
Processing Flask-Mail-0.9.1.tar.gz

I tried pretty much all combinations of capital/lowercase for flask and flask-mail. No success. Interestingly enough, if I run the install script again (same virtual environment), it finds flask.

```pytb
error: The 'flask' distribution was not found and is required by flask-Mail
```

### Environment

* Python version: Python 3.6.7
* Flask version: latest
* Werkzeug version: latest

**Comment by benoit-pierre** [comment] 2019-01-18 17:34
Duplicate of #498, workaround: put `Flask-Mail` before `Flask` in `requirements.txt`:
```diff
 requirements.txt | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git i/requirements.txt w/requirements.txt
index 1cd48c1..dd56906 100644
--- i/requirements.txt
+++ w/requirements.txt
@@ -1,6 +1,6 @@
 pytest
+Flask-Mail
 Flask
 gevent
 click
-Flask-Mail
 python-rapidjson
```

**Closed by benoit-pierre** 2019-01-18 17:34 UTC
