### ISSUE TITLE
ModuleNotFoundError: No module named 'setuptools' 

### ISSUE THREAD

**Issue by Ramizf25** [pypa/setuptools#2555] opened 2021-02-04 10:16 UTC

**Comment by webknjaz** [comment] 2021-02-04 10:41
@Ramizf25 could you please fill in the description and adjust the title? Dumping some random line from the log does not give any context and we'll have to close this unless there's some useful info added.

**Comment by Ramizf25** [comment] 2021-02-04 11:09
ERROR: (gcloud.ai-platform.jobs.submit.training) Packaging of user Python code failed with message: Traceback (most recent call last):   File "/home/ramiz_f/tensorflow-recommendation-wals/wals_ml_engine/setup.py", line 15, in <module>     from setuptools import find_packages ModuleNotFoundError: No module named 'setuptools' Try manually building your Python code by running:   $ python setup.py sdist and providing the output via the `--packages` flag (for example, `--packages dist/package.tar.gz,dist/package2.whl)` Thu Feb  4 10:10:30 UTC 2021

**Comment by webknjaz** [comment] 2021-02-04 12:58
@Ramizf25 please describe what you're trying to do. From the traceback, it's conclusive that you don't have setuptools installed in the environment where your `setup.py` script imports it. You must install it there in order for this to work. It doesn't differ from any other module in the sense that you must have the package available in order to use it. From your logline, it looks like you are dealing with tensorflow. You may want to ask them what to do if the code is not yours.
This doesn't demonstrate that anything's wrong on the setuptools side. If you want to report a bug, please post steps to reproduce that solely rely on setuptools without any other external tooling. The way I see it now, you have some external platform that "forgot" to pre-install the build requirements (that is `setuptools` in your case, maybe something else too) and you should fix what that platform does, maybe add `pip install setuptools` somewhere, I don't know because your comment doesn't include any context of what's happening, what you did, what you expect or what you're asking about.

**Comment by Ramizf25** [comment] 2021-02-05 10:47
Tried deactivating tensorflow and conda, installed setup tools using pip. but still shows
![Screenshot from 2021-02-04 18-08-37](https://user-images.githubusercontent.com/69594881/107024104-99218700-67cd-11eb-8e96-46f8c51e903f.png)

**Comment by webknjaz** [comment] 2021-02-05 14:10
You need to reproduce this without your `./mltrain.sh` script. We don't know what it does, it doesn't have anything to do with setuptools.

**Comment by webknjaz** [comment] 2021-02-06 17:11
Closing per above.

**Closed by webknjaz** 2021-02-06 17:11 UTC
Labels: Needs Repro, invalid
