### ISSUE TITLE
setuptools install fails for 34.* on Python 2.6

### ISSUE THREAD

**Issue by DenverJ** [pypa/setuptools#938] opened 2017-01-23 23:36 UTC
Doing a ```pip install --upgrade setuptools``` fails in a virtualenv on Python 2.6. I haven't tested any other configurations.
```
$ python -V
Python 2.6.6
$ virtualenv --no-site-packages test-setuptools
New python executable in test-setuptools/bin/python
Installing Setuptools..............................................................................................................................................................................................................................done.
Installing Pip.....................................................................................................................................................................................................................................................................................................................................done.
$ source test-setuptools/bin/activate
(test-setuptools)$ pip install --upgrade setuptools
Downloading/unpacking setuptools from https://pypi.python.org/packages/b1/d1/3df86b914d72b18d37266f964a11576f135eadbb7d2e3c5165377e4263bc/setuptools-34.0.1.zip#md5=9e907950a94d38c0295df0da2507c280
  Downloading setuptools-34.0.1.zip (617kB): 617kB downloaded
  Running setup.py egg_info for package setuptools
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "setuptools/__init__.py", line 10, in <module>
        from six.moves import filter, map
    ImportError: No module named six.moves
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 3, in <module>

  File "setuptools/__init__.py", line 10, in <module>

    from six.moves import filter, map

ImportError: No module named six.moves

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/user/test-setuptools/build/setuptools
Storing complete log in /home/user/.pip/pip.log
```

**Comment by jaraco** [comment] 2017-01-23 23:37
I see it's building setuptools from source, which is no longer supported. Do you have a late version of pip that can install wheels? If not, you'll need to pre-install the setuptools dependencies manually.

**Comment by jaraco** [comment] 2017-01-23 23:40
```
$ python -m virtualenv --python python2.6 env26
Running virtualenv with interpreter /usr/bin/python2.6
New python executable in /Users/jaraco/Dropbox/code/yg/queso/env26/bin/python2.6
Also creating executable in /Users/jaraco/Dropbox/code/yg/queso/env26/bin/python
Installing setuptools, pip, wheel...done.
$ env26/bin/python -m pip.__main__ -V
pip 9.0.1 from /Users/jaraco/Dropbox/code/yg/queso/env26/lib/python2.6/site-packages (python 2.6)
$ env26/bin/python -m pip.__main__ install 'setuptools<34'     
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Collecting setuptools<34
  Using cached setuptools-33.1.1-py2.py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: setuptools 34.0.1
    Uninstalling setuptools-34.0.1:
      Successfully uninstalled setuptools-34.0.1
Successfully installed setuptools-33.1.1
$ env26/bin/python -m pip.__main__ install 'setuptools>=34'
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Collecting setuptools>=34
  Using cached setuptools-34.0.1-py2.py3-none-any.whl
Requirement already satisfied: appdirs>=1.4.0 in ./env26/lib/python2.6/site-packages (from setuptools>=34)
Requirement already satisfied: packaging>=16.8 in ./env26/lib/python2.6/site-packages (from setuptools>=34)
Requirement already satisfied: six>=1.10.0 in ./env26/lib/python2.6/site-packages (from setuptools>=34)
Requirement already satisfied: pyparsing in ./env26/lib/python2.6/site-packages (from packaging>=16.8->setuptools>=34)
Installing collected packages: setuptools
  Found existing installation: setuptools 33.1.1
    Uninstalling setuptools-33.1.1:
      Successfully uninstalled setuptools-33.1.1
Successfully installed setuptools-34.0.1
```

**Comment by jaraco** [comment] 2017-01-23 23:46
I suspect this issue is a duplicate of #937, only with a slighly different manifestation.

**Comment by DenverJ** [comment] 2017-01-23 23:49
Ah, yes it is. I looked for open issues but didn't think to look at closed. Thanks!

**Closed** 2017-01-24 01:20 UTC

**Comment by lorinkoz** [comment] 2017-01-26 19:46
Same problem trying to create virtualenvs in Cygwin. I had to install all setuptools dependencies in order to have it systemwide, but now I don't know how to overcome this when creating virtualenvs.
