### ISSUE TITLE
Having problems running develop command with v50.0 - must subclass Command

### ISSUE THREAD

**Issue by karriebear** [pypa/setuptools#2366] opened 2020-09-01 00:46 UTC
Similar to #2355 but for the `develop` command. Looks like the `develop` command is subclassing `namespaces.DevelopInstaller` --> `Installer`

This looks like it clashes with the check that each command implements the Command interface in [dist.py](https://github.com/pypa/setuptools/blob/17cb9d6bf249cefe653d3bdb712582409035a7db/setuptools/_distutils/dist.py#L544)
```
Traceback (most recent call last):
  File "setup.py", line 57, in <module>
    setuptools.setup(
  File "/Users/karrie/.local/share/virtualenvs/lib-NEukqkcO/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/Users/karrie/.local/share/virtualenvs/lib-NEukqkcO/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 134, in setup
    ok = dist.parse_command_line()
  File "/Users/karrie/.local/share/virtualenvs/lib-NEukqkcO/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 484, in parse_command_line
    args = self._parse_command_opts(parser, args)
  File "/Users/karrie/.local/share/virtualenvs/lib-NEukqkcO/lib/python3.8/site-packages/setuptools/dist.py", line 903, in _parse_command_opts
    nargs = _Distribution._parse_command_opts(self, parser, args)
  File "/Users/karrie/.local/share/virtualenvs/lib-NEukqkcO/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 547, in _parse_command_opts
    raise DistutilsClassError(
distutils.errors.DistutilsClassError: command class <class 'setuptools.command.develop.develop'> must subclass Command```

**Comment by jaraco** [comment] 2020-09-01 00:55
I suspect this is a dupe of #2355.

**Closed** 2020-09-01 01:20 UTC
Labels: duplicate
