### ISSUE TITLE
MANIFEST file ignored

### ISSUE THREAD

**Issue by erdnaxeli** [pypa/setuptools#1897] opened 2019-10-30 17:11 UTC
Hi,

I noticed that sometimes the MANIFEST file can be ignored.

Python version: 3.6.5
Setuptools version: 41.6.0

### Setup

In a new folder, create a file `setup.py` with the following:
```Python
from setuptools import setup, find_packages

setup(
    name='MyPackageName',
    version='1.0.0',
    url='https://github.com/mypackage.git',
    author='Author Name',
    author_email='author@gmail.com',
    description='Description of my package',
    packages=find_packages(),    
    install_requires=['numpy >= 1.11.1', 'matplotlib >= 1.5.1'],
)
```

You alse need an *empty* MANIFEST file, and another file we will call juste `myfile`.

Run `python setup.py sdist`. You will see that `myfile` *is not part* of the archive.

### Include `myfile`

Now change the MANIFEST file to:
```
include myfile
```

Then run `python setup.py sdist` again. Now `myfile` *is part* of the archive.

### Remove `myfile`

Oops, actually we didn't want to include `myfile`. Let's empty the MANIFEST file again.

Then run `python setup.py sdist`. We can see that `myfile` *is still part* of the archive.

## What was expected

In the last step, I would expect `myfile` to not be part of the archive.

Note that if we remove the `MyPackageName.egg-info` folder between the build, it behaves correctly. Still, this does not seem to be an expected behaviour.

Thanks.

**Comment by jaraco** [comment] 2019-11-01 17:54
When you say MANIFEST file, I think you mean the manifest template (MANIFEST.in). The manifest is actually the list of files to be included in the sources, and that's `*.egg-info/sources.txt`.

To be clear, it's not that the manifest template isn't being honored - it is, but it's just that once you've generated the manifest from the manifest template, those sources will be honored too.

This issue is a duplicate of #436.

**Closed by jaraco** 2019-11-01 17:54 UTC
