### ISSUE TITLE
Easy_install is distributing a suspected revoked release of pip-10.0.0b2

### ISSUE THREAD

**Issue by james-powis** [pypa/setuptools#1315] opened 2018-04-03 17:15 UTC
See https://github.com/pypa/pip/issues/5156

```
root@4f4af6ea00cd:/# pip -V
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
root@4f4af6ea00cd:/# pip install -U pip
Collecting pip
  Downloading pip-9.0.3-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 565kB/s
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed pip-9.0.3
root@4f4af6ea00cd:/# pip install --upgrade pip
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages
root@4f4af6ea00cd:/# pip install --upgrade pip -i https://pypi.python.org/simple/
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages
root@4f4af6ea00cd:/# easy_install -U pip
Searching for pip
Reading https://pypi.python.org/simple/pip/
Downloading https://pypi.python.org/packages/32/67/572f642e6e42c580d3154964cfbab7d9322c23b0f417c6c01fdd206a2777/pip-10.0.0b2.tar.gz#md5=cbfc1208d00bb72aba19431a7bb4afd5
Best match: pip 10.0.0b2
Processing pip-10.0.0b2.tar.gz
Writing /tmp/easy_install-o4Wodr/pip-10.0.0b2/setup.cfg
Running pip-10.0.0b2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-o4Wodr/pip-10.0.0b2/egg-dist-tmp-YO2jf8
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.mailmap'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching '.landscape.yml'
warning: no previously-included files found matching 'src/pip/_vendor/Makefile'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files found matching '*-requirements.txt'
warning: no previously-included files found matching 'appveyor.yml'
warning: no previously-included files found matching 'src/pip/_vendor/six'
warning: no previously-included files matching '*.pyi' found under directory 'src/pip/_vendor'
no previously-included directories found matching '.github'
no previously-included directories found matching '.travis'
no previously-included directories found matching 'docs/build'
no previously-included directories found matching 'news'
no previously-included directories found matching 'contrib'
no previously-included directories found matching 'tasks'
no previously-included directories found matching 'tests'
creating /usr/local/lib/python2.7/dist-packages/pip-10.0.0b2-py2.7.egg
Extracting pip-10.0.0b2-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding pip 10.0.0b2 to easy-install.pth file
Installing pip script to /usr/local/bin
Installing pip2.7 script to /usr/local/bin
Installing pip2 script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/pip-10.0.0b2-py2.7.egg
```

**Comment by benoit-pierre** [comment] 2018-04-03 17:19
Duplicate of #855.

**Closed by benoit-pierre** 2018-04-03 17:19 UTC
