### ISSUE TITLE
Problem on entry_points when package and module have the same name

### ISSUE THREAD

**Issue by eamanu** [pypa/setuptools#1432] opened 2018-07-20 15:29 UTC
Hello Everybody, 

I have the next simply test_eamanu.py file:

```
def main():
    print("Hello World!")

if __name__ == '__main__':
    main()
```
And the next simply setup.py:

```
from setuptools import setup

setup(
    name='test_eamanu',
    packages=['test_eamanu],
    entry_points={
        'console_scripts':[
            'test_eamanu=test_eamanu.test_eamanu:main'
        ]
    }
)
```

Whole is in this tree structure:
```
.
├── test_eamanu
│   ├── __init__.py
│   └── test_eamanu.py
|__ setup.py

```

When, I run `python setup.py install` the script finish successfully, but the "command" _test_ doesn't work. 

# Workaround
To avoid this problem I have to rename the package to _src_. So, the setup.py is the next:

```
from setuptools import setup

setup(
    name='test_eamanu',
    packages=['test_eamanu],
    entry_points={
        'console_scripts':[
            'test_eamanu=src.test_eamanu:main'
        ]
    }
)
```

**Comment by pganssle** [comment] 2018-10-19 20:40
@eamanu I can't reproduce this issue.

I created a repo for it, and it works just fine:

```bash
$ git clone git@github.com:pganssle-bug-mwes/setuptools_1432.git
Cloning into 'setuptools_1432'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 6 (delta 0), reused 6 (delta 0), pack-reused 0
Receiving objects: 100% (6/6), done.
$ cd setuptools_1432/
$ python -m venv venv
$ source venv/bin/activate
(venv) $ pip install .
Processing /tmp/setuptools_1432
Installing collected packages: test-eamanu
  Running setup.py install for test-eamanu ... done
Successfully installed test-eamanu-0.0.0
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(venv) $ test_eamanu
Hello World!
```

I'm going to close this for now, but if you think I've made a mistake attempting to reproduce this, let me know and I can re-open it.

That said, I'm a big fan of the [src layout](https://hynek.me/articles/testing-packaging/), so if this is some bug that was caused by something happening in your local directory that was fixed by using a `src` layout, let me know, because that's more fuel for the fire. 🔥🔥🔥

**Closed by pganssle** 2018-10-19 20:40 UTC
Labels: Needs Repro
