### ISSUE TITLE
[BUG] walk_recvtrl causes add_defaults to fail with vague, cryptic errors

### ISSUE THREAD

**Issue by happysmash27** [pypa/setuptools#2845] opened 2021-11-02 18:08 UTC
### setuptools version

57.5.0

### Python version

3.9.0b4

### OS

Gentoo Linux

### Additional environment information

This happens when I try to install QRL, both from pip, and manually: https://github.com/theQRL/QRL/. This happens on Gentoo but not the newest LTS Ubuntu on my VPS. I use Dual Xeon X5560s processors. 

### Description

When running `python setup.py build` in the QRL repository, or running `pip3 install --user QRL`, it fails with the vague, cryptic errors: 

```
abort: no repository found in '/home/happysmash27/Gits/QRLs/3/QRL' (.hg not found)
FileNotFoundError: [Errno 2] No such file or directory: ''
```
Despite the fact that this is not a mercurial repository, but a Git one. 

### Expected behavior

Setuptools doesn't try to do mercurial things on a Git repository and QRL installs successfully. 

### How to Reproduce

For pip: `pip3 install --user qrl`

From Github: 

1. `git clone https://github.com/theQRL/QRL/`
2. `cd QRL`
3. `python setup.py build`

To get to where the function fails in the debugger, run `python -m pdb setup.py build`, then pase the following code, removing all lines that begin with `//`: 

```
break 33
continue
n
//setup command
s
until 153
//runs the build command
//bunch of wrapper functions here
s
until 148
s
until 966
s
until 985
s
until 135
s
until 313
s
//We run command build_py
p command
until 985
s
until 1552
s
//self.build_packages on line 55 might be related
//But the error happens on line 56, build_package_data
//Runs self.build_package_data
until 56
s
//Ooh! Interesting. Trying to run p self.data_files actually triggers the error!
until 118
s
//At this point, pdb puts me into a __getattr__ function with comment "lazily compute data files"
until 69
s
//Now we are in __get_data_files(self)
//It fails on self.analyze_manifest()
until 82
s
//Then it fails on self.run_command('egg_info')
until 139
//Wrapper functions again
s
until 313
s
until 985
s
//Now we are in this other run command, in egg_info.py
//It does all the "writing *****" messages in the for loop. No error here.
//And then it fails in self.find_sources(), line 299
until 299
s
//It does manifest_filename = os.path.join(self.egg_info, "SOURCES.txt")
p os.path.join(self.egg_info, "SOURCES.txt")
//The value of os.path.join(self.egg_info, "SOURCES.txt") is 'src/qrl.egg-info/SOURCES.txt'
//This file is empty.
//This must mean it is filling the file?
//It assigns that to mm.manifest. mm = manifest_maker(self.distribution)
//As expected, the failure point here is mm.run(), line 306
until 306
s
//This function is also in egg_info.py, line 137
//It fails in self.add_defaults()
until 541
s
//And then, it fails in 581: rcfiles = list(walk_revctrl()), which as we know from previous experiments, is the failure point
//The line after it says if rcfiles. This file doesn't even need to exist!
//So the problem is, that it is throwing the error instead of ignoring it? 
```

### Output

`pip3 install --user qrl` does this, version after version: 

```
 % pip3 install --user qrl
Collecting qrl
  Using cached qrl-2.1.2.tar.gz (547 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0pslezxs/qrl_e69118d39eb4493d9f74ddd3f209d9f1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0pslezxs/qrl_e69118d39eb4493d9f74ddd3f209d9f1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-dwcq5ahc
         cwd: /tmp/pip-install-0pslezxs/qrl_e69118d39eb4493d9f74ddd3f209d9f1/
    Complete output (18 lines):
    /usr/lib/python3.9/site-packages/setuptools/dist.py:697: UserWarning: Usage of dash-separated 'author-email' will not be supported in future versions. Please use the underscore name 'author_email' instead
      warnings.warn(
    /usr/lib/python3.9/site-packages/setuptools/dist.py:697: UserWarning: Usage of dash-separated 'long-description' will not be supported in future versions. Please use the underscore name 'long_description' instead
      warnings.warn(
    /usr/lib/python3.9/site-packages/setuptools/dist.py:697: UserWarning: Usage of dash-separated 'author-email' will not be supported in future versions. Please use the underscore name 'author_email' instead
      warnings.warn(
    /usr/lib/python3.9/site-packages/setuptools/dist.py:697: UserWarning: Usage of dash-separated 'long-description' will not be supported in future versions. Please use the underscore name 'long_description' instead
      warnings.warn(
    running egg_info
    creating /tmp/pip-pip-egg-info-dwcq5ahc/qrl.egg-info
    writing /tmp/pip-pip-egg-info-dwcq5ahc/qrl.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-dwcq5ahc/qrl.egg-info/dependency_links.txt
    writing entry points to /tmp/pip-pip-egg-info-dwcq5ahc/qrl.egg-info/entry_points.txt
    writing requirements to /tmp/pip-pip-egg-info-dwcq5ahc/qrl.egg-info/requires.txt
    writing top-level names to /tmp/pip-pip-egg-info-dwcq5ahc/qrl.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-dwcq5ahc/qrl.egg-info/SOURCES.txt'
    error: [Errno 2] No such file or directory: ''
    abort: no repository found in '/tmp/pip-install-0pslezxs/qrl_e69118d39eb4493d9f74ddd3f209d9f1' (.hg not found)
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/13/6e/a796d90230910c0c93cdc9c303b0440a4efee62263e52a91744811f34dc0/qrl-2.1.2.tar.gz#sha256=f8e2aae448191ef5c6bdd407521fa0b2fb53bdc36260e387679ec7c26c7fa262 (from https://pypi.org/simple/qrl/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached qrl-2.1.1.tar.gz (547 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0pslezxs/qrl_17a325f9a00c49239698073910bce3ff/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0pslezxs/qrl_17a325f9a00c49239698073910bce3ff/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_wjaxo48
         cwd: /tmp/pip-install-0pslezxs/qrl_17a325f9a00c49239698073910bce3ff/
    Complete output (18 lines):
    /usr/lib/python3.9/site-packages/setuptools/dist.py:697: UserWarning: Usage of dash-separated 'author-email' will not be supported in future versions. Please use the underscore name 'author_email' instead
      warnings.warn(
    /usr/lib/python3.9/site-packages/setuptools/dist.py:697: UserWarning: Usage of dash-separated 'long-description' will not be supported in future versions. Please use the underscore name 'long_description' instead
      warnings.warn(
    /usr/lib/python3.9/site-packages/setuptools/dist.py:697: UserWarning: Usage of dash-separated 'author-email' will not be supported in future versions. Please use the underscore name 'author_email' instead
      warnings.warn(
    /usr/lib/python3.9/site-packages/setuptools/dist.py:697: UserWarning: Usage of dash-separated 'long-description' will not be supported in future versions. Please use the underscore name 'long_description' instead
      warnings.warn(
    running egg_info
    creating /tmp/pip-pip-egg-info-_wjaxo48/qrl.egg-info
    writing /tmp/pip-pip-egg-info-_wjaxo48/qrl.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-_wjaxo48/qrl.egg-info/dependency_links.txt
    writing entry points to /tmp/pip-pip-egg-info-_wjaxo48/qrl.egg-info/entry_points.txt
    writing requirements to /tmp/pip-pip-egg-info-_wjaxo48/qrl.egg-info/requires.txt
    writing top-level names to /tmp/pip-pip-egg-info-_wjaxo48/qrl.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-_wjaxo48/qrl.egg-info/SOURCES.txt'
    error: [Errno 2] No such file or directory: ''
    abort: no repository found in '/tmp/pip-install-0pslezxs/qrl_17a325f9a00c49239698073910bce3ff' (.hg not found)
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/75/64/d05429b4ad38b5e2513a2279866cce48578c9fc6ffc920f58ffed5e0b06e/qrl-2.1.1.tar.gz#sha256=8b87fbf0f6aad3c70cd486b4464e5929db4506ec63f6203443f884cacbe05ca8 (from https://pypi.org/simple/qrl/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached qrl-2.1.0.tar.gz (547 kB)
```
etc etc etc. 

`python setup.py build`:

```
 % python setup.py build
/usr/lib/python3.9/site-packages/setuptools/dist.py:697: UserWarning: Usage of dash-separated 'author-email' will not be supported in future versions. Please use the underscore name 'author_email' instead
  warnings.warn(
/usr/lib/python3.9/site-packages/setuptools/dist.py:697: UserWarning: Usage of dash-separated 'long-description' will not be supported in future versions. Please use the underscore name 'long_description' instead
  warnings.warn(
/usr/lib/python3.9/site-packages/setuptools/dist.py:697: UserWarning: Usage of dash-separated 'author-email' will not be supported in future versions. Please use the underscore name 'author_email' instead
  warnings.warn(
/usr/lib/python3.9/site-packages/setuptools/dist.py:697: UserWarning: Usage of dash-separated 'long-description' will not be supported in future versions. Please use the underscore name 'long_description' instead
  warnings.warn(
running build
running build_py
creating build
creating build/lib
creating build/lib/qrl
copying src/qrl/__init__.py -> build/lib/qrl
copying src/qrl/_version.py -> build/lib/qrl
copying src/qrl/cli.py -> build/lib/qrl
copying src/qrl/grpcProxy.py -> build/lib/qrl
copying src/qrl/main.py -> build/lib/qrl
copying src/qrl/measure.py -> build/lib/qrl
creating build/lib/qrl/core
copying src/qrl/core/AddressState.py -> build/lib/qrl/core
copying src/qrl/core/Block.py -> build/lib/qrl/core
copying src/qrl/core/BlockHeader.py -> build/lib/qrl/core
copying src/qrl/core/BlockMetadata.py -> build/lib/qrl/core
copying src/qrl/core/ChainManager.py -> build/lib/qrl/core
copying src/qrl/core/DifficultyTracker.py -> build/lib/qrl/core
copying src/qrl/core/ESyncState.py -> build/lib/qrl/core
copying src/qrl/core/GenesisBlock.py -> build/lib/qrl/core
copying src/qrl/core/Indexer.py -> build/lib/qrl/core
copying src/qrl/core/LastTransactions.py -> build/lib/qrl/core
copying src/qrl/core/Message.py -> build/lib/qrl/core
copying src/qrl/core/MessageRequest.py -> build/lib/qrl/core
copying src/qrl/core/Miner.py -> build/lib/qrl/core
copying src/qrl/core/MultiSigAddressState.py -> build/lib/qrl/core
copying src/qrl/core/OptimizedAddressState.py -> build/lib/qrl/core
copying src/qrl/core/OutgoingMessage.py -> build/lib/qrl/core
copying src/qrl/core/PaginatedBitfield.py -> build/lib/qrl/core
copying src/qrl/core/PaginatedData.py -> build/lib/qrl/core
copying src/qrl/core/PoWValidator.py -> build/lib/qrl/core
copying src/qrl/core/ProposalRecord.py -> build/lib/qrl/core
copying src/qrl/core/Singleton.py -> build/lib/qrl/core
copying src/qrl/core/State.py -> build/lib/qrl/core
copying src/qrl/core/StateContainer.py -> build/lib/qrl/core
copying src/qrl/core/StateMigration.py -> build/lib/qrl/core
copying src/qrl/core/TokenList.py -> build/lib/qrl/core
copying src/qrl/core/TokenMetadata.py -> build/lib/qrl/core
copying src/qrl/core/TransactionInfo.py -> build/lib/qrl/core
copying src/qrl/core/TransactionMetadata.py -> build/lib/qrl/core
copying src/qrl/core/TransactionPool.py -> build/lib/qrl/core
copying src/qrl/core/VoteStats.py -> build/lib/qrl/core
copying src/qrl/core/Wallet.py -> build/lib/qrl/core
copying src/qrl/core/__init__.py -> build/lib/qrl/core
copying src/qrl/core/config.py -> build/lib/qrl/core
copying src/qrl/core/formulas.py -> build/lib/qrl/core
copying src/qrl/core/messagereceipt.py -> build/lib/qrl/core
copying src/qrl/core/node.py -> build/lib/qrl/core
copying src/qrl/core/qrlnode.py -> build/lib/qrl/core
creating build/lib/qrl/crypto
copying src/qrl/crypto/AESHelper.py -> build/lib/qrl/crypto
copying src/qrl/crypto/QRandomX.py -> build/lib/qrl/crypto
copying src/qrl/crypto/Qryptonight.py -> build/lib/qrl/crypto
copying src/qrl/crypto/Qryptonight7.py -> build/lib/qrl/crypto
copying src/qrl/crypto/__init__.py -> build/lib/qrl/crypto
copying src/qrl/crypto/doctest_data.py -> build/lib/qrl/crypto
copying src/qrl/crypto/misc.py -> build/lib/qrl/crypto
copying src/qrl/crypto/xmss.py -> build/lib/qrl/crypto
creating build/lib/qrl/generated
copying src/qrl/generated/__init__.py -> build/lib/qrl/generated
copying src/qrl/generated/qrl_pb2.py -> build/lib/qrl/generated
copying src/qrl/generated/qrl_pb2_grpc.py -> build/lib/qrl/generated
copying src/qrl/generated/qrlbase_pb2.py -> build/lib/qrl/generated
copying src/qrl/generated/qrlbase_pb2_grpc.py -> build/lib/qrl/generated
copying src/qrl/generated/qrldebug_pb2.py -> build/lib/qrl/generated
copying src/qrl/generated/qrldebug_pb2_grpc.py -> build/lib/qrl/generated
copying src/qrl/generated/qrllegacy_pb2.py -> build/lib/qrl/generated
copying src/qrl/generated/qrllegacy_pb2_grpc.py -> build/lib/qrl/generated
copying src/qrl/generated/qrlmining_pb2.py -> build/lib/qrl/generated
copying src/qrl/generated/qrlmining_pb2_grpc.py -> build/lib/qrl/generated
copying src/qrl/generated/qrlstateinfo_pb2.py -> build/lib/qrl/generated
copying src/qrl/generated/qrlstateinfo_pb2_grpc.py -> build/lib/qrl/generated
copying src/qrl/generated/qrlwallet_pb2.py -> build/lib/qrl/generated
copying src/qrl/generated/qrlwallet_pb2_grpc.py -> build/lib/qrl/generated
creating build/lib/qrl/services
copying src/qrl/services/AdminAPIService.py -> build/lib/qrl/services
copying src/qrl/services/BaseService.py -> build/lib/qrl/services
copying src/qrl/services/DebugAPIService.py -> build/lib/qrl/services
copying src/qrl/services/MiningAPIService.py -> build/lib/qrl/services
copying src/qrl/services/PublicAPIService.py -> build/lib/qrl/services
copying src/qrl/services/WalletAPIService.py -> build/lib/qrl/services
copying src/qrl/services/__init__.py -> build/lib/qrl/services
copying src/qrl/services/grpcHelper.py -> build/lib/qrl/services
copying src/qrl/services/services.py -> build/lib/qrl/services
creating build/lib/qrl/tools
copying src/qrl/tools/__init__.py -> build/lib/qrl/tools
copying src/qrl/tools/generate_genesis.py -> build/lib/qrl/tools
copying src/qrl/tools/token_migration_json_converter.py -> build/lib/qrl/tools
creating build/lib/qrl/core/miners
copying src/qrl/core/miners/__init__.py -> build/lib/qrl/core/miners
creating build/lib/qrl/core/misc
copying src/qrl/core/misc/DependencyChecker.py -> build/lib/qrl/core/misc
copying src/qrl/core/misc/__init__.py -> build/lib/qrl/core/misc
copying src/qrl/core/misc/db.py -> build/lib/qrl/core/misc
copying src/qrl/core/misc/expiring_set.py -> build/lib/qrl/core/misc
copying src/qrl/core/misc/helper.py -> build/lib/qrl/core/misc
copying src/qrl/core/misc/logger.py -> build/lib/qrl/core/misc
copying src/qrl/core/misc/logger_twisted.py -> build/lib/qrl/core/misc
copying src/qrl/core/misc/ntp.py -> build/lib/qrl/core/misc
copying src/qrl/core/misc/set_logger.py -> build/lib/qrl/core/misc
creating build/lib/qrl/core/notification
copying src/qrl/core/notification/Observable.py -> build/lib/qrl/core/notification
copying src/qrl/core/notification/ObservableEvent.py -> build/lib/qrl/core/notification
copying src/qrl/core/notification/__init__.py -> build/lib/qrl/core/notification
creating build/lib/qrl/core/p2p
copying src/qrl/core/p2p/IPMetadata.py -> build/lib/qrl/core/p2p
copying src/qrl/core/p2p/__init__.py -> build/lib/qrl/core/p2p
copying src/qrl/core/p2p/p2pChainManager.py -> build/lib/qrl/core/p2p
copying src/qrl/core/p2p/p2pObservable.py -> build/lib/qrl/core/p2p
copying src/qrl/core/p2p/p2pObserver.py -> build/lib/qrl/core/p2p
copying src/qrl/core/p2p/p2pPeerManager.py -> build/lib/qrl/core/p2p
copying src/qrl/core/p2p/p2pTxManagement.py -> build/lib/qrl/core/p2p
copying src/qrl/core/p2p/p2pfactory.py -> build/lib/qrl/core/p2p
copying src/qrl/core/p2p/p2pprotocol.py -> build/lib/qrl/core/p2p
creating build/lib/qrl/core/processors
copying src/qrl/core/processors/TxnProcessor.py -> build/lib/qrl/core/processors
copying src/qrl/core/processors/__init__.py -> build/lib/qrl/core/processors
creating build/lib/qrl/core/txs
copying src/qrl/core/txs/CoinBase.py -> build/lib/qrl/core/txs
copying src/qrl/core/txs/LatticeTransaction.py -> build/lib/qrl/core/txs
copying src/qrl/core/txs/MessageTransaction.py -> build/lib/qrl/core/txs
copying src/qrl/core/txs/SlaveTransaction.py -> build/lib/qrl/core/txs
copying src/qrl/core/txs/TokenTransaction.py -> build/lib/qrl/core/txs
copying src/qrl/core/txs/Transaction.py -> build/lib/qrl/core/txs
copying src/qrl/core/txs/TransferTokenTransaction.py -> build/lib/qrl/core/txs
copying src/qrl/core/txs/TransferTransaction.py -> build/lib/qrl/core/txs
copying src/qrl/core/txs/__init__.py -> build/lib/qrl/core/txs
creating build/lib/qrl/core/miners/qrandomx
copying src/qrl/core/miners/qrandomx/QRXMiner.py -> build/lib/qrl/core/miners/qrandomx
copying src/qrl/core/miners/qrandomx/QRXPoWValidator.py -> build/lib/qrl/core/miners/qrandomx
copying src/qrl/core/miners/qrandomx/__init__.py -> build/lib/qrl/core/miners/qrandomx
creating build/lib/qrl/core/miners/qryptonight7
copying src/qrl/core/miners/qryptonight7/CNv1Miner.py -> build/lib/qrl/core/miners/qryptonight7
copying src/qrl/core/miners/qryptonight7/CNv1PoWValidator.py -> build/lib/qrl/core/miners/qryptonight7
copying src/qrl/core/miners/qryptonight7/__init__.py -> build/lib/qrl/core/miners/qryptonight7
creating build/lib/qrl/core/txs/multisig
copying src/qrl/core/txs/multisig/MultiSigCreate.py -> build/lib/qrl/core/txs/multisig
copying src/qrl/core/txs/multisig/MultiSigSpend.py -> build/lib/qrl/core/txs/multisig
copying src/qrl/core/txs/multisig/MultiSigVote.py -> build/lib/qrl/core/txs/multisig
copying src/qrl/core/txs/multisig/__init__.py -> build/lib/qrl/core/txs/multisig
creating build/lib/qrl/tools/modeling
copying src/qrl/tools/modeling/__init__.py -> build/lib/qrl/tools/modeling
copying src/qrl/tools/modeling/extract_timing.py -> build/lib/qrl/tools/modeling
running egg_info
creating src/qrl.egg-info
writing src/qrl.egg-info/PKG-INFO
writing dependency_links to src/qrl.egg-info/dependency_links.txt
writing entry points to src/qrl.egg-info/entry_points.txt
writing requirements to src/qrl.egg-info/requires.txt
writing top-level names to src/qrl.egg-info/top_level.txt
writing manifest file 'src/qrl.egg-info/SOURCES.txt'
abort: no repository found in '/home/happysmash27/Gits/QRLs/4/QRL' (.hg not found)
error: [Errno 2] No such file or directory: ''
```
My newest pdb session: 

```
 % python -m pdb setup.py build
> /home/happysmash27/Gits/QRLs/3/QRL/setup.py(3)<module>()
-> """
(Pdb) break 33
Breakpoint 1 at /home/happysmash27/Gits/QRLs/3/QRL/setup.py:33
(Pdb) continue
> /home/happysmash27/Gits/QRLs/3/QRL/setup.py(33)setup_package()
-> use_pyscaffold=True)
(Pdb) n
> /home/happysmash27/Gits/QRLs/3/QRL/setup.py(29)setup_package()
-> setup(setup_requires=['pyscaffold>=3.0a0,<3.1a0'] + sphinx,
(Pdb) s
--Call--
> /usr/lib/python3.9/site-packages/setuptools/__init__.py(150)setup()
-> def setup(**attrs):
(Pdb) until 153
/usr/lib/python3.9/site-packages/setuptools/dist.py:697: UserWarning: Usage of dash-separated 'author-email' will not be supported in future versions. Please use the underscore name 'author_email' instead
  warnings.warn(
/usr/lib/python3.9/site-packages/setuptools/dist.py:697: UserWarning: Usage of dash-separated 'long-description' will not be supported in future versions. Please use the underscore name 'long_description' instead
  warnings.warn(
> /usr/lib/python3.9/site-packages/setuptools/__init__.py(153)setup()
-> return distutils.core.setup(**attrs)
(Pdb) s
--Call--
> /usr/lib/python3.9/distutils/core.py(57)setup()
-> def setup (**attrs):
(Pdb) until 148
/usr/lib/python3.9/site-packages/setuptools/dist.py:697: UserWarning: Usage of dash-separated 'author-email' will not be supported in future versions. Please use the underscore name 'author_email' instead
  warnings.warn(
/usr/lib/python3.9/site-packages/setuptools/dist.py:697: UserWarning: Usage of dash-separated 'long-description' will not be supported in future versions. Please use the underscore name 'long_description' instead
  warnings.warn(
> /usr/lib/python3.9/distutils/core.py(148)setup()
-> dist.run_commands()
(Pdb) s
--Call--
> /usr/lib/python3.9/distutils/dist.py(960)run_commands()
-> def run_commands(self):
(Pdb) until 966
> /usr/lib/python3.9/distutils/dist.py(966)run_commands()
-> self.run_command(cmd)
(Pdb) s
--Call--
> /usr/lib/python3.9/distutils/dist.py(970)run_command()
-> def run_command(self, command):
(Pdb) until 985
running build
> /usr/lib/python3.9/distutils/dist.py(985)run_command()
-> cmd_obj.run()
(Pdb) s
--Call--
> /usr/lib/python3.9/distutils/command/build.py(128)run()
-> def run(self):
(Pdb) until 135
> /usr/lib/python3.9/distutils/command/build.py(135)run()
-> self.run_command(cmd_name)
(Pdb) s
--Call--
> /usr/lib/python3.9/distutils/cmd.py(308)run_command()
-> def run_command(self, command):
(Pdb) until 313
> /usr/lib/python3.9/distutils/cmd.py(313)run_command()
-> self.distribution.run_command(command)
(Pdb) s
--Call--
> /usr/lib/python3.9/distutils/dist.py(970)run_command()
-> def run_command(self, command):
(Pdb) p command
'build_py'
(Pdb) until 985
running build_py
> /usr/lib/python3.9/distutils/dist.py(985)run_command()
-> cmd_obj.run()
(Pdb) s
--Call--
> /home/happysmash27/Gits/QRLs/3/QRL/versioneer.py(1548)run()
-> def run(self):
(Pdb) until 1552
> /home/happysmash27/Gits/QRLs/3/QRL/versioneer.py(1552)run()
-> _build_py.run(self)
(Pdb) s
--Call--
> /usr/lib/python3.9/site-packages/setuptools/command/build_py.py(46)run()
-> def run(self):
(Pdb) until 56
> /usr/lib/python3.9/site-packages/setuptools/command/build_py.py(56)run()
-> self.build_package_data()
(Pdb) s
--Call--
> /usr/lib/python3.9/site-packages/setuptools/command/build_py.py(116)build_package_data()
-> def build_package_data(self):
(Pdb) until 118
> /usr/lib/python3.9/site-packages/setuptools/command/build_py.py(118)build_package_data()
-> for package, src_dir, build_dir, filenames in self.data_files:
(Pdb) s
--Call--
> /usr/lib/python3.9/site-packages/setuptools/command/build_py.py(66)__getattr__()
-> def __getattr__(self, attr):
(Pdb) until 69
> /usr/lib/python3.9/site-packages/setuptools/command/build_py.py(69)__getattr__()
-> self.data_files = self._get_data_files()
(Pdb) s
--Call--
> /usr/lib/python3.9/site-packages/setuptools/command/build_py.py(80)_get_data_files()
-> def _get_data_files(self):
(Pdb) until 82
> /usr/lib/python3.9/site-packages/setuptools/command/build_py.py(82)_get_data_files()
-> self.analyze_manifest()
(Pdb) s
--Call--
> /usr/lib/python3.9/site-packages/setuptools/command/build_py.py(130)analyze_manifest()
-> def analyze_manifest(self):
(Pdb) until 139
> /usr/lib/python3.9/site-packages/setuptools/command/build_py.py(139)analyze_manifest()
-> self.run_command('egg_info')
(Pdb) s
--Call--
> /usr/lib/python3.9/distutils/cmd.py(308)run_command()
-> def run_command(self, command):
(Pdb) until 313
> /usr/lib/python3.9/distutils/cmd.py(313)run_command()
-> self.distribution.run_command(command)
(Pdb) s
--Call--
> /usr/lib/python3.9/distutils/dist.py(970)run_command()
-> def run_command(self, command):
(Pdb) until 985
running egg_info
> /usr/lib/python3.9/distutils/dist.py(985)run_command()
-> cmd_obj.run()
(Pdb) s
--Call--
> /usr/lib/python3.9/site-packages/setuptools/command/egg_info.py(285)run()
-> def run(self):
(Pdb) until 299
writing src/qrl.egg-info/PKG-INFO
writing dependency_links to src/qrl.egg-info/dependency_links.txt
writing entry points to src/qrl.egg-info/entry_points.txt
writing requirements to src/qrl.egg-info/requires.txt
writing top-level names to src/qrl.egg-info/top_level.txt
> /usr/lib/python3.9/site-packages/setuptools/command/egg_info.py(299)run()
-> self.find_sources()
(Pdb) s
--Call--
> /usr/lib/python3.9/site-packages/setuptools/command/egg_info.py(301)find_sources()
-> def find_sources(self):
(Pdb) until 306
> /usr/lib/python3.9/site-packages/setuptools/command/egg_info.py(306)find_sources()
-> mm.run()
(Pdb) s
--Call--
> /usr/lib/python3.9/site-packages/setuptools/command/egg_info.py(537)run()
-> def run(self):
(Pdb) until 541
> /usr/lib/python3.9/site-packages/setuptools/command/egg_info.py(541)run()
-> self.add_defaults()
(Pdb) s
--Call--
> /usr/lib/python3.9/site-packages/setuptools/command/egg_info.py(577)add_defaults()
-> def add_defaults(self):
(Pdb) ll
577  ->	    def add_defaults(self):
578  	        sdist.add_defaults(self)
579  	        self.filelist.append(self.template)
580  	        self.filelist.append(self.manifest)
581  	        rcfiles = list(walk_revctrl())
582  	        if rcfiles:
583  	            self.filelist.extend(rcfiles)
584  	        elif os.path.exists(self.manifest):
585  	            self.read_manifest()
586  	
587  	        if os.path.exists("setup.py"):
588  	            # setup.py should be included by default, even if it's not
589  	            # the script called to create the sdist
590  	            self.filelist.append("setup.py")
591  	
592  	        ei_cmd = self.get_finalized_command('egg_info')
593  	        self.filelist.graft(ei_cmd.egg_info)
(Pdb) n
> /usr/lib/python3.9/site-packages/setuptools/command/egg_info.py(578)add_defaults()
-> sdist.add_defaults(self)
(Pdb) n
> /usr/lib/python3.9/site-packages/setuptools/command/egg_info.py(579)add_defaults()
-> self.filelist.append(self.template)
(Pdb) n
> /usr/lib/python3.9/site-packages/setuptools/command/egg_info.py(580)add_defaults()
-> self.filelist.append(self.manifest)
(Pdb) n
> /usr/lib/python3.9/site-packages/setuptools/command/egg_info.py(581)add_defaults()
-> rcfiles = list(walk_revctrl())
(Pdb) n
abort: no repository found in '/home/happysmash27/Gits/QRLs/3/QRL' (.hg not found)
FileNotFoundError: [Errno 2] No such file or directory: ''
> /usr/lib/python3.9/site-packages/setuptools/command/egg_info.py(581)add_defaults()
-> rcfiles = list(walk_revctrl())
```
A bunch more logs and things are here: https://github.com/theQRL/QRL/issues/1689. It took me a while to even figure out that this issue was with setuptools, as there were many layers of abstraction and the error output is extremely vague. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by henry12322** [comment] 2021-11-03 00:53
Contact coinbase support team https://my.forms.app/form/617e6cc70d06846f4ca75ee4

**Comment by happysmash27** [comment] 2021-11-03 02:15
Random 2 hour old account with an easy-to-automatically-generate name sending an "official" form that, for some reason, isn't hosted on the company's own website, all while having advice not applicable to the situation, but is vague enough to seem plausible... Are people making bots to send scams in Github issues now??? That is so unexpected they didn't even put in a button to report scams here!

**Comment by henry12322** [comment] 2021-11-03 02:17
2 hours Account. You started like I did too bro

**Comment by abravalheri** [comment] 2022-01-05 11:51
Hi @happysmash27, sorry to hear about your bad experience with GitHub :(

Following up our previous [discussion](https://github.com/pyscaffold/pyscaffold/discussions/484), I think this is a problem with the `setuptools-scm` plugin, not setuptools itself.

setuptools does not even have a `walk_recvtrl` function, so there is not much we can do in this repository... For this reason I think the best course of action would be closing the issue here and open another one in https://github.com/pypa/setuptools_scm, unless we find some new evidence that the problem is generated by setuptools itself.

Sorry for not being able to help you much with this problem.

**Closed by abravalheri** 2022-01-05 11:51 UTC
Labels: bug, Needs Triage
