### ISSUE TITLE
Moving distutils into setuptools

### ISSUE THREAD

**Issue by xoviat** [pypa/setuptools#1164] opened 2017-10-02 16:15 UTC
As discussed on distutils-sig, we want to vendor a copy of distutils and have setuptools use that copy rather than the local Python distutils. Long-term, CPython will remove distutils and `python -m ensuresetuptools`.

@jaraco Would you like me to submit a PR for this or would you like to do it yourself?

**Comment by jaraco** [comment] 2017-10-25 16:28
This is a duplicate of #417.

**Closed by jaraco** 2017-10-25 16:28 UTC
