### ISSUE TITLE
Removal of SetuptoolsVersion breaks public API, forces installation of `packaging` or perverse import from `extern`

### ISSUE THREAD

**Issue by benjolitz** [pypa/setuptools#1310] opened 2018-03-28 02:44 UTC
I am quite confused at the removal of ``SetuptoolsVersion``, ``SetuptoolsLegacyVersion`` and it's unifying mixin ``_SetuptoolsVersionMixin `` - it's been long exposed and provides support for an `isinstance` check.

By removing it, I discovered that a boring deployment became quite exciting in forcing me to figure out how to satisfy the following cryptic comment:

```
They should not have been used, but if they were, replace with ``Version`` and ``LegacyVersion`` from ``packaging.version``.
```

A better description that states either:

- Use ``from pkg_resources.extern.packaging.version import Version, LegacyVersion``
- Use the `packaging` project (acquirable via ``pip install packaging``)

It also would be highly helpful for migrating off of that removed public API for the mixin with:

- Use ``_BaseVersion`` from ``packaging.version`` import to replace ``_SetuptoolsVersionMixin``

As API changes go, this is both surprising and under-documented.

**Comment by pganssle** [comment] 2018-03-28 21:14
@benjolitz I mean, it's a major version, you should expect some backwards compatibility to break, right?

In any case, I don't see `SetuptoolsVersion` anywhere in the documentation for version 38.x, and it is not in `pkg_resources.__all__`, so I don't think it was intended to be part of the public interface at this point. I think the preferred interface is to call `pkg_resources.parse_version` and use whatever object that gives you, rather than trying to manually construct any of these objects, which is why the changelog says "They should not have been used".

As for the other things, one of them is private (has a leading `_`) and the other one has the word "Legacy" in it, so those are pretty obviously deprecated. I think going forward just call `pkg_resources.parse_version()` or if for some reason you absolutely must directly construct these objects for some reason, use `pip install packaging`.

**Comment by benjolitz** [comment] 2018-03-28 22:41
This is the commit in question:

https://github.com/pypa/setuptools/commit/eeeb9b27fa48fccf2b5d52919eff1c75c4ad1718

As a matter of API design, that class has been present for over several dozen setuptools versions.

Secondly, if I give you a data object, pray tell _how_ are you supposed to figure out it is a Version object? Something as silly as `version_cls = type(parse_version('0.0.0'))`?

Thirdly, the changes in question are within one of the **most depended-upon projects in the entire Python ecosystem**.  Frankly the "lolfuckyou didn't you see the major version uptick?" sucks as a response.

As to use cases, I used the `SetuptoolsVersion` as part of a type restriction to constrain hostile user input. I would expect that someone else would want to use `isinstance` to catch both of them using either a tuple or the mixin (`_SetuptoolsVersionMixin`) as a common inheritance point.

But that's really not the main issue. 

The issue is over the quality advice towards migrating off of `SetuptoolsVersion` and `SetuptoolsLegacyVersion` - it is vague, unhelpful and arbitrary.

And "This should not have been used" in the changelog for a long present data class? Really? Thats your idea of deprecation?

**Comment by pganssle** [comment] 2018-03-28 23:14
Closing as this is not a bug and there is no possible remedy. Future users of the undocumented `SetuptoolsVersion` will see this thread and know what to do.

**Comment by pganssle** [comment] 2018-03-28 23:14
FWIW, `isinstance` does nothing to stop any hostile user input, and I suspect that you have bigger problems if you are accepting user input into your build system.

**Closed by pganssle** 2018-03-28 23:14 UTC

**Comment by pganssle** [comment] 2018-03-29 00:07
@benjolitz For what it's worth I understand where you are coming from here, and I was mostly trying to reverse engineer the logic for the deprecation myself, having joined this project literally days ago.

In the future, I would agree that it is probably better to use some sort of deprecation cycle that raises warnings if you try and access previously-existing classes like that, since according to [Hyrum's Law](http://www.hyrumslaw.com/) it doesn't matter what the *developer* thinks is part of the public interface, everything accessible *will be used*.

As for your specific concern, I think that `type(parse_version('0.0.0'))` is actually a pretty stable way to get the type of the object returned by `parse_version`, and that idiom is [used in the CPython standard library](https://github.com/python/cpython/blob/master/Lib/types.py#L12).

That said, I don't know the function well enough to say that the return type being independent of the input is part of the contract of the function (I can imagine that the contract really just intends to give you objects that have a certain semantic relationship with one another, e.g. they are comparable, without specifying the type). I don't really understand how checking whether the result of `parse_version` would be an instance of `SetuptoolsVersion` would help protect against user hostile input, but I think it's probably a good idea to try to find a way to do it that does not rely on this assumption.
