### ISSUE TITLE
Some namespace packages rely on `setuptools` importing `pkg_resources` during build, which is not necessarily true in 67.3.1

### ISSUE THREAD

**Issue by mnasiadka** [pypa/setuptools#3824] opened 2023-02-15 10:25 UTC
### setuptools version

setuptools===67.3.1

### Python version

Python 3.9

### OS

CentOS Stream 9 / Rocky Linux 9

### Description

Happening on a regular build of OpenStack Kolla container images installing OpenStack Horizon (and dependencies) using pip:

LOG: https://storage.gra.cloud.ovh.net/v1/AUTH_dcaab5e32b234d56b626f72581e3644c/zuul_opendev_logs_046/873875/1/check/kolla-build-rocky9/0467a01/kolla/build/000_FAILED_horizon.log

### Expected behavior

Installation successful (like in 67.2.0)

### How to Reproduce

Use setuptools 67.3.0 and run exact commands as in linked Log file.

### Output

```console
INFO:kolla.common.utils.horizon:Collecting XStatic-Moment-Timezone>=0.5.22.0
INFO:kolla.common.utils.horizon:  Downloading http://mirror-int.iad.rax.opendev.org:8080/pypifiles/packages/77/8d/a3a89a0b2b18086b1c7c9c754decefb813715d870df3adcdcf1ca687ff70/XStatic-Moment-Timezone-0.5.22.0.tar.gz (99 kB)
INFO:kolla.common.utils.horizon:     â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â” 99.7/99.7 kB 132.6 MB/s eta 0:00:00
INFO:kolla.common.utils.horizon:  Preparing metadata (setup.py): started
INFO:kolla.common.utils.horizon:  Preparing metadata (setup.py): finished with status 'error'
INFO:kolla.common.utils.horizon:[91m  error: subprocess-exited-with-error
INFO:kolla.common.utils.horizon:  
INFO:kolla.common.utils.horizon:  Ã— python setup.py egg_info did not run successfully.
INFO:kolla.common.utils.horizon:  â”‚ exit code: 1
INFO:kolla.common.utils.horizon:  â•°â”€> [6 lines of output]
INFO:kolla.common.utils.horizon:      Traceback (most recent call last):
INFO:kolla.common.utils.horizon:        File "<string>", line 2, in <module>
INFO:kolla.common.utils.horizon:        File "<pip-setuptools-caller>", line 34, in <module>
INFO:kolla.common.utils.horizon:        File "/tmp/pip-install-5b3r3by_/xstatic-moment-timezone_8aa6c912d03148cc8a3bf51bd5942cbf/setup.py", line 2, in <module>
INFO:kolla.common.utils.horizon:          from xstatic.pkg import moment_timezone as xs
INFO:kolla.common.utils.horizon:      ImportError: cannot import name 'moment_timezone' from 'xstatic.pkg' (unknown location)
INFO:kolla.common.utils.horizon:      [end of output]
INFO:kolla.common.utils.horizon:  
INFO:kolla.common.utils.horizon:  note: This error originates from a subprocess, and is likely not a problem with pip.
INFO:kolla.common.utils.horizon:[0m
INFO:kolla.common.utils.horizon:[91merror: metadata-generation-failed
INFO:kolla.common.utils.horizon:Ã— Encountered error while generating package metadata.
INFO:kolla.common.utils.horizon:â•°â”€> See above for output.
INFO:kolla.common.utils.horizon:note: This is an issue with the package mentioned above, not pip.
INFO:kolla.common.utils.horizon:hint: See above for details.
INFO:kolla.common.utils.horizon:[0m
```

**Comment by mnasiadka** [comment] 2023-02-15 10:49
Minimal reproducer:
# docker run --network host -it quay.io/rockylinux/rockylinux:9 bash
# dnf -y install git python3-pip
# python3 -m venv venv
# . ./venv/bin/activate
# pip3 install -U pip
# pip3 install -U setuptools
# git clone https://opendev.org/openstack/horizon
# pip3 install /horizon
Output:
Installing collected packages: XStatic-tv4, XStatic-term.js, XStatic-Spin, XStatic-smart-table, XStatic-roboto-fontface, XStatic-Rickshaw, XStatic-objectpath, XStatic-mdi, XStatic-JSEncrypt, XStatic-JQuery.TableSorter, XStatic-JQuery.quicksearch, XStatic-JQuery-Migrate, XStatic-jQuery, XStatic-Jasmine, XStatic-Hogan, XStatic-Font-Awesome, XStatic-D3, XStatic-bootswatch, XStatic-Bootstrap-SCSS, XStatic-Bootstrap-Datepicker, XStatic-Angular-Schema-Form, XStatic-Angular-lrdragndrop, XStatic-Angular-Gettext, XStatic-Angular-FileUpload, XStatic-Angular-Bootstrap, XStatic-Angular, XStatic, wcwidth, rjsmin, requestsexceptions, rcssmin, pytz, pyperclip, pyinotify, netifaces, netaddr, msgpack, charset-normalizer, appdirs, zipp, XStatic-jquery-ui, wrapt, WebOb, urllib3, sqlparse, six, simplejson, semantic-version, rfc3986, PyYAML, pyrsistent, pyparsing, pycparser, PrettyTable, pbr, packaging, jsonpointer, jmespath, iso8601, idna, futurist, fasteners, dnspython, django-debreach, decorator, certifi, Babel, autopage, attrs, asgiref, stevedore, requests, python-dateutil, pyScss, pymongo, oslo.i18n, os-service-types, jsonschema, jsonpatch, importlib-metadata, Django, debtcollector, cmd2, cffi, warlock, python-swiftclient, oslo.utils, oslo.context, oslo.config, keystoneauth1, enmerkar, dogpile.cache, django-pyscss, django-appconf, cryptography, cliff, python-cinderclient, pyOpenSSL, oslo.serialization, oslo.concurrency, openstacksdk, django-compressor, python-novaclient, python-keystoneclient, python-glanceclient, osprofiler, oslo.policy, oslo.log, osc-lib, os-client-config, python-neutronclient, oslo.upgradecheck, horizon
  DEPRECATION: XStatic-tv4 is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for XStatic-tv4 ... done
  DEPRECATION: XStatic-term.js is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for XStatic-term.js ... error
  error: subprocess-exited-with-error

  × Running setup.py install for XStatic-term.js did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-uaux9_j4/xstatic-term-js_5158c196deaa4e8fa1a36235e0e8cb2f/setup.py", line 1, in <module>
          from xstatic.pkg import termjs as xs
      ImportError: cannot import name 'termjs' from 'xstatic.pkg' (unknown location)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> XStatic-term.js

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by abravalheri** [comment] 2023-02-15 15:21
Hi @mnasiadka,

Could you please try installing the `wheel` package to the environment as well?

I can see that the following commands will result in a successful installation:

```bash
> docker run --network host -it quay.io/rockylinux/rockylinux:9 bash

dnf -y install git python3-pip
python3 -m venv venv
. ./venv/bin/activate
pip3 install -U pip
pip3 install -U setuptools
pip3 install -U wheel

git clone https://opendev.org/openstack/horizon
pip3 install /horizon
```

Alternatively you also can pass the `--use-pep517` flag to pip.

If you are satisfied with this approach, I think we can close this issue. Otherwise we would like to **really simplify** the example to a minimal reproducer (which I am afraid https://github.com/pypa/setuptools/issues/3824#issuecomment-1431137591 is not).

**Comment by abravalheri** [comment] 2023-02-15 15:26
A few remarks:

- [v67.3.0](https://setuptools.pypa.io/en/latest/history.html#v67-3-0) did some internal changes to decouple `setuptools` from `pkg_resources` and added a couple of warnings/clarifications.
   - These changes seem to be unrelated to how local imports work, however some installation workflows could be relying on the fact that once `pkg_resources` is imported it will cause a series of side-effects...
- In general `virtualenv` and `venv` already include `wheel`...
  - Maybe if you have a dependency chain: `target <- dependency` and `target` is build in isolation but does not uses `setuptools`, you could be in a situation where `dependency` is built in an environment that does not contain `wheel`...

**Comment by abravalheri** [comment] 2023-02-16 11:23
Here is a sequence of commands that (I think) reproduce the described error without using external packages:


```bash
rm -rf /tmp/stash && mkdir -p /tmp/stash && cd /tmp/stash

mkdir -p proj1/parent_ns/child_ns/pkg1
echo  >  proj1/parent_ns/__init__.py "__import__('pkg_resources').declare_namespace(__name__)"
echo  >  proj1/parent_ns/child_ns/__init__.py "__import__('pkg_resources').declare_namespace(__name__)"
touch    proj1/parent_ns/child_ns/pkg1/__init__.py
cat   >  proj1/setup.py <<EOF
from parent_ns.child_ns import pkg1
from setuptools import setup

setup(
    name='pkg1',
    packages=['parent_ns', 'parent_ns.child_ns', 'parent_ns.child_ns.pkg1'],
    namespace_packages=['parent_ns', 'parent_ns.child_ns'],
)
EOF

mkdir -p proj2/parent_ns/child_ns/pkg2
echo  >  proj2/parent_ns/__init__.py "__import__('pkg_resources').declare_namespace(__name__)"
echo  >  proj2/parent_ns/child_ns/__init__.py "__import__('pkg_resources').declare_namespace(__name__)"
touch    proj2/parent_ns/child_ns/pkg2/__init__.py
cat   >  proj2/setup.py <<EOF
from parent_ns.child_ns import pkg2
from setuptools import setup

setup(
    name='pkg2',
    packages=['parent_ns', 'parent_ns.child_ns', 'parent_ns.child_ns.pkg2'],
    namespace_packages=['parent_ns', 'parent_ns.child_ns'],
)
EOF

mkdir  proj3
cat >  proj3/setup.py <<EOF
from setuptools import setup

setup(
    name='pkg3',
    install_requires=[
        'pkg1 @ file:///tmp/stash/proj1',
        'pkg2 @ file:///tmp/stash/proj2',
    ]
)
EOF

python3 -m venv .venv-67.2
.venv-67.2/bin/python -m pip install -U pip 'setuptools==67.2.0'
.venv-67.2/bin/python -m pip install ./proj3
# ==========> This succeeds:
# ...
# Successfully installed pkg1-0.0.0 pkg2-0.0.0 pkg3-0.0.0

python3 -m venv .venv-67.3
.venv-67.3/bin/python -m pip install -U pip 'setuptools==67.3.2'
.venv-67.3/bin/python -m pip install ./proj3
# ==========> This fails:
# ...
# Installing collected packages: pkg2, pkg1, pkg3
# ...
# Running setup.py install for pkg2 ... done
# ...
# Running setup.py install for pkg1 ... error
# ...
# ImportError: cannot import name 'pkg1' from 'parent_ns.child_ns' (unknown location)
```

In this situation we have 2 packages that use the `namespace_packages` configuration in `setup.py`  and `pkg_resources.declare_namespace` in their `__init__.py` [^1]. Both share the same nested namespace. When installing a 3rd package that depends on both, the first dependency gets installed normally, but the second dependency fails to install, because its `setup.py` cannot import the module from CWD.

[^1]: `namespace_packages` and `pkg_resources.declare_namespace` have been discouraged for a while in by [PyPA](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/) and [Setuptools itself](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#legacy-namespace-packages). This way of declaring namespaces was officially deprecated 3 years ago (https://github.com/pypa/setuptools/pull/2149).

**Comment by abravalheri** [comment] 2023-02-16 11:48
Based on the example above we can also demonstrate that using `namespace_packages` and `pkg_resources.declare_namespace` has always been causing import failures, even before that v67.3:

```bash
# starting with the code base from the example above
cd /tmp/stash
rm -rf .venv-67.2 && python3 -m venv .venv-67.2
.venv-67.2/bin/python -m pip install -U pip 'setuptools==67.2.0'
.venv-67.2/bin/python -m pip install ./proj2   # <--- Let's install proj2
cd proj1  # <--- Now let's get inside proj1 and try to perform an import relying on CWD
../.venv-67.2/bin/python -c 'from parent_ns.child_ns import pkg1'
# ImportError: cannot import name 'pkg1' from 'parent_ns.child_ns' (unknown location)

# We can repeat the same process for a much older version of setuptools (e.g. 57)
cd /tmp/stash
rm -rf .venv-57 && python3 -m venv .venv-57
.venv-57/bin/python -m pip install -U pip 'setuptools==57.0.0'
.venv-57/bin/python -m pip install ./proj2
cd proj1
../.venv-57/bin/python -c 'from parent_ns.child_ns import pkg1'
# ImportError: cannot import name 'pkg1' from 'parent_ns.child_ns' (unknown location)
```

If we do however, import `pkg_resources` prior to trying importing anything from inside the namespaces, the import statement will be successful:

```bash
cd /tmp/stash/proj1
../.venv-57/bin/python -c 'import pkg_resources; from parent_ns.child_ns import pkg1'  # No errors
../.venv-67.2/bin/python -c 'import pkg_resources; from parent_ns.child_ns import pkg1'  # No errors
../.venv-67.3/bin/python -c 'import pkg_resources; from parent_ns.child_ns import pkg1'  # No errors

**Comment by abravalheri** [comment] 2023-02-16 12:14
Based on the investigation in https://github.com/pypa/setuptools/issues/3824#issuecomment-1432964898, my conclusion is that having scripts import packages that use the deprecated `namespace_packages` + `pkg_resources.declare_namespace` technique is error prone and that has not been changed or caused by v67.3.1.

My guess is that, in the context of a package installation, these errors where being masked in `setuptools<=67.2.0` by the fact that `setuptools` was importing `pkg_resources`. In v67.3.1, there was a huge effort to avoid importing `pkg_resources`.

This is inline with the declared intention to [separate the projects and obviate `pkg_resources`](https://github.com/pypa/setuptools/milestone/4). I don't think we can afford adding this import back.

My suggested workaround is to use `pip install --use-pep517` (which will be the default in a few months).

**Comment by abravalheri** [comment] 2023-02-16 12:35
I will leave this issue open for a few days, but I am inclined to close it soon (as a no-op), since we identified that the most likely origin for the problem is the package's `setup.py` script assumes `pkg_resources` is imported by `setuptools`.

**Comment by mnasiadka** [comment] 2023-02-16 12:41
Feel free to close, I'll raise issues in the respective repositories with a link to that explanation - hopefully they can work on it.

**Closed** 2023-02-16 13:45 UTC
Labels: bug, Needs Triage, Waiting User Feedback
