### ISSUE TITLE
[BUG] Editable Installation with src-layout Fails Due to Hidden '.venv'

### ISSUE THREAD

**Issue by fkhn** [pypa/setuptools#4595] opened 2024-08-26 02:23 UTC
### setuptools version

setuptools==65.5.0

### Python version

Python 3.11

### OS

macOS

### Additional environment information

a venv name '.venv'
pip 24.2

### Description

When using `pip install -e .` with a `src-layout`, an entry is typically added to `sys.path` via a file named `__editable__.pakagename.pth`. However, the loading of this `.pth` file fails if the virtual environment is hidden, which is the case for the default `.venv` name used by many tools.
To be precise, `cpython/Lib/site.py` uses `os.lstat` on the `.pth` file and skips it.
It is likely the same on other Unix-like systems.

### Expected behavior

Since `src-layout` and editable installs are frequently used, they should be supported regardless of the virtual environment's naming convention or visibility status.

### How to Reproduce

create a venv with a name starting by a dot, typically `.venv`
use a `src-layout`
`python3 -v -m packagename`

### Output

```
Skipping hidden .pth file: '/project_folder/.venv/lib/python3.11/site-packages/__editable__.packagename.pth'
```

**Comment by abravalheri** [comment] 2024-08-26 10:53
Please also note that users are advised to try the last version available of setuptools before reporting problems. Setuptools development model only releases monotonically increasing versions, so if any change is necessary to solve the problem it is only done on top of the `main` branch.

---

I am not sure why you are getting this message. The file that setuptools itself produces is not a hidden file itself, it does not start with a `.` and we [do not add any special attribute to it when creating the wheel](https://github.com/pypa/setuptools/blob/v73.0.1/setuptools/command/editable_wheel.py#L393-L396) used by `pip`, so there is nothing we can really change about it.

The problem description also mentions "likely the same on other Unix-like systems", but I cannot reproduce this in a different POSIX environment:

```bash
# docker run --rm -it python:3.11-bookworm /bin/bash
mkdir -p /tmp/proj/src
cd /tmp/proj

cat <<EOF > pyproject.toml
[build-system]
requires = ["setuptools==73.0.1"]
build-backend = "setuptools.build_meta"
EOF

cat <<EOF > src/pkg.py
print("hello world")
EOF

python -m venv .venv
.venv/bin/python -m pip install -U "pip==24.2"
.venv/bin/python -m pip install -e .
# ...
# Successfully built pkg
# Installing collected packages: pkg
# Successfully installed pkg-0.0.0

ls -la .venv/lib/python3.11/site-packages/__editable__.pkg-0.0.0.pth
# -rw-r--r-- 1 root root 14 Aug 26 10:35 .venv/lib/python3.11/site-packages/__editable__.pkg-0.0.0.pth

.venv/bin/python -m pkg
# hello world
```


In Linux I cannot see any `Skipping hidden .pth file` message.

Based on this code (from  https://github.com/python/cpython/commit/21ab20b3a794ab5f64963706088af21574068f4c), we can also check inside of the container for any attributes: https://github.com/python/cpython/blob/v3.11.9/Lib/site.py#L172-L180

```python
# .venv/bin/python
Python 3.11.9 (main, Apr  3 2024, 23:59:48) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os, stat
>>> st = os.lstat('.venv/lib/python3.11/site-packages/__editable__.pkg-0.0.0.pth')
>>> st
os.stat_result(st_mode=33188, st_ino=200282, st_dev=230, st_nlink=1, st_uid=0, st_gid=0, st_size=14, st_atime=1724668626, st_mtime=1724668530, st_ctime=1724668530)
>>> getattr(st, 'st_flags', 0) & stat.UF_HIDDEN
0
>>> getattr(st, 'st_file_attributes', 0) & stat.FILE_ATTRIBUTE_HIDDEN
0
```

That said, this is the furthest I can go with this investigation, because I don't have access to a macOS machine. If anyone would like to take the investigation further and find out the origin of the problem that would be very nice, but for now the problem sounds very weird.

There is nothing in the setuptools code adding any kind of flag or file attribute to make the file hidden.

**Comment by fkhn** [comment] 2024-08-26 14:24
Your comment leads me to a specific macOS stuff. My folder is under Documents and this one is synchronized with iCloud. The side effect of that is that the hidden flag is set by that machinery. So now we know it’s not as wide as Unix-like but narrowed to macOS with iCloud sync. A better situation as fewer people are concerned, but still annoying.

**Comment by fkhn** [comment] 2024-08-26 14:46
To reproduce the macOS iCloud behavior, I have setup a test folder with both dot and not dot folder and move that test folder under Documents that is synched: see the result on hidden flag.

```
find test_hidden -exec ls -ldO \{\} \;
drwxr-xr-x  5 franck  staff  - 160 26 aoû 16:30 test_hidden
drwxr-xr-x  3 franck  staff  - 96 26 aoû 16:16 test_hidden/.dot_folder
drwxr-xr-x  3 franck  staff  - 96 26 aoû 16:16 test_hidden/.dot_folder/inner_folder
-rw-r--r--  1 franck  staff  - 0 26 aoû 14:36 test_hidden/.dot_folder/inner_folder/a_file
-rw-r--r--  1 franck  staff  - 618 26 aoû 14:52 test_hidden/pyproject.toml
drwxr-xr-x  3 franck  staff  - 96 26 aoû 16:16 test_hidden/nodot_folder
drwxr-xr-x  3 franck  staff  - 96 26 aoû 16:16 test_hidden/nodot_folder/inner_folder
-rw-r--r--  1 franck  staff  - 0 26 aoû 14:37 test_hidden/nodot_folder/inner_folder/a_file

```
`mv test_hidden Documents`
```
find Documents/test_hidden -exec ls -ldO \{\} \; 
drwxr-xr-x  5 franck  staff  - 160 26 aoû 16:30 Documents/test_hidden
drwxr-xr-x  3 franck  staff  hidden 96 26 aoû 16:30 Documents/test_hidden/.dot_folder
drwxr-xr-x  3 franck  staff  hidden 96 26 aoû 16:30 Documents/test_hidden/.dot_folder/inner_folder
-rw-r--r--  1 franck  staff  hidden 0 26 aoû 14:36 Documents/test_hidden/.dot_folder/inner_folder/a_file
-rw-r--r--  1 franck  staff  - 618 26 aoû 14:52 Documents/test_hidden/pyproject.toml
drwxr-xr-x  3 franck  staff  - 96 26 aoû 16:30 Documents/test_hidden/nodot_folder
drwxr-xr-x  3 franck  staff  - 96 26 aoû 16:30 Documents/test_hidden/nodot_folder/inner_folder
-rw-r--r--  1 franck  staff  - 0 26 aoû 14:37 Documents/test_hidden/nodot_folder/inner_folder/a_file
```
With that in mind, it is a macOS or python subject more than a setuptools one. I guess that there is other contexts where the hidden flag might be set and trigger the same trouble. If setuptools might help either on the hidden python policy for pth file, or to warn users. That was quite difficult to isolate.

**Comment by abravalheri** [comment] 2024-08-26 16:16
> If setuptools might help either on the hidden python policy for pth file, or to warn users. That was quite difficult to isolate.

I am afraid setuptools cannot help with that, because the development of Python happens very separated from setuptools and vice versa... Python policy for `.pth` files is something that has to be discussed with the Python core devs either in https://discuss.python.org or via an issue/discussion in the https://github.com/python/cpython repository.

We are not in a very good position to warn the users either, because setuptools only builds a wheel file and does not know where it is going to be installed... That information is under the control of installers like `pip`. Moreover, installers usually hide all output from setuptools, even warnings. Users don't see any of the messages we have in editable installations. For example I don't think any user ever saw the following `warnings.warn` message for non-src-layout editable installations: https://github.com/pypa/setuptools/blob/v73.0.1/setuptools/command/editable_wheel.py#L535; or the following `logging.warning` message for src-layouts: https://github.com/pypa/setuptools/blob/v73.0.1/setuptools/command/editable_wheel.py#L399-L403.

**Comment by abravalheri** [comment] 2024-08-26 16:28
Thank you very much @fkhn for the investigation and finding out what is the root of the problem.
Since we identified that there is not much setuptools can do for this case (everything seems to be outside of the control of `setuptools`, probably the best next step would be asking for the advice of the Python core devs about this situation.

The checks for hidden files seem to be a new "feature" in Python (merged at the beginning of this year): https://github.com/python/cpython/pull/113660.

I am not sure if the core developers where already notified of this edge case where it is not the user (legitimate or malicious) that marks the `.pth` file as hidden, but iCloud itself (and not because of the name of the `.pth` file, but because of the name of a parent folder -- which is even worse). It may be worth discussing with them.

It is also important to point out 2 things:

- The behaviour that you observed does not seem to be restricted to editable installs or more specifically a setuptools editable installs. ***ANY*** `.pth` file on a `.venv` environment would be affected and skipped.
- `.pth` files are currently at the core of any implementation of editable installs. In the current state of Python's packaging ecosystem, it cannot be done consistently with them. So if there is some external factor making Python skip `.venv/**/*.pth` files, there is no way to implement editable installs.

I will go ahead and close this issue because I don't think we can do anything in setuptools code base to get around this problem.

**Closed by abravalheri** 2024-08-26 16:28 UTC
Labels: bug, Needs Triage

**Comment by fkhn** [comment] 2024-08-26 17:13
Thank you very much @abravalheri for your reactivity and constructive comments that help to discover the root cause. I have appreciated your pointers to cpython. I am fine with the closure of the current issue. For your information I have added a comment on [cpython/issues/113659](https://github.com/python/cpython/issues/113659) to make the link to the current discussion.
