### ISSUE TITLE
[Docs]  Please add changelog link to Github Releases

### ISSUE THREAD

**Issue by dolfinus** [pypa/setuptools#4130] opened 2023-11-21 12:40 UTC
### Summary

Release notes pushed to Github with almost no description:
https://github.com/pypa/setuptools/releases
![изображение](https://github.com/pypa/setuptools/assets/4661021/4547c033-8fec-4d2d-af46-f79070a8a010)

Please add at least a link to changelog of specific version, like https://setuptools.pypa.io/en/stable/history.html#v69-0-1. Or even add the same changelog items to release description, converting them from .rst syntax to .md, [here is](https://github.com/MobileTeleSystems/onetl/blob/2b4ced786b998e5b6a66d0363034cc8a4279f82e/.github/workflows/release.yml#L70) some example.

### Additional Information

-

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment] 2023-11-21 13:46
This is probably a duplicate of #2892 and #2807.

Any help implementing that is appreciated. I am happy to review PRs for that topic.
Maybe it is needed to coordinate with https://github.com/jaraco/jaraco.develop, which is the tool we use to create the release via Github API.

**Closed by abravalheri** 2023-11-21 13:46 UTC
Labels: Needs Triage, documentation

**Comment by dolfinus** [comment] 2023-12-16 19:47
So you don't use Github Actions to publish releases to PyPI and Github? All this is just manual?

**Comment by abravalheri** [comment] 2023-12-16 20:01
No, the process is automated. To understand more about the automation, I recommend having a look at:

- the linked issues (to which I consider this issue to be a duplicate),
- the workflow file
- the docs website (in the section about development process and releases)
- the `tox.ini` file.

**Comment by dolfinus** [comment] 2023-12-16 20:10
I've just tried to see logs of workflow which (as I expected) was used to publish the recent release, but got only failed jobs:
https://github.com/pypa/setuptools/actions/runs/7211233162

`release` job was skipped

**Comment by abravalheri** [comment] 2023-12-17 00:48
The last automated release to PyPI was 69.0.2.
