### ISSUE TITLE
Install amqplib for Python3.9 failed using setuptool 60.1.0

### ISSUE THREAD

**Issue by kewywwq** [pypa/setuptools#2979] opened 2021-12-28 09:10 UTC
### setuptools version

setuptools==60.1.0

### Python version

Python 3.9

### OS

Ubuntu 20.04

### Description

On Ubuntu20.04, install Python3.9 and setuptools==60.1.0 and amqplib==1.0.2
Checked py file in amqplib folder.
$ vi /usr/local/lib/python3.9/dist-packages/amqplib/client_0_8/__init__.py, it is not corrected for Python3 syntax.
from basic_message import *
from channel import *
from connection import *
from exceptions import *

__all__ =  [
            'Connection',
            'Channel',      # here mainly so it shows in in pydoc
            'Message',
            'AMQPException',
            'AMQPConnectionException',
            'AMQPChannelException',
           ]

If use setuptools==59.4.0, amqplib is installed correctly and checked file as below.
$ vi /usr/local/lib/python3.9/dist-packages/amqplib/client_0_8/__init__.py
from .basic_message import *
from .channel import *
from .connection import *
from .exceptions import *

__all__ =  [
            'Connection',
            'Channel',      # here mainly so it shows in in pydoc
            'Message',
            'AMQPException',
            'AMQPConnectionException',
            'AMQPChannelException',
           ]

### Expected behavior

amqplib should be installed correctly for Python3.9.

### How to Reproduce

OS: Ubuntu 20.04
1. apt-get install python3.9
2. apt-get install python3-pip
3. pip3 install setuptools==60.1.0
4. pip3 install amqplib==1.0.2
5. vi /usr/local/lib/python3.9/dist-packages/amqplib/client_0_8/__init__.py

### Output

from basic_message import *
from channel import *
from connection import *
from exceptions import *

__all__ =  [
            'Connection',
            'Channel',      # here mainly so it shows in in pydoc
            'Message',
            'AMQPException',
            'AMQPConnectionException',
            'AMQPChannelException',
           ]

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment] 2021-12-28 11:13
Hi @kewywwq, thank you very much for the issue report.

I suspect this problem is related to this change: https://setuptools.pypa.io/en/latest/history.html#v58-0-0.

**Comment by kewywwq** [comment] 2021-12-29 04:37
@abravalheri  Thank you so much for your quick reply. 
I tried to export SETUPTOOLS_USE_DISTUTILS=stdlib and install amqplib using setuptools==60.1.0, and it is correct.
BTW, I saw this change is since v58.0.0, but when I use v59.4.0 w/o export environment parameter SETUPTOOLS_USE_DISTUTILES, my amqplib installation is also correct. Why is it?

**Comment by abravalheri** [comment] 2021-12-29 08:17
I suppose this happens because until [v60](https://setuptools.pypa.io/en/latest/history.html#v60-0-0) the build process would rely on the outdated copy of distutils distributed with the Python stdlib, and this version of distutils would itself handle converting Python2 to 3 even without the help of setuptools.

Starting with v60, setuptools by default will try to use an updated version of distutils.

This vendored version of distutils contains several bug fixes and improvements but also deprecate things (like the command to convert Python2 to Python3 syntax at build time).

**Comment by abravalheri** [comment] 2021-12-29 08:27
I am not sure if much can be done inside setuptools to help with this situation now that we confirmed the root cause of the problem.

Have you tried to contact the package developers? I understand that changing the code to the Python3 syntax may be difficult, but a simple solution could be publishing a wheel (a wheel can be created in a venv with the pinned version of setuptools and will contain the "pre-converted" Python2 to 3)

**Comment by kewywwq** [comment] 2021-12-29 08:33
Thank you so much ! @abravalheri 
The package 'amqplib' is a little older and the latest version of it is 2011. So I think it is not very suitable for the latest syntax. 
Anyway I have tried to set the env parameter and install correctly for this package and I also want to use the latest version of setuptools.

**Comment by abravalheri** [comment] 2021-12-29 08:44
I am glad that we found a workaround for your workflow :)

Would you mind if we close this issue with that solution? (I am considering that the deprecation/breaking change was announced and still supported for a few releases to give people chance to move on, and  that Python 2 syntax have been retired for a while).

There are a few ways to solve this issue in the package side of things that do not involve migrating the code base to Python 3. I am more than happy to advise on that 😀

**Comment by kewywwq** [comment] 2021-12-29 08:50
Yes, I think this issue is fixed for me. Thank you.

**Closed** 2021-12-29 08:51 UTC
