### ISSUE TITLE
setuptools failing in github checks

### ISSUE THREAD

**Issue by Tiwari1812** [pypa/setuptools#3251] opened 2022-04-05 15:03 UTC
### setuptools version

setuptools==57.0.0 in ide but not sure which version github uses to run checks

### Python version

python3.8

### OS

ubuntu

### Additional environment information

When github checks are running build.yml 

### Description

When github is trying to load build.yml file its failing on the line pip install --upgrade pip setuptools wheel  and checks are not even starting
<img width="1389" alt="Screenshot 2022-04-05 at 8 14 43 PM" src="https://user-images.githubusercontent.com/87305579/161784033-e0cbee46-1316-4383-a7af-520174449da4.png">

i have even tried upgrading pip and changing the setuptools version but no progress

### Expected behavior

its coming from past 10days before that checks were loading succesfully 

### How to Reproduce

runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip3 install -r requirements/test.txt
    - name: Check Quality
      run: |
        ./pylama.sh

### Output

Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-401qhgiu/django-allauth_5c477dffa46b40b5983e966a17fbf0e0/setup.py", line 8, in <module>
          from setuptools import convert_path, find_packages, setup
      ImportError: cannot import name 'convert_path' from 'setuptools' (/home/runner/work/betterhalf-backend/betterhalf-backend/.tox/py38/lib/python3.8/site-packages/setuptools/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by abravalheri** [comment] 2022-04-05 15:07
Hi @Tiwari1812, can you try updating the version of setuptools in your build environment. I think this was solved in v61.1.0.

**Comment by Tiwari1812** [comment] 2022-04-05 15:14
> Hi @Tiwari1812, can you try updating the version of setuptools in your build environment (to the latest version)? I think this was solved in v61.1.0.

pip install --upgrade pip setuptools==61.1.0 wheel
did this but still having the same issue

**Comment by abravalheri** [comment] 2022-04-05 20:15
Sorry @Tiwari1812 I don't think a call would work for me.

To be able to investigate this issue, I think what is missing is a minimal reproducer.
There are some [guides on the internet](https://stackoverflow.com/help/minimal-reproducible-example), discussing [how to do it](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports). 

For example, based on your description, I would expect the following snippet to be such a reproducer:
```python
virtualenv .venv
.venv/bin/python -m pip install -U pip 'setuptools==62.0.0'
.venv/bin/python -m pip install 'django-allauth==0.42.0'
```
However, that works completely fine.

Can you provide a simple example similar to the 3 lines above that results in the same error you are facing?

**Comment by Tiwari1812** [comment] 2022-04-08 11:10
> Sorry @Tiwari1812 I don't think a call would work for me.
> 
> To be able to investigate this issue, I think what is missing is a minimal reproducer. There are some [guides on the internet](https://stackoverflow.com/help/minimal-reproducible-example), discussing [how to do it](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).
> 
> For example, based on your description, I would expect the following snippet to be such a reproducer:
> 
> ```python
> virtualenv .venv
> .venv/bin/python -m pip install -U pip 'setuptools==62.0.0'
> .venv/bin/python -m pip install 'django-allauth==0.42.0'
> ```
> 
> However, that works completely fine.
> 
> Can you provide a simple example similar to the 3 lines above that results in the same error you are facing?

on local its working fine but on github checks its failing so thats why i am not able to reproduce it

**Comment by abravalheri** [comment] 2022-04-08 12:10
Hi @Tiwari1812, without a reproducer it is impossible to analyse this problem.

With v62.0.0 of `setuptools` you should not reach this error: `ImportError: cannot import name 'convert_path' from 'setuptools'`: if you open the `setuptools/__init__.py` file you are going to find the function defined there.

So my conclusion is that your CI somehow ends up with an older version of setuptools on the PYTHONPATH. That might be caused for a plethora of factors and some of them might very well be external to setuptools.

**Comment by abravalheri** [comment] 2022-04-21 10:34
@Tiwari1812, I think I will close this issue for now since there seems to be no reproduction that we can use to investigate the problem. And without being able to reproduce the problem there is not much we can do.

If you manage to create a minimal reproducer following the tutorials I listed above, please let me know and I will more than happy to re-open this issue.

If you have problems trying to reproduce the issue in a virtual environment, you can also use a docker container or a docker file to simulate a global installation.

**Closed by abravalheri** 2022-04-21 10:34 UTC
Labels: Needs Repro
