### ISSUE TITLE
latest setuptools thinks chdir is in os.path instead of os

### ISSUE THREAD

**Issue by fcntl** [pypa/setuptools#691] opened 2016-07-26 00:56 UTC
```
  Downloading setuptools-25.0.1.tar.gz (610kB): 610kB downloaded
  Running setup.py egg_info for package setuptools
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "XXX/build/setuptools/setup.py", line 194, in <module>
        here and os.path.chdir(here)
    AttributeError: 'module' object has no attribute 'chdir'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "XXX/build/setuptools/setup.py", line 194, in <module>

    here and os.path.chdir(here)

AttributeError: 'module' object has no attribute 'chdir'


```

**Comment by jaraco** [comment] 2016-07-26 03:06
Dupe of #688

**Closed by jaraco** 2016-07-26 03:06 UTC
