### ISSUE TITLE
importlib.metadata entry points might load wrong module and crash

### ISSUE THREAD

**Issue by eli-schwartz** [pypa/setuptools#2390] opened 2020-09-16 03:21 UTC
```
$ sip-build --help
Traceback (most recent call last):
  File "/usr/bin/sip-build", line 33, in <module>
    sys.exit(load_entry_point('sip==5.4.0', 'console_scripts', 'sip-build')())
  File "/usr/bin/sip-build", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
```

I have `python-sip` as well as `sip5` installed on Arch Linux. In the site-packages directory:

```
$ ls -1d sip-*
sip-4.19.24.dist-info/
sip-5.4.0-py3.8.egg-info/
```

The 4.x version installs:
```
sipconfig.py
sipdistutils.py
sip.pyi
sip.so*
```

The 5.x version installs:
```
sipbuild/
```

They're co-installable because people might need the legacy version, still.

...

It appears pkg_resources is fully capable of finding the needed distribution given version constraint on `sip==5.4.0`:
```
>>> import pkg_resources
>>> pkg_resources.load_entry_point('sip==5.4.0', 'console_scripts', 'sip-build')
<function main at 0x7f4febf588b0>
>>> pprint(pkg_resources.get_distribution('sip==5.4.0').get_entry_map())
{'console_scripts': {'sip-build': EntryPoint.parse('sip-build = sipbuild.tools.build:main'),
                     'sip-distinfo': EntryPoint.parse('sip-distinfo = sipbuild.distinfo.main:main'),
                     'sip-install': EntryPoint.parse('sip-install = sipbuild.tools.install:main'),
                     'sip-module': EntryPoint.parse('sip-module = sipbuild.module.main:main'),
                     'sip-sdist': EntryPoint.parse('sip-sdist = sipbuild.tools.sdist:main'),
                     'sip-wheel': EntryPoint.parse('sip-wheel = sipbuild.tools.wheel:main'),
                     'sip5': EntryPoint.parse('sip5 = sipbuild.legacy.sip5:main')}}

```

Not so with importlib.metadata, which AFAICT has no way to specify versions or indeed find multiple versions of one distribution (and is finding the *old* version to boot):

```
>>> from importlib.metadata import distribution
>>> distribution('sip').metadata['Version']
'4.19.24'
>>> distribution('sip').entry_points
[]
```

**Comment by eli-schwartz** [comment] 2020-09-16 03:32
It's not clear what to do here. pkg_resources is slow but reliable, on the other hand, side by side installs of different versions of one distribution seems to be rather an edge case.

I didn't look into what happens if there are different versions on different parts of the PYTHONPATH.

**Comment by jaraco** [comment] 2020-09-21 13:41
> side by side installs of different versions of one distribution seems to be rather an edge case

It's worse than that. Through the introduction of pip, support for multiple distributions of the same name became unsupported. Setuptools had support for multiple installs of the same distribution, but that functionality is discouraged if not actively deprecated.

You could file a ticket with [importlib-metadata](https://gitlab.com/python-devs/importlib_metadata/) (which I also maintain), but that would probably only serve to capture the request and be closed as "won't fix".

If you think this is a use-case that is compelling enough that it deserves reconsideration, you may want to file something with [packaging problems](https://github.com/pypa/packaging-problems/issues). Just keep in mind that this behavior is something that was once supported but then was dropped and would likely require a PEP to revive proper support.

What I recommend for `sip`, if it wishes to support side-by-side support of similar functionality, is to rename the distribution package for the legacy version, perhaps `sip-4-legacy` or similar, and create a new release (4.20). Then anyone (including Arch) could install `sip` and `sip-4-legacy` side-by-side with full Python packaging support.

I don't think there's anything that Setuptools can do here except give the advice above, but feel free to reply if there's more information I can add or if you think there's something Setuptools should do.

**Closed by jaraco** 2020-09-21 13:41 UTC

**Comment by krassowski** [comment] 2020-09-28 08:55
I am getting lots of similar tracebacks on Travis which started failing about two months in one of my side projects (which appears to be "spontaneous"):

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/bin/nbdiff", line 33, in <module>
    sys.exit(load_entry_point('nbdime==2.0.0', 'console_scripts', 'nbdiff')())
  File "/home/travis/virtualenv/python3.7.1/bin/nbdiff", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration

Creating path "reports" for "qc_report_path" output argument

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/bin/nbstripout", line 33, in <module>
    sys.exit(load_entry_point('nbstripout==0.3.9', 'console_scripts', 'nbstripout')())
  File "/home/travis/virtualenv/python3.7.1/bin/nbstripout", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/bin/papermill", line 33, in <module>
    sys.exit(load_entry_point('papermill==2.2.0', 'console_scripts', 'papermill')())
  File "/home/travis/virtualenv/python3.7.1/bin/papermill", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/bin/papermill", line 33, in <module>
    sys.exit(load_entry_point('papermill==2.2.0', 'console_scripts', 'papermill')())
  File "/home/travis/virtualenv/python3.7.1/bin/papermill", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/bin/nbdiff", line 33, in <module>
    sys.exit(load_entry_point('nbdime==2.0.0', 'console_scripts', 'nbdiff')())
  File "/home/travis/virtualenv/python3.7.1/bin/nbdiff", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
```

I am completely lost and unable to reproduce this locally. Would you be able to please suggest where the issue might originate from? I appreciate your time and sorry about posting in the already closed issue.

**Comment by jaraco** [comment] 2020-10-03 18:09
The `StopIteration` occurs when `importlib_load_entry_point` fails to find the relevant package. So somehow in your environment, the metadata for the packages `nbdime`, `papermill`, and `nbstripout` are missing or otherwise not found by `importlib_metadata`. The issue only occurs when using `setup.py install` because that's the codepath that uses easy_install with this script launcher technique.

**Comment by miraculixx** [comment] 2021-11-23 09:34
In my case this error occurred when installing the package in editable mode (`pip install -e .`), while when installed normally the entry point worked fine (`pip install .`)  

It turns out where was a directory "<package>.egg-info" in the package's directory, probably from a previous install. Fix was to remove this directory and run `pip install -e .`  again.

**Comment by moan0s** [comment] 2022-04-15 07:21
Thank you this helped me a lot! 🥳
