### ISSUE TITLE
[FR] support pep-621 - storing core project metadata in pyproject.toml

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pypa/setuptools#2671] opened 2021-05-11 04:58 UTC
### What's the problem this feature will solve?

this is intended to build on #1688 

with [PEP-621](https://www.python.org/dev/peps/pep-0621/) python packaging has been extended with a standard to include core metadata in `pyproject.toml`

### Describe the solution you'd like

in order for setuptools to support it i beleive i see the need for the following steps

- [ ] basic toml support in setuptools (just mirroring setup.cfg in pyproject.toml, as setup.cfg is still a supoerset of that the peps support
- [ ] a loader for pep-621 meta-data (ideally via packaging)
- [ ] #3415
- [ ] warnings for usages of `tool.setuptools` when core package metadata is viable (maybe via jsonschema + its deprecation mechanism) 

### Additional context

[Support incremental complexity and build steps for packages](https://github.com/pypa/packaging-problems/issues/248)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by con-f-use** [comment] 2022-02-12 15:03
Just for clarification, because true to my nick, I'm a little bit confused. Can I put core metadata from PEP 621 into my `pyproject.toml` and expect that work with setuptools? What happens today (version 60.8.2) if I put core metadata into `pyproject.toml` and delete the duplicates from `setup.cfg`?

**Comment by abravalheri** [comment] 2022-02-12 15:14
Hi @con-f-use, not yet. This feature is still under active development/review.

**Comment by abravalheri** [comment] 2022-05-11 12:13
Hi @RonnyPfannschmidt, the basics of the support have been implemented now.
Do you think there is something left in this ticket that is not implemented yet? Or should we just close it?

**Comment by RonnyPfannschmidt** [comment] 2022-05-11 12:20
@abravalheri i haven't been on top of this one

Is toml Metadata avaliable to setuptools extensions?

**Comment by abravalheri** [comment] 2022-05-11 12:23
Could you describe a bit more what making toml Metadata avaliable to extensions would mean?
Is there any existing mechanism for `setup.cfg` metadata?

**Comment by RonnyPfannschmidt** [comment] 2022-05-11 12:28
No, which makes Integration painful

**Comment by abravalheri** [comment] 2022-05-11 12:32
Thank you very much Ronny for clarifying that.
This looks like a fair request. If we manage to put up the requirements for this feature (or at least have an idea on how it would look like), I can do some investigation and work on that sometime in the near future (no promises though :P).

**Comment by abravalheri** [comment] 2022-05-11 12:49
Depending on the hook the plugin implements, the `dist` object will have its attributes set to the corresponding values in `pyproject.toml`, the problem is that the majority of the existing hooks run before the parsing of the configuration.

Are the `dist` attributes enough or would this feature be something different?

**Comment by abravalheri** [comment] 2022-06-07 16:04
Thank you @bhrutledge, I will have a look on that.

**Comment by RonnyPfannschmidt** [comment] 2022-06-07 22:03
:+1:

**Comment by abravalheri** [comment] 2022-06-26 10:29
I am splitting the remaining aspects of the feature request in #2671.
Anyone interested please feel free to add comments there.

**Closed by abravalheri** 2022-06-26 10:29 UTC
Labels: enhancement, major, Needs Discussion, Needs Implementation

**Comment by agronholm** [comment] 2022-06-26 10:32
Did you just link to this same issue?

**Comment by abravalheri** [comment] 2022-06-26 10:41
Woops, thanks @agronholm.

**Comment by abravalheri** [comment] 2022-06-26 11:01
My interpretation of the status of the original steps is:

- > basic toml support in setuptools (just mirroring setup.cfg in pyproject.toml, as setup.cfg is still a supoerset of that the peps support

  Basic support for `pyproject.toml` configuration is currently implemented in setuptools.
  I am being **very** conservative about the `[tool.setuptools]` table because I want us to use this opportunity to reflect what would be the best shape for this data structure (ideally simplifying stuff), not only mirror what is currently available in `setup.cfg`.
  I cannot do that alone, though, so I would appreciate input on this aspect.

- > a loader for pep-621 meta-data (ideally via packaging)

  The existing implementation uses tomli to load `pyproject.toml` and then a series of custom functions to apply the data to the distribution class. But I am happy to replace it if `packaging` implements the required APIs. Related to the discussion of https://github.com/pypa/packaging/pull/518.
 
- > hooks to pull in the pep-621 metadata

  I understand that this refers to `setuptools` plugins. I am tracking this in #3415 
 
- > warnings for usages of tool.setuptools when core package metadata is viable (maybe via jsonschema + its deprecation mechanism)

  The existing implementation will raise a validation error if someone tries to specify `tool.setuptools.name`, `tool.setuptools.version` etc...
