### ISSUE TITLE
Add support for pipfile

### ISSUE THREAD

**Issue by felix-ht** [pypa/setuptools#1958] opened 2020-01-08 13:19 UTC
Pipfile seems to be the new standard of how to deal with the dependencies in python.
Setuptools however does not provide functionality to use pipfile to define a package.

Pipenv is a cli tool so it shoud not deal with this kind of stuff, as one would have to add it to projects depencies -> https://github.com/pypa/pipenv/issues/209#issuecomment-337241138.

To me setuptools seems like the right place to do this. So it would be great if this could be added.
A potential solution might look something like this:

```py
from setuptools import setup, find_packages, load_pipfile

setup(
    name="example",
    license="MIT",
    maintainer="Oteph",
    version="1.0.0",
    description="A pipfile example",
    packages=find_packages(),
    include_package_data=True,
    **load_pipfile()
)

## load_pipfile should probably provide an option to specify the 
## location of the pipfile. 

## load_pipfile() would return something like:

{
    "python_requires":">=3.6",
    "install_requires":[
        "some_package"
    ]
}



```

**Comment by abravalheri** [comment] 2022-01-05 23:14
Hi @felix-ht, thank you very much for the discussion.

My understanding is that Pipfile targets reproducible "applications", with pinned versions for their dependencies.
The major focus of setuptools would be "libraries", with ranges of versions for their dependencies.

There is some conceptual difference between the two that is explained in detail in https://caremad.io/posts/2013/07/setup-vs-requirement/ and https://pyscaffold.org/en/stable/dependencies.html.

Therefore I think this feature would not make much sense here.
Instead setuptools should be moving towards to the way PEP 621 specifies dependencies (which is not much different from the current implementation).

Please also notice that the new spec in development (PEP 665) might end up having support for [source distributions](https://discuss.python.org/t/a-file-format-to-list-python-dependencies-of-an-application-without-strict-reproducibility-guarantees/12218). If that is the case, the opposite approach would be viable.

If your use case still requires something like `load_pipfile`, I think the best approach here would be creating a 3rdParty module that can be used in `setup.py` (you can add it as a build-time dependency in `pyproject.toml` so it will get automatically installed and available).

**Closed by abravalheri** 2022-01-05 23:14 UTC

**Comment by felix-ht** [comment] 2022-01-06 00:11
@abravalheri 
The argument of the first article is that much that the requirements txt is supposed to be used as a lockfile while the setup tools should give a rough outline of the the requirements. This separation of concern is supposed to enable self hosted packages.

My two cents on this:
* Requirements txt sucks as a lockfile (no hashing)
* As a user i just don't want to specify the same thing in two places - the different concerns argument is very weak
* Lockfiles should be managed by the tooling not by the user
* Self hosting does not depend on this split - a single file can do this just fine

The setups tools requirements.txt split creates needless complexity with very limit benefits for the user. 
Modern packaging systems have one requirements file managed by the user and one lock file managed by the system. Overriding packages works fine in these systems as well. See for example pubspec(.yaml) for dart or poerty - pyproject.toml  for python. 

As a side Note:
Pipenv doesn't deal with packing and is forcing one to have a pipfile + pipfile.lock + setup.py + requirements.txt which is the worst of all worlds. For this reason (and many others) I converted all my packages to poetry. (So I no longer need the pipfile integration into setup tools)

**Comment by abravalheri** [comment] 2022-01-06 00:35
Thank you very much for the feedback. I think your current approach is a very good one, poetry seems to be an excellent choice for this use case.

I just would like to point out that my idea on linking these articles was not suggesting to use 'requirements.txt', just provide a reference for the "conceptual" side of it. I completely agree that a lock file should have hashes...

(I also did not suggest to repeat the specifications of the deps in two files. Ideally the user should specify them once in the setup.cfg or pyproject.toml and a tool would use this info to properly lock the dependencies - which is more or less how poetry works. The second link, although mentioning PyScaffold, gives some hints on how that could be achieved with Pipenv and pip-tools... but I think the situation will be improved after PEP 665)

**Comment by Splines** [comment] 2024-03-15 10:58
It'd be awesome if `setuptools` had support for a **`Pipfile`** generated by `pipenv install <dependency>`. It might look like this:

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
plum-dispatch = "~=2.3"

[dev-packages]
pylint = "~=3.0"
pytest = "~=8.1"

[requires]
python_version = "3.11"

```

Then, setuptools could go ahead, parse the `[packages]` section and add it to the `pyproject.toml` (or an internal representation) as if the user had manually specified:

```
[project]
dependencies = [
    "plum-dispatch ~= 2.3"
]
```

This way, I wouldn't have to manually copy over the dependencies and potentially risk that my `Pipfile` and the `pyproject.toml` get out of sync.
